### ISSUE TITLE
Visual Recognition doesn't recognize IAM_APIKEY and URL from credentials.env provided by the service.

### ISSUE THREAD

**Issue by kyokonishito** [watson-developer-cloud/node-sdk#1004]
**Overview**
Visual Recognition doesn't recognize IAM_APIKEY and URL from credentials.env provided by the service.
When I put the credentials.env provided by the visual recognition service to the working directory, the api returns 'Error: Missing required parameters: apikey'.

**Expected behavior**
The apikey is loaded from credentials.env.

**Actual behavior**
the api returns 'Error: Missing required parameters: apikey'.

**How to reproduce**
1. Download credentials.env to the working directory of #2 code  from Visual Recognition service.
2. Run following code with node.js

```
var VisualRecognitionV3 = require('ibm-watson/visual-recognition/v3'); 
var visualRecognition = new VisualRecognitionV3({ 
  version: '2018-05-01'
});
```
**Screenshots**
_If applicable, add screenshots to help explain your problem._

**SDK Version**
v5.2.0

**Additional information:**
The SDK only reads the variables started  from WATSON_VISION_COMBINED_.
However the values of credentials.env are started from VISUAL_RECOGNITION_.
SDK v4 reads both values.

**Comment by msalimbe1** [comment]
You need to pass it to the constructor:

 ```var VisualRecognitionV3 = require('ibm-watson/visual-recognition/v3'); 
var visualRecognition = new VisualRecognitionV3({ 
  version: '2018-05-01',
  apikey: 'YOU_IAM_API_KEY_VARIABLE'
});
```

**Comment by kyokonishito** [comment]
My issue is the sdk  does not read the api key from the credentials.env provided by the service [explained as README.md](https://github.com/watson-developer-cloud/node-sdk#credentials-file-easier), not how to pass the APIKEY.

**Comment by germanattanasio** [comment]
This is a known issue and we are working on the fix. 

The SDK will recognize `VISUAL_RECOGNITION_` which is the one that in the credentials file.

In the meantime can you use the snippet from @msalimbe1? 

```
const visualRecognition = new VisualRecognitionV3({ 
 version: '2018-05-01',
 apikey: process.env.VISUAL_RECOGNITION_IAM_APIKEY
});
```

**Comment by germanattanasio** [comment]
Related to https://github.com/watson-developer-cloud/node-sdk/issues/994

**Comment by kyokonishito** [comment]
@germanattanasio Thank you!  I will pass the api key as your code  until getting the fix.

**Comment by tanushreepaul04** [comment]
**The same issue is there with Watson Assistant. Not reading from ibm-credential.env file.**
If IAM creadential is given in a ibm-credential.env file, AsistantV2  can not read it from that ".env" 
Always throwing **Error: Missing required parameters: apikey**.
It only works if the credentials are passed in constructor directly.

**Comment by germanattanasio** [comment]
@tanushreepaul04 Can you please show us the keys in the `ibm-credentials.env` file? I think it's related to the keys not being the ones that the SDK is looking for
