### ISSUE TITLE
Custom SDK bundle for browsers with accessToken authentication support.

### ISSUE THREAD

**Issue by nevrologica** [watson-developer-cloud/node-sdk#1006]
Looking at previous resolved issues i found a closed one (#30) that i don't understand if it has been resolved with added feature or not.

I attemped to build a custom library including only a subset of services for use client-side on browsers.
I made a new directory in the root folder and included that index.js

```
'use strict';

exports.ToneAnalyzerV3 = require('ibm-watson/tone-analyzer/v3');
exports.NaturalLanguageUnderstandingV1 = require('ibm-watson/natural-language-understanding/v1');
exports.SpeechToTextV1 = require('ibm-watson/speech-to-text/v1');
exports.TextToSpeechV1 = require('ibm-watson/text-to-speech/v1');
exports.Authenticator = require('ibm-watson/auth');
```
That is my package dependencies from the package.json after installing browserify and tinyify.

```
{
  "name": "watson-developer-cloud-custom-bundle",
  "version": "1.0.0",
  "description": "Use the Watson JS SDK in browsers via browserify",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "author": "",
  "license": "Apache-2.0",
  "dependencies": {
    "browserify": "^16.5.0",
    "ibm-watson": "latest",
    "tinyify": "^2.5.2"
  },
  "devDependencies": {},
  "engines": {
    "node": ">=6"
  }
}
```
I generate the new bundle like this:
```
browserify -p tinyify index.js --standalone Watson > watson-sdk.min.js
```
I can see the included prototypes of the bundle when i load it in browser.
![image](https://user-images.githubusercontent.com/29121228/71071902-22b76500-2186-11ea-8f3e-79dd61b148cc.png)

While i have been trying to instantiate a class i have come accross some examples using different techniques like the following:
```
const speechToText = new SpeechToTextV1({
  authenticator: new IamAuthenticator({ apikey: '<apikey>' }),
  url: 'https://stream.watsonplatform.net/speech-to-text/api/'
});

var speechToText = new SpeechToTextV1({
  username: 'INSERT YOUR USERNAME FOR THE SERVICE HERE',
  password: 'INSERT YOUR PASSWORD FOR THE SERVICE HERE',
  url: 'https://stream.watsonplatform.net/speech-to-text/api/'
});
```

Since i already have an API made in PHP that produces the accessToken from the credentials of my services, and because i don't want to expose the service credentials either in the client-side code or embeded into the library sdk, how can i instantiate a service using the prefetched accessToken i have? Reading on #30 about the token expiration, i have solved this by fetching a fresh token from my API if a request from the client validates as unauthenticated, or also if the endpoint is down since i have a failover support embeded with two services credentials just in case, so i handle the tokens properly through my API and client side code that fetches fresh ones, i just need to hide the credentials from eyesight and use the produced accessToken, if possible. Is there an example somwhere if this is supported?

Thats a sample of a token object I am currently using.
![image](https://user-images.githubusercontent.com/29121228/71072342-f7814580-2186-11ea-969d-098e9a5fdb67.png)

And further to my question, since i can see that axios is being used for the services POST or GET requests if not a websocket connection is used (STT/TTS), are the promises resolved inside the library synchronously or do i have to call them with an 'async' function and having to 'await' until i get back a response?

I am also eager to know if the STT accepts a mediaStream passed in as a paramter (so that i don't have to rewrite microphone access code since i have that before i start the service), and if a TSS accepts an audio object passed in as a parameter (so that i can reuse one audio object, because that technique seems to work better for mobile support).

Lastly my intention is to use a future supported sdk that i can get a subset of services into a bundle in order to use it from various browsers. I am currently using the speech javascript sdk that offers a few out of the box features like handling microphone access etc, but i really want to further the exploration of the services and be able to use custom models, train them, and have something used that will be maintained in the future in order to get new updates and reproduce my custom bundle.

**Comment by germanattanasio** [comment]
I will work with the services to make sure CORS is enabled
