### ISSUE TITLE
Getting 404 error on Watson Assistant V2

### ISSUE THREAD

**Issue by vladaman** [watson-developer-cloud/node-sdk#1008]
I am trying to use V2 and I get 404 error - resource not found. Any reason why?
```javascript
const AssistantV2 = require('ibm-watson/assistant/v2');
const IamAuthenticator = require('ibm-watson/auth').IamAuthenticator;
const uuidv4 = require('uuid/v4');

const assistant = new AssistantV2({
    authenticator: new IamAuthenticator({
        apikey: '--api-key-here--'
    }),
    // url: 'https://gateway.watsonplatform.net/assistant/api/',
    // url: 'https://api.us-south.assistant.watson.cloud.ibm.com',
        url: 'https://api.us-south.assistant.watson.cloud.ibm.com/instances/uuid-here',
        version: '2019-02-28'
});

const ASSISTANT_ID = 'uuid-here';

assistant.createSession({
        assistantId: ASSISTANT_ID
    })
    .then(res => {
        console.log(JSON.stringify(res, null, 2));
    })
    .catch(err => {
        console.log(err);
    });
```

**Comment by germanattanasio** [comment]
Your `ASSISTANT_ID` and your `instance-id` are different. Try using `https://api.us-south.assistant.watson.cloud.ibm.com` as the service url.

Take a look at the `DEBUG` section and see if you can find the problem https://github.com/watson-developer-cloud/node-sdk#debug

**Comment by nicolascatalan** [comment]
you found solution?

**Comment by oyundari1205** [comment]
> I am trying to use V2 and I get 404 error - resource not found. Any reason why?
> 
> ```js
> const AssistantV2 = require('ibm-watson/assistant/v2');
> const IamAuthenticator = require('ibm-watson/auth').IamAuthenticator;
> const uuidv4 = require('uuid/v4');
> 
> const assistant = new AssistantV2({
>     authenticator: new IamAuthenticator({
>         apikey: '--api-key-here--'
>     }),
>     // url: 'https://gateway.watsonplatform.net/assistant/api/',
>     // url: 'https://api.us-south.assistant.watson.cloud.ibm.com',
>         url: 'https://api.us-south.assistant.watson.cloud.ibm.com/instances/uuid-here',
>         version: '2019-02-28'
> });
> 
> const ASSISTANT_ID = 'uuid-here';
> 
> assistant.createSession({
>         assistantId: ASSISTANT_ID
>     })
>     .then(res => {
>         console.log(JSON.stringify(res, null, 2));
>     })
>     .catch(err => {
>         console.log(err);
>     });
> ```

how did you solve this error? Thanks

**Comment by christianduncan** [comment]
Why is this closed has anyone found solution? Please re-open

**Comment by dpopp07** [comment]
> Try using https://api.us-south.assistant.watson.cloud.ibm.com as the service url.

Have you tried this approach? The problem was addressed in [this comment](https://github.com/watson-developer-cloud/node-sdk/issues/1008#issuecomment-570223861)
