### ISSUE TITLE
 Not Found: Invalid Session

### ISSUE THREAD

**Issue by ZALESCHI** [watson-developer-cloud/node-sdk#1009]
Hello guys,
I tryed to use v2 integration but return the error:
message: 'Invalid Session',
How can i have this session id?
![image](https://user-images.githubusercontent.com/11997891/72101879-7855dc00-3304-11ea-8da6-4f7ee2708d17.png)

**Comment by dpopp07** [comment]
You will need to create a session first. You can use the `createSession` method to do this.

**Comment by ZALESCHI** [comment]
How i can do it?have a tutorial? ty for the help

**Comment by ZALESCHI** [comment]
like this ?
assistant.createSession({
    assistant_id: 'XXX-XXX-XXX-XXX'
})
    .then(res => {
        console.log(JSON.stringify(res, null, 2));
    })

**Comment by dpopp07** [comment]
Like this: where `assistantId` is lower camel case (if you are using v5)

```
assistant.createSession({
  assistantId: 'XXX-XXX-XXX-XXX'
})
.then(res => {
  console.log(JSON.stringify(res, null, 2));
})
```

Does that solve your problem?

**Comment by ZALESCHI** [comment]
Hello, yes its works for me, thanks for the help, sorry for delay to response

**Comment by dpopp07** [comment]
Glad to hear!
