### ISSUE TITLE
NLC createClassifier throwing missing metadata error

### ISSUE THREAD

**Issue by chughts** [watson-developer-cloud/node-sdk#1010]
I am using ibm-watson v 5.2.1
Node v 10.16.3

I am able to create a classifier using CURL but get an error trying to create the classifier using the Node.js ibm-watson SDK. The error is suggesting metadata is missing, but all metadata has been provided. 

I suspect that the SDK is not passing the language metadata to the underlying REST API correctly. 

I have created a simple app based on the sample in the API Documentation 

```Node.js

var fs = require('fs');

const NaturalLanguageClassifierV1 = require('ibm-watson/natural-language-classifier/v1');
const { IamAuthenticator } = require('ibm-watson/auth');

const naturalLanguageClassifier = new NaturalLanguageClassifierV1({
  authenticator: new IamAuthenticator({
    apikey: 'c1...'
  }),
  url: 'https://api.us-south.natural-language-classifier.watson.cloud.ibm.com/instances/1b1fc352-b588-46f9-b97d-f8fedf4df3f7'
});

const createClassifierParams = {
  trainingMetadata: JSON.stringify({
    name: 'My Test classifier',
    language: 'en',
  }),
  trainingData: fs.createReadStream('../weather_data_train.csv'),
};

naturalLanguageClassifier.createClassifier(createClassifierParams)
  .then(response => {
    const classifier = response.result;
    console.log(JSON.stringify(classifier, null, 2));
  })
  .catch(err => {
    console.log('error:', err);
  });

```

but this throws an error

````
  name: 'Bad Request',
  code: 400,
  message: 'Missing metadata',
  body:
   '{"code":400,"error":"Missing metadata","description":"The required training metadata is missing. The request should contain \'language\' and \'name\' besides the training data."}',
````

**Comment by dpopp07** [comment]
@chughts Thanks for the issue. This looks like it may be a bug. I will investigate soon

**Comment by dpopp07** [comment]
@chughts Turns out, this is an error in the example. The `trainingMetadata` parameter is meant to be a file, as it is documented. The example _should_ read:
```js
const createClassifierParams = {
  trainingMetadata: fs.createReadStream('../metadata.json'),
  trainingData: fs.createReadStream('../weather_data_train.csv'),
};
```

where `metadata.json` contains your information:
```json
{
    "name": "My Test classifier",
    "language": "en"
}
```

I will make sure to get the example updated. Thanks again for the issue!

**Comment by chughts** [comment]
@dpopp07 thanks for the information. Just wanted to document that in my case this translates to 

```
trainingMetadata: Buffer.from(JSON.stringify(meta)),
``` 

which does work.
