### ISSUE TITLE
Text-To-Speech: RangeError [ERR_OUT_OF_RANGE] when using audio/mp3 OR audio/mpeg as media type

### ISSUE THREAD

**Issue by ankurranpariya4066** [watson-developer-cloud/node-sdk#1017]
There is an issue in repairWavHeaderStream function when using mimeType = audio/mp3 or audio/mpeg with text-To-Speech SDK.

If we use audio/wav mime type with same content, Everything goes well without any error.

For MP3 / MPEG, Text To Speech fails and returns following error:

> RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 22375. Received -1052485267,    
> at boundsError (internal/buffer.js:58:9),    
> at Buffer.readInt32LE (internal/buffer.js:286:5),    
> at TextToSpeechV1._this.repairWavHeader (/our-project-directory/node_modules/ibm-watson/text-to-speech/v1.js:82:45),    
> at IncomingMessage.<anonymous> (/our-project-directory/node_modules/ibm-watson/text-to-speech/v1.js:45:35),    
> at IncomingMessage.emit (events.js:198:15),    
> at IncomingMessage.EventEmitter.emit (domain.js:481:20),    
> at endReadableNT (_stream_readable.js:1142:12),    
> at processTicksAndRejections (internal/process/task_queues.js:81:17)

ibm-watson package version => 5.3.0
Node version: v11.13.0

Code to reproduce the issue:
```
var watson = require('ibm-watson/text-to-speech/v1'),
    IamAuthenticator = require('ibm-watson/auth'),
    fs = require('fs');

var mediaText = {
	text: 'Hi This is Ankur Ranpariya and trying to generate new mp3 file with large content to see if it is working or not.',
	accept: 'audio/mp3',
	voice: 'en-US_LisaV3Voice'
}

var textToSpeech = new watson({
    authenticator: new IamAuthenticator.IamAuthenticator({ apikey: 'API_KEY' }),
    url: 'https://stream.watsonplatform.net/text-to-speech/api/'
});

textToSpeech.synthesize(mediaText).then(response => {
    const audio = response.result;
    return textToSpeech.repairWavHeaderStream(audio);
}).then(finalAudio => {
	fs.writeFileSync("testAudio.mp3", finalAudio);
	return response.status(200).send({status: "Ok!"});
}).catch(err => {
    return response.status(500).send({error: err.message})
});
```

**Comment by dpopp07** [comment]
@ankurranpariya4066 the `repairWavHeaderStream` method is only applicable to WAV files. WAV files have a corrupted header when they are returned that needs to be repaired. This is not the case for audio of other formats, like `mp3`.
