### ISSUE TITLE
getaddrinfo ENOTFOUND getaddrinfo ENOTFOUND"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname": iam.bluemix.net iam.bluemix.net:443

### ISSUE THREAD

**Issue by cmpmohan** [watson-developer-cloud/node-sdk#1019]
**Overview**

We have a nodeJS application that is running in a container and it includes an IBM apikey.

**Actual behavior**
```
Error occurred while trying to retrieve all the existing Watson Discovery service instance environments. - {"stack":"Error: getaddrinfo ENOTFOUND iam.bluemix.net iam.bluemix.net:443\n at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","message":"getaddrinfo ENOTFOUND iam.bluemix.net iam.bluemix.net:443","errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"iam.bluemix.net","host":"iam.bluemix.net","port":443}
```

**SDK Version**

**Additional information:**
node 8

**Comment by germanattanasio** [comment]
@cmpmohan do you have an IBM Cloud apikey or a Watson Discovery apikey? they are different.

**Comment by cmpmohan** [comment]
Yes we have.. looks like issue resolved once we have updated proxy details inside container

**Comment by amitchauhanKN** [comment]
I am facing the same issue, what am i suppose to do ?

A 2020-10-22T04:38:35Z { Error: getaddrinfo ENOTFOUND twcservice.eu-gb.mybluemix.net twcservice.eu-gb.mybluemix.net:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
 
A 2020-10-22T04:38:35Z   errno: 'ENOTFOUND',
 
A 2020-10-22T04:38:35Z   code: 'ENOTFOUND',
 
A 2020-10-22T04:38:35Z   syscall: 'getaddrinfo',
 
A 2020-10-22T04:38:35Z   hostname: 'twcservice.eu-gb.mybluemix.net',
 
A 2020-10-22T04:38:35Z   host: 'twcservice.eu-gb.mybluemix.net',
 
A 2020-10-22T04:38:35Z   port: '443' }
 
A 2020-10-22T04:38:35Z str is Error: getaddrinfo ENOTFOUND twcservice.eu-gb.mybluemix.net twcservice.eu-gb.mybluemix.net:443
