### ISSUE TITLE
IBM skill (dialog) doesn't return the main intent or dialog name with final response

### ISSUE THREAD

**Issue by aumerhadi** [watson-developer-cloud/node-sdk#1025]
**Overview**
IBM dialog doesn't return the main intent or dialog name with the final response (after collecting all entities) 
even with return_context: true
Without the intent or dialog name, the backend server doesn't know how to process this request
even with return context enabled
`'options': {
                'return_context': true
}`

**Expected behavior**
the final response should include main intent or dialog name,

**Actual behavior**
No intent name or dialog name with the  JSON response

```
{
  "entities": {
    "output": {
      "generic": [],
      "intents": [],
      "entities": [
        {
          "entity": "sys-date",
          "location": [
            0,
            4
          ],
          "value": "2001-01-01",
          "confidence": 1,
          "metadata": {
            "calendar_type": "GREGORIAN",
            "timezone": "GMT"
          }
        },
        {
          "entity": "sys-date",
          "location": [
            0,
            4
          ],
          "value": "2001-12-31",
          "confidence": 1,
          "metadata": {
            "calendar_type": "GREGORIAN",
            "timezone": "GMT"
          }
        },
        {
          "entity": "sys-number",
          "location": [
            0,
            4
          ],
          "value": "2001",
          "confidence": 1,
          "metadata": {
            "numeric_value": 2001
          }
        }
      ]
    },
    "context": {
      "global": {
        "system": {
          "turn_count": 4
        }
      },
      "skills": {
        "main skill": {
          "user_defined": {
            "carbrand": "honda",
            "carcolor": "Blue",
            "number": 2001
          },
          "system": {}
        }
      }
    }
  }
}
```

**How to reproduce**
I created a simple node.js application using Watson assistant v2 you can find the code here [(https://github.com/aumerhadi/simple_watson_v2)](https://github.com/aumerhadi/simple_watson_v2)
create a new Watson skill and assistant. and add new intent #AddCar, and entities @breand, @color, @year (you can use any scenario for single question with multiple entities)
the request will be sent from postman to node.js application (details in readme file)
check the final response when Watson collects all entities
the response from Watson doesn't include intent or dialog name

**Screenshots**

**SDK Version**
IBM Watson SDK v2 - Node.js

**Additional information:**
Node v: 10.16.3

**Comment by dpopp07** [comment]
I am not sure why you would be seeing this behavior but it is not likely an issue with the SDK.

What is the date you are using for `version`? @rrberry are you aware of any change in behavior that would explain this between version dates?

**Comment by rrberry** [comment]
Nothing I know of.

**Comment by aumerhadi** [comment]
> 
> 
> I am not sure why you would be seeing this behavior but it is not likely an issue with the SDK.
> 
> What is the date you are using for `version`? @rrberry are you aware of any change in behavior that would explain this between version dates?

I am using 2019-02-28, I didn't try another version, is there any other version you recommend ?

**Comment by dpopp07** [comment]
@aumerhadi what happens if you invoke this request using a `curl` command? Do you see the same behavior?

**Comment by aumerhadi** [comment]
@dpopp07 I never tried it with `curl`, I will test and share the result

**Comment by aumerhadi** [comment]
@dpopp07  I got the same response, no intent include

```
{
  "output": {
    "generic": [],
    "intents": [],
    "entities": [
      {
        "entity": "carcolor",
        "location": [
          0,
          3
        ],
        "value": "Red",
        "confidence": 1
      }
    ]
  },
  "context": {
    "global": {
      "system": {
        "turn_count": 4
      }
    },
    "skills": {
      "main skill": {
        "user_defined": {
          "number": 2018,
          "carbrand": "honda",
          "carcolor": "Red"
        },
        "system": {}
      }
    }
  }
}
```

**Comment by dpopp07** [comment]
Okay, so there's nothing we can do in the SDK to change your result. I will ask someone that works on Assistant to comment on the issue

**Comment by mitchmason** [comment]
To clarify for the rest of the team, this is not an issue with the SDK. When calling the /message API, the intents/entities returned are for the previous message only. So I am assuming the input was very short and no intent was identified for that specific turn, hence no intent is returned. To return the dialog diagnostic information try setting debug:true instead of context. The debug information should contain the necessary dialog node information you are looking for.
