### ISSUE TITLE
Issue loading in-browser in IE11

### ISSUE THREAD

**Issue by kevinkbender** [watson-developer-cloud/node-sdk#1027]
**Overview**
If we include ibm-watson 5.4.0 in our page, the page doesn't load in IE11 due to use of ES6 syntax.

I couldn't find a browser list on this repo anywhere, but README.md does say that it "should work in the browser" so I hope it's appropriate to create a bug for this.

I believe the issue is related to dependencies used by the sdk (camelcase, file-type, debug).  Do you have any recommendation for a solution with ES5 compatibility?

**Expected behavior**
Expected page to load.

**Actual behavior**
Script error related to ES6 syntax.

**How to reproduce**
Include ibm-watson 5.4.0 anywhere on your site and then open it in IE11.

**SDK Version**
5.4.0

**Comment by germanattanasio** [comment]
Did you look at https://github.com/watson-developer-cloud/node-sdk/tree/master/examples/browserify? It's an example of how to browserify the node-sdk
