### ISSUE TITLE
Explain where to find the version dates

### ISSUE THREAD

**Issue by dandv** [watson-developer-cloud/node-sdk#1032]
I'm looking at the samples in the README, and they all use some YYYY-MM-DD version numbers such as `version: '2018-04-05'` (except for the [Language Translator](https://github.com/watson-developer-cloud/node-sdk#language-translator) sample, which uses `YYYY-MM-DD` literally :eyes:).

Where does one find the available versions?

Is there a `latest` designation?

The [Usage](https://github.com/watson-developer-cloud/node-sdk#usage) section glosses over this: `version: '{version}'`.

**Comment by dpopp07** [comment]
@dandv Thanks for the issue. You can find information about versioning in the [official API/SDK documentation](https://cloud.ibm.com/apidocs/language-translator/language-translator#versioning). When in doubt, you can always use today's date to get the "latest". The important thing is that once you've set a date for your application, you don't change it (unless you intentionally want to move to a newer version).
