### ISSUE TITLE
Multi-byte characters break analysis

### ISSUE THREAD

**Issue by dandv** [watson-developer-cloud/node-sdk#1033]
Apparently, multi-byte Unicode characters such as emojis confuse the offset of some words. A minimal reproduction is below:

```js
const response = await nlu.analyze(
  {
    text: 'Unicode characters like 🧐 confuse word offsets:\nBrave partners with Binance to bring in-browser liquidity to 13 M users',
    features: {
      entities: {},
    },
  });
console.log(response.result.entities[0]);
```

The first entity is `rave partners ` (not talking about `partners` being a verb here; just the chopped off first letter).

Using `version: '2020-03-26'`.

**Comment by dandv** [comment]
Unstale

**Comment by germanattanasio** [comment]
@dandv this looks like a problem with the service not the SDK. I will see if I can find someone to look into this. Sorry for the delay

**Comment by idfah** [comment]
@dandv @germanattanasio I believe that this issue should now be fixed.  Can someone please check if this is still happening?  Thank you.
