### ISSUE TITLE
Keyword with punctuation inconsistently detected

### ISSUE THREAD

**Issue by dandv** [watson-developer-cloud/node-sdk#1034]
The keyword `ICE Clear U.S.` is correctly detected in

> Today, we're pleased to update you on the launch of bitcoin futures contracts developed by Bakkt in collaboration with ICE Futures U.S. and ICE Clear U.S.
>
> Buy IBM!

![image](https://user-images.githubusercontent.com/33569/77563582-52fd6500-6f26-11ea-8000-61c65ac1d611.png)

...but not detected in

> Today, we're pleased to update you on the launch of bitcoin futures contracts developed by Bakkt in collaboration with ICE Futures U.S. and ICE Clear U.S.
> 
> Today it rained at IBM.

![image](https://user-images.githubusercontent.com/33569/77563413-20536c80-6f26-11ea-8fc3-542d33c60977.png)

**Comment by dandv** [comment]
Unstale

**Comment by germanattanasio** [comment]
Similar to https://github.com/watson-developer-cloud/node-sdk/issues/1033 I think this could be a problem with the service.
