### ISSUE TITLE
"entities: cannot analyze: downstream issue" on text with emojis

### ISSUE THREAD

**Issue by dandv** [watson-developer-cloud/node-sdk#1035]
Apparently, multi-byte Unicode characters such as emojis [also](https://github.com/watson-developer-cloud/node-sdk/issues/1033) cause a "downstream issue" for `analyze`. A minimal reproduction is below. I've set the `language` to `en` [as suggested on SO](https://stackoverflow.com/questions/50424019/watson-nlu-giving-downstream-issue-500-in-a-loop-but-not-on-the-sentence-indi#comment87877700_50424019), but I still get the error.

```js
const response = await nlu.analyze(
  {
    language: 'en',
    text: `🚨Here is what happened🚨

Dogs bark. 🤔

The government quit. 🤔

6 Trillion! #bitcoin
`,
    features: {
      entities: {},
      keywords: {},
    },
  });
console.log(response.result.warnings[0]);  // entities: cannot analyze: downstream issue
```

The `keywords` are returned successfully.

Using `version: '2020-03-26'`.

**Comment by germanattanasio** [comment]
Can you test sending a json file in curl with the same content? I'm wondering if it's a service issue or if the SDK is doing something with the encodign...
