### ISSUE TITLE
IamAuthenticator fetching a new token on every request

### ISSUE THREAD

**Issue by ljoseppi** [watson-developer-cloud/node-sdk#1038]
**Overview**
We've received the following email:

> Hello, 
>  
> I am reaching out on behalf of the Identity and Access Management team at IBM Cloud. We noticed that your service is calling the IBM Cloud token API very often (> 3000 times per minute) to obtain an access token always for the same account (account id: 1659c5678e1e5e5cadefa0fb2c2ca5e1).
>  
> Please note that tokens are valid for 1 hour and must be cached and reused. Please adjust your service to reuse the token that you obtained.
> Otherwise we need to block your requests in order to protect IBM Cloud from the flood of unnecessary requests. Please respond to this message ASAP confirming that you are making updates to your service. Due to the high number of API calls, we will begin blocking calls in 24 hours.

**Expected behavior**
IamAuthenticator should handle token expiration and renovation, as in the [documentation](https://github.com/IBM/node-sdk-core/blob/master/AUTHENTICATION.md#identity-and-access-management-authentication-iam)

**Actual behavior**
IamAuthenticator is fetching a new token on every request

**How to reproduce**
We followed this [example](https://github.com/watson-developer-cloud/node-sdk#assistant-v1)
Here is a code snippet of what we're doing:
```js
'use strict';

var AssistantV1 = require('ibm-watson/assistant/v1');
const { IamAuthenticator } = require('ibm-watson/auth');

const watson = {
    call_assistant: function (params) {
        return new Promise((resolve, reject) => {
            let context = params.context;
            let msg = params.msg;
            let alternate_intents = params.alternate_intents || false;
            let config = params.config;

            let watson_assistant = new AssistantV1({
                authenticator: new IamAuthenticator({ apikey: config.apikey }),
                serviceUrl: config.url,
                version: '2019-02-28'
            });

            watson_assistant.message(
                {
                    input: { text: msg },
                    workspaceId: config.workspace_id,
                    context: context,
                    alternateIntents: alternate_intents
                }
            ).then(resolve).catch(reject);
        });
    }
}

module.exports = watson;
```

**SDK Version**
_5.1.0_

**Additional information:**
- OS: _Ubuntu 16.04.4 LTS_
- Node: _v10.16.3_

**Additional context**
We have many different instances with 20 workspaces each using this module to make calls to Watson Assistant.

**Comment by mkistler** [comment]
The problem is that you are constructing a new `IAMAuthenticator` and `watson_assistant` object for every call to `message`.  You should construct these once and then just reuse them for subsequent calls to `message`.

**Comment by mkistler** [comment]
Received word that the issue was resolved using the approach above.
