### ISSUE TITLE
Speech-to-text Streaming mode in jobs

### ISSUE THREAD

**Issue by akjoshi6** [watson-developer-cloud/node-sdk#1046]
I am able to get transcription for continuously growing audio files using below example [Synchronous]:
https://github.com/watson-developer-cloud/node-sdk/blob/master/examples/speech_to_text.v1.js

I now want to stream multiple growing audio files by creating jobs [Asynchronous]. I am using [this](https://www.npmjs.com/package/@uppy/fs-tail-stream) package to obtain a createReadStream object to continuously get transcript of a growing audio file. This works fine using synchronous approach.

But when I do the same thing by creating jobs I face following error:

```
error: Service Unavailable: Service Unavailable
    at RequestWrapper.formatError (/home/user/STT/ibm-node/node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js:216:21)
    at /home/user/STT/ibm-node/node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js:204:25
    at processTicksAndRejections (internal/process/task_queues.js:94:5) {
  statusText: 'Service Unavailable',
  name: 'Service Unavailable',
  status: 503,
  code: 503,
  message: 'Service Unavailable',
  body: '"<HTML><HEAD>\\n<TITLE>Internal Server Error</TITLE>\\n</HEAD><BODY>\\n<H1>Internal Server Error - Write</H1>\\nThe server encountered an internal error or misconfiguration and was unable to\\ncomplete your request.<P>\\nReference&#32;&#35;4&#46;be0a2c17&#46;1591344998&#46;43e5dace\\n</BODY></HTML>\\n"',
  headers: {
    server: 'AkamaiGHost',
    'mime-version': '1.0',
    'content-type': 'text/html',
    'content-length': '285',
    expires: 'Fri, 05 Jun 2020 08:16:38 GMT',
    date: 'Fri, 05 Jun 2020 08:16:38 GMT',
    connection: 'close'
  }
}
```

Streaming mode is mentioned in [docs](https://cloud.ibm.com/apidocs/speech-to-text?code=node#create-a-job) for creating jobs.

**Comment by dpopp07** [comment]
As it's a 500-level "Internal Server Error" so I don't think there's anything that can be fixed in the SDKs, it is likely a bug in the API. @mamoonraja who would be the best person to look at this on the service-side?

**Comment by mamoonraja** [comment]
I will reach out to @daniel-bolanos and see what we can do about it.

**Comment by mamoonraja** [comment]
@akjoshi6 can you still reproduce the issue? Service team will look into it if it's still an issue.

**Comment by akjoshi6** [comment]
No, not able to reproduce
