### ISSUE TITLE
Electron error with test/utils

### ISSUE THREAD

**Issue by EdmarPereira** [watson-developer-cloud/node-sdk#1047]
Hello I am working on an application developed in electron, where the frontend is made in ReactJs and backend in NodeJs. I installed the “ibm-watson” package to use the Watson Assistant module, however when I generate the electron build for production, an exception error appears saying:

"A Javascript error occurred in the main process.
Uncaught Exception:
Error: Cannot find a module './test/utils'

I did an investigation and realized that the “ibm-watson” module has a dependency on another module called “ibm-cloud-sdk-core” and that module in the index.js file has an “__export (require (" ./ test / utils ”));” If I comment on this line, the application works as expected, and my question is whether it really is necessary to keep this require as it is a test package.

**Comment by dpopp07** [comment]
@EdmarPereira Thanks for bringing this up. We've not seen this show up as a problem before but you're right, it shouldn't be required in the exported application.

We'll need to fix this

**Comment by EdmarPereira** [comment]
Hey, any update on this, this will be on next release? 
Every time we delete our node_modules we need to search for this line in the package and comment it. 
Thanks a lot

**Comment by dpopp07** [comment]
Hi @EdmarPereira no update yet, but I will look at it this week

**Comment by dpopp07** [comment]
@EdmarPereira The issue in the core is being addressed ([PR here](https://github.com/IBM/node-sdk-core/pull/101)). Once the new version of the core is out, I will update this package and the problem should be resolved
