### ISSUE TITLE
Speech-To-Text: Memory leakage while using recognizeStream 

### ISSUE THREAD

**Issue by akjoshi6** [watson-developer-cloud/node-sdk#1048]
I am dealing with continuously increasing .aac files, creating a stream using createReadStream and passing it to recognizeStream using pipe which looks like below:

`var recognizeStream = speechToText.recognizeUsingWebSocket(_this.params);`
 `var transcriber = fst.createReadStream(filePath,_this.options).pipe(recognizeStream).on('sync',function(){
                    recognizeStream.close();
                })`

It creates memory overhead if IBM websocket is abruptly closed, works fine otherwise. Have we handled backpressure ?

![image](https://user-images.githubusercontent.com/31006589/87029171-61356f80-c1fd-11ea-9f63-fd802db43046.png)
Here is the heap dump. It is accumulating once there is an issue with the socket. You can see difference between heapdump sizes of before and after socket issue. I am also destroying stream at error and close socket events, but no luck.

**Comment by apaparazzi0329** [comment]
Hi @akjoshi6 thank you for bringing up this issue. Would you be able to tell me what version of the node sdk you were using when you found this issue. Also, if this is no longer an issue would you be able to share the solution you found. Thanks again

**Comment by akjoshi6** [comment]
Node version was 5.6.0 I handled this by deleting/renaming respective audio file on close socket event. Let me know if there's any better approach to handle this

**Comment by apaparazzi0329** [comment]
Awesome thanks for the info. I will let you know if I discover anything better
