### ISSUE TITLE
Creating Assistant with `ibm-credentials.env` requires additional `serviceName: 'assistant'` to work

### ISSUE THREAD

**Issue by dtom90** [watson-developer-cloud/node-sdk#1064]
**Overview**
When creating a `new AssistantV1(...)` using [credentials file](https://github.com/watson-developer-cloud/node-sdk#credentials-file-easier) an additional config `serviceName: 'assistant'` must be passed into the constructor options to override the default `serviceName: 'conversation'`: 
```js
const assistant = new AssistantV1({
  serviceName: 'assistant', // THIS IS REQUIRED TO WORK
  version: '2020-04-01'
});
```
This is not documented in the README and can cause a bit of confusion

**Expected behavior**
I would expect an assistant client to be able to be created with minimal configuration:
```js
const assistant = new AssistantV1({
  version: '2020-04-01'
});
```

**Actual behavior**
`Error: Missing required parameters: apikey`

**How to reproduce**
- Clone https://github.com/dtom90/ibm-watson-test
- Download `ibm-credentials.env`, add to the project root
- Set `workspaceId` in [`index.js`](https://github.com/dtom90/ibm-watson-test/blob/0779efa914ff388874437d02daf4316f2e66160e/index.js#L9)
- Run `node index.js`
- Uncomment [`serviceName: 'assistant'`](https://github.com/dtom90/ibm-watson-test/blob/0779efa914ff388874437d02daf4316f2e66160e/index.js#L4)
- Run `node index.js` again

**SDK Version**
`5.7.1`

**Additional information:**
- OS: macOs
- Which version of `Node` are you using? `14.13.0`

**Comment by dpopp07** [comment]
@dtom90 Thanks for the issue. We are aware of this problem. Unfortunately, there are legacy issues preventing us from changing the default service name to 'assistant`, which would be the desired solution. I need to determine if this is something we can fix in the upcoming major release.

In the meantime, I suppose the best we can do is document this explicitly in the README.
