### ISSUE TITLE
[speech-to-text] Change to a custom grammar gives: "Header JSON already received. Now expected a sequence of blobs or an 'unready' event, but got 'listen' event in state 'listening'"

### ISSUE THREAD

**Issue by MattRiddell** [watson-developer-cloud/node-sdk#1065]
**Overview**

I have started a streaming WebSocket connection and piped in the audio from a telephone call.

I run:

```Javascript
            const message = {
                action:       'start',
                contentType:  'audio/l16; rate=8000',
                grammar_name: '3 letters',
            };
            this.recognizeStream.sendJSON(message);
```

By the way all the [IBM js examples for websockets](https://cloud.ibm.com/docs/speech-to-text?topic=speech-to-text-websockets) say to use content-type without speech marks which obviously wouldn't work

**Expected behavior**
I expect the grammar to change to the 3 letters grammar and only detect things in the custom grammar for the time being.

The call was started with the correct language customization.

**Actual behavior**
I receive the following error:

`Error: Header JSON already received. Now expected a sequence of blobs or an 'unready' event, but got 'listen' event in state 'listening'.`

**How to reproduce**

Connect to Watson using:

```Javascript
       this.speechToText  = new SpeechToTextV1(
            {
                authenticator: new IamAuthenticator(
                    {
                        apikey: process.env.BLUEMIX_API_KEY,
                    }
                ),
                serviceUrl:    process.env.BLUEMIX_SERVICE_URL,
            });

        this.params = {
            objectMode:              true,
            contentType:             'audio/l16; rate=8000; channels=1',
            model:                        model,
            interimResults:          true,
            languageCustomizationId: 'xxxxxxxxxxxxx',
        };

        this.u.echo("Connecting to IBM");
        this.recognizeStream = this.speechToText.recognizeUsingWebSocket(this.params);
```

Where model is:

```Javascript
en-US_ShortForm_NarrowbandModel
```

I've even tried dropping the grammar_name but to no avail.

The audio is received (from Asterisk EAGI) on file descriptor 3 and is piped in with:

```Javascript
this.audioStream.pipe(this.recognizeStream);
```

Everything works fine with the exception that I can't change the grammar.

I also tried simplifying the message as:

```Javascript
const message = {
    "interim_results": false,
    action:       'start',
};
```

I added debug to check the query string was in fact providing the language_customization_id correctly and checked the initial start messages being sent by the library.

The feature I'm trying to use is [referenced as follows](https://cloud.ibm.com/docs/speech-to-text?topic=speech-to-text-websockets#WSmore):

> **Send additional requests and modify request parameters**
> 
> While the WebSocket connection remains active, the client can continue to use the connection to send further recognition  requests with new audio. By default, the service continues to use the parameters that were sent with the previous start message for all subsequent requests that are sent over the same connection.
> 
> To change the parameters for subsequent requests, the client can send another start message with the new parameters after it receives the final recognition results and {"state":"listening"} message from the service. The client can change any parameters except for those parameters that are specified when the connection is opened (model, language_customization_id, and so on).

```Javascript
var message = {
  action: 'start',
  content-type: 'audio/l16;rate=22050',
  word_confidence: true,
  timestamps: true
};
websocket.send(JSON.stringify(message));
```

**SDK Version**
Latest

**Additional information:**
Linux, Node 14

**Comment by MattRiddell** [comment]
The examples with content-type are at:

[https://cloud.ibm.com/docs/speech-to-text?topic=speech-to-text-websockets](https://cloud.ibm.com/docs/speech-to-text?topic=speech-to-text-websockets)

**Comment by dpopp07** [comment]
@MattRiddell Thanks for the issue and for all of the detail. I will attempt to reproduce the issue soon.

We'll get those examples updated ASAP as well 👍

**Comment by MattRiddell** [comment]
Cool man, let me know if there's anything I can do to help - in the meantime I'm shutting the stream down and starting it back up with another grammar.

**Comment by MattRiddell** [comment]
Hiya, anything I can do to help/get the hacks out of my code? Have premium IBM support SLA/contract. Is this the right place or there?

**Comment by dpopp07** [comment]
@MattRiddell Apologies, things got piled on top of this. I will take a look at it today

**Comment by dpopp07** [comment]
@MattRiddell I am able to reproduce your issue and I think I know what is wrong although, unfortunately, I'm not yet sure what to do about it.

The key sentence in the docs that you included with your issue is
> To change the parameters for subsequent requests, the client can send another start message with the new parameters after it receives the final recognition results and {"state":"listening"} message from the service

Specifically, `after it receives the final recognition results and {"state":"listening"} message from the service`.

The issue is that you are sending the new message before the final recognition results are sent back and the service is "listening" again. By waiting for this to happen in my own code, I've been able to send the new message to the service without the error message you've posted above.

That said, the issue at hand now is that the SDK seems to automatically close the connection once the final results are received. So even though I can send the new message with the new parameters to the service without error, the connection closes immediately afterward. [This documentation](https://cloud.ibm.com/docs/speech-to-text?topic=speech-to-text-websockets#WSstop) describes what I am trying to do (send the stop message, then send a new message) but I have been unable to do this in the SDK.

I've tried altering the SDK code to prevent the closure but without luck. Unfortunately, this is going to require more time looking at how we can modify the SDK to fit this use case, if possible to do so.

**Comment by MattRiddell** [comment]
I don't think in my tests the connection got closed because I continue to receive results.

I'll dig into the code a bit more from my end and see if I can come up with something.  If it really does get closed we could store the request and send it on the new start rather than as a new message.

Will dig in from my end when I get a chance and post back.

**Comment by dpopp07** [comment]
Still needs fixing
