### ISSUE TITLE
No luck with Speech-to-text: HTTP Authentication failed; no valid credentials available

### ISSUE THREAD

**Issue by rzfzr** [watson-developer-cloud/node-sdk#1083]
**Overview**
I tried replicating both examples, the one in the main readme and the one in the examples folder (they are slightly different), however it fails to connect.

**Screenshots**
![image](https://user-images.githubusercontent.com/13456224/107300414-3d1e6300-6a58-11eb-94d6-0d3c9cb46f90.png)

**SDK Version**
"ibm-watson": "^6.0.0",

**Additional information:**
Windows 10
Node v14.15.3

**Comment by apaparazzi0329** [comment]
Hi rzfzr thank you for filing this issue. Would you be able to provide a code snippet of what you are running minus any api keys you may be using. Also as a first guess make sure to check that you inputted the correct credentials.

**Comment by rzfzr** [comment]
Hello there, sure, here's the relevant code

```
const SpeechToTextV1 = require("ibm-watson/speech-to-text/v1");
const { IamAuthenticator } = require("ibm-watson/auth");
const speechToText = new SpeechToTextV1({
  authenticator: new IamAuthenticator({
    apikey: "05cNCQpEuMK3lm2PmCxudXOZpfYaqcFKnHvFRGm1LDOu",
  }),
  serviceUrl:
    "https://api.us-south.speech-to-text.watson.cloud.ibm.com/instances/70d6cb2e-92ed-4d7a-a295-b8adfa834b11",
  disableSslVerification: true,
});

```
[...]

  ```
const params = {
          contentType: "audio/wav",
          objectMode: true,
        };

        const recognizeStream = speechToText.recognizeUsingWebSocket(params);

        fs.createReadStream(tempDir + "speech.wav").pipe(recognizeStream);

        recognizeStream.on("data", function (event) {
          onEvent("Data:", event);
        });
        recognizeStream.on("error", function (event) {
          onEvent("Error:", event);
        });
        recognizeStream.on("close", function (event) {
          onEvent("Close:", event);
        });
      }
```

**Comment by rzfzr** [comment]
But from what I have been seing this isso might has something to do with the fact that I am trying to use it through electron, it's still node, I thought it should work

**Comment by rzfzr** [comment]
@apaparazzi0329 thanks for the edit, I can't believe it  I forgot... :/, I'm generating new keys

**Comment by apaparazzi0329** [comment]
No worries ;)

**Comment by apaparazzi0329** [comment]
Can you do me a favor? After creating the SpeechToTextV1 instance can you `console.log` its contents. I'm specifically interested in seeing its `serviceUrl` property

**Comment by rzfzr** [comment]
Sure thing, thanks for the help, I thought this url was as sensitive as the apikey

  ```
baseOptions: {
    qs: {},
    serviceUrl:
      "https://api.us-south.speech-to-text.watson.cloud.ibm.com/instances/aafdd8ff-2a4e-44ac-8a2a-7b0ff69acb69",
    authenticator: {
      disableSslVerification: false,
      headers: {},
      tokenManager: {
        disableSslVerification: false,
        headers: {},
        requestWrapperInstance: { compressRequestData: false },
        pendingRequests: [],
        tokenName: "access_token",
        tokenInfo: {},
        requiredOptions: ["apikey"],
        apikey: "ohtheshame",
        url: "https://iam.cloud.ibm.com/identity/token",
      },
      requiredOptions: ["apikey"],
      apikey: "ohtheshame",
    },
    disableSslVerification: true,
    serviceName: "speech_to_text",
  },
  requestWrapperInstance: { compressRequestData: false },
  authenticator: {
    disableSslVerification: false,
    headers: {},
    tokenManager: {
      disableSslVerification: false,
      headers: {},
      requestWrapperInstance: { compressRequestData: false },
      pendingRequests: [],
      tokenName: "access_token",
      tokenInfo: {},
      requiredOptions: ["apikey"],
      apikey: "ohtheshame",
      url: "https://iam.cloud.ibm.com/identity/token",
    },
    requiredOptions: ["apikey"],
    apikey: "ohtheshame",
  },
```

**Comment by apaparazzi0329** [comment]
Its not as sensitive since you can't actually make calls to the service without the apikey, in fact your instance is often inferred from the apikey so sometimes you don't even need the url. The only thing that strikes me as odd is that your url is `api.us-south.speech-to-text.watson.cloud.ibm.com` which is located in the US yet your websocket call is trying to hit a server in london. Are you behind some sort of vpn perhaps?

**Comment by rzfzr** [comment]
Got it,
not behind a vpn of any kind, I am situated in Brazil tho, internet-wise that seems to be always closer to north america than to europe server....  The Dallas server was the first to come up when selecting so I thought it was the closest, I could try the UK one if one exists

**Comment by rzfzr** [comment]
Well it's settled, electron is messing things up, I dropped the exact same code into a js test file and executed it with just node and it worked perfectly....
I already enabled node integration to get other things to work, like extraResources, fs, ffmpeg..., my vue.config.js looks like this:


```
const webpack = require('webpack');

module.exports = {
    pluginOptions: {
        electronBuilder: {
            nodeIntegration: true,
            builderOptions: {
                extraResources: ['src/extraResources']
            }
        }
    },
    configureWebpack: {
        plugins: [
            new webpack.DefinePlugin({
                'process.env.FLUENTFFMPEG_COV': false
            })
        ]
    }
}

```

**Comment by apaparazzi0329** [comment]
In that case my knowledge to help fix an issue with Electron would be quite limited. I am curious though could you try calling different endpoints and sending the same error message you sent in the beginning. I want to see if you will always hit the old london endpoint. Simply replace `api.us-south` in your `serviceUrl` with each of these endpoints
`api.us-east`
`api.eu-gb`

**Comment by rzfzr** [comment]
with gb:
 ```
baseOptions: {
    qs: {},
    serviceUrl:
      "https://api.eu-gb.speech-to-text.watson.cloud.ibm.com/instances/aafdd8ff-2a4e-44ac-8a2a-7b0ff69acb69",
    authenticator: {
      disableSslVerification: false,
      headers: {},
      tokenManager: {
        disableSslVerification: false,
        headers: {},
        requestWrapperInstance: { compressRequestData: false },
        pendingRequests: [],
        tokenName: "access_token",
        tokenInfo: {},
        requiredOptions: ["apikey"],
        apikey: "a",
        url: "https://iam.cloud.ibm.com/identity/token",
      },
      requiredOptions: ["apikey"],
      apikey: "a",
    },
    disableSslVerification: true,
    serviceName: "speech_to_text",
  },
  requestWrapperInstance: { compressRequestData: false },
  authenticator: {
    disableSslVerification: false,
    headers: {},
    tokenManager: {
      disableSslVerification: false,
      headers: {},
      requestWrapperInstance: { compressRequestData: false },
      pendingRequests: [],
      tokenName: "access_token",
      tokenInfo: {},
      requiredOptions: ["apikey"],
      apikey: "a",
      url: "https://iam.cloud.ibm.com/identity/token",
    },
    requiredOptions: ["apikey"],
    apikey: "a",
  },
```

and east:

```
baseOptions: {
    qs: {},
    serviceUrl:
      "https://api.us-east.speech-to-text.watson.cloud.ibm.com/instances/aafdd8ff-2a4e-44ac-8a2a-7b0ff69acb69",
    authenticator: {
      disableSslVerification: false,
      headers: {},
      tokenManager: {
        disableSslVerification: false,
        headers: {},
        requestWrapperInstance: { compressRequestData: false },
        pendingRequests: [],
        tokenName: "access_token",
        tokenInfo: {},
        requiredOptions: ["apikey"],
        apikey: "a",
        url: "https://iam.cloud.ibm.com/identity/token",
      },
      requiredOptions: ["apikey"],
      apikey: "a",
    },
    disableSslVerification: true,
    serviceName: "speech_to_text",
  },
  requestWrapperInstance: { compressRequestData: false },
  authenticator: {
    disableSslVerification: false,
    headers: {},
    tokenManager: {
      disableSslVerification: false,
      headers: {},
      requestWrapperInstance: { compressRequestData: false },
      pendingRequests: [],
      tokenName: "access_token",
      tokenInfo: {},
      requiredOptions: ["apikey"],
      apikey: "a",
      url: "https://iam.cloud.ibm.com/identity/token",
    },
    requiredOptions: ["apikey"],
    apikey: "a",
  },
```

**Comment by rzfzr** [comment]
I am positive it is something with it not liking not being vanilla node, watson was my first attempt as I used another AI resource for natural language in a similar faction, but after a day with no progress I tried to implement googles speech to text with very similar results, in that case I found [this](https://www.npmjs.com/package/electron-speech) which seems that they are actively stopping it.... (I tried implementing their own api for node, before finding this package and everything making sense....)
In my other project, where I user the natural language res from watson it was inside a .js being exported as a module, I copied the same syntax, made no difference....
I just opened [this](https://github.com/electron/electron/issues/27690)

**Comment by apaparazzi0329** [comment]
This issue is outside this repository's scope. Closing as wontfix. If more issues come in involving Electron we may look into increased instructions or compatibility.
