### ISSUE TITLE
Receiving stream and passing it to SpeechToText service

### ISSUE THREAD

**Issue by sw-dev-code** [watson-developer-cloud/node-sdk#1088]
I would like to use the audio stream which is received over the Websocket as input to the SpeechToText service instead of input from the microphone.

Is that possible and is there any example of how to do that?

Thank you in advance.

**Comment by apaparazzi0329** [comment]
The issues board is only used for reporting bugs and/or feature enhancements. For assistance in developing with Watson I would ask your questions in the Watson Developer Community Slack channel. Here is the invite link. https://wdc-slack-inviter.mybluemix.net/. Closing as non issue
