### ISSUE TITLE
Response includes period character

### ISSUE THREAD

**Issue by fgoyti** [watson-developer-cloud/node-sdk#1089]
**Overview**
Response includes a period at the end, only in the Node SDK.  If I use curl or the Try button in the Dialog UI, there is no period (as expected).  For example,
response.result.output.generic[0].text returns "What API would you like to learn about?."  In my Dialog, there is no period after the question mark.

**Expected behavior**
No period after the question mark. 

**Actual behavior**
The SDK seems to append a period for every response.

**How to reproduce**
`
    assistant.message(
        {
            assistantId: myAssistantId,
            sessionId: session,
            input: { 
                text: transcribedText }
        })
        .then(response => {
            console.log (response.result.output.generic[0].text);
    });
`

**Screenshots**
N/A

**SDK Version**
    "ibm-watson": {
      "version": "6.0.3",
      "resolved": "https://registry.npmjs.org/ibm-watson/-/ibm-watson-6.0.3.tgz",

**Additional information:**
- OS: Windows
- Node v14.16.0

**Comment by apaparazzi0329** [comment]
Thank you for posting this issue I shall look into it shortly

**Comment by fgoyti** [comment]
Please disregard.  This is not a bug.  Error in my code.
