### ISSUE TITLE
React & Webpack webapp fails to load ibm-watson in browser

### ISSUE THREAD

**Issue by psulkava** [watson-developer-cloud/node-sdk#1090]
**Overview**
I'm attempting to use DiscoveryV2. within an existing React application that is using Webpack 4 for bundling and webpack-dev-server for running locally. Whenever I attempt to run the application locally it fails to load with the following error.

```
polyfills.js?a0a3:139 Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at Function.setPrototypeOf (<anonymous>)
    at eval (polyfills.js?a0a3:139)
    at patch (polyfills.js?a0a3:141)
    at patch (graceful-fs.js?0da7:104)
    at Object.eval (graceful-fs.js?0da7:96)
    at eval (graceful-fs.js?0da7:373)
    at Object.DadK (vendor.js:4032)
    at __webpack_require__ (insights:873)
    at fn (insights:170)
    at Object.eval (index.js?a3f7:14)
```

The error seems to be coming from the vendor.js file which is the npm package bundled code and specifically from the ibm-watson package. If I run the webpack example application in this repo it works fine so its somehow being caused by my specific react/webpack configuration.

**Expected behavior**
Web application loads successfully.

**Actual behavior**
Application doesn't load and just shows white screen in browser with above error in console.

**How to reproduce**
I can provide my code if needed.

**SDK Version**
ibm-watson: 6.0.3

**Comment by repjarms** [comment]
@psulkava thanks for filing this! We can look into it and see if we can reproduce it. Out of curiosity - could you check and let us know what version of the `ibm-cloud-sdk-core` package you have installed in the app as well?

@apaparazzi0329 @dpopp07 since you both know more than I do about the node sdk.

**Comment by psulkava** [comment]
@repjarms The version of `ibm-cloud-sdk-core` is "2.10.1" which is being included by the ibm-watson package.

**Comment by dpopp07** [comment]
@psulkava We identified the issue in the core package and I just opened a PR to fix [here](https://github.com/IBM/node-sdk-core/pull/132). Once the core patch merges and releases, we'll release a patch version of the Watson Node SDK. Hopefully this will all happen pretty quickly. Version `6.0.4` of this SDK will contain the fix

**Comment by dpopp07** [comment]
Version `6.0.4` has been released - let us know if the issue persists
