### ISSUE TITLE
Support Speech to Text over websockets

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/node-sdk#110]
This is a cleaner, simpler interface and will also help with timeout issues (including possibly fixing #68)

**Comment by germanattanasio** [comment]
I think I will first try with https://github.com/Worlize/WebSocket-Node.

```javascript
/**
 * Wrapper for Worlize WebSocketNode to emulate the browser WebSocket object.
 */
var WebSocketClient = require('./WorlizeWebSocketNode/lib/websocket').client;

exports.WebSocket = function (uri) {
  var self = this;
  this.connection = null;
  this.socket = new WebSocketClient();
  this.socket.on('connect', function (connection) {
    self.connection = connection;

    connection.on('error', function (error) {
      self.onerror();
    });

    connection.on('close', function () {
      self.onclose();
    });

    connection.on('message', function (message) {
      if (message.type === 'utf8') {
        self.onmessage({data:message.utf8Data});
      }
    });

    self.onopen();
  });
  this.socket.connect(uri);
}

exports.WebSocket.prototype.send = function (data) {
  this.connection.sendUTF(data);
}
```

### More info:
 1. http://stackoverflow.com/questions/3842565/is-there-a-browserless-websocket-client-for-node-js-that-does-not-need-to-use-a
 1. http://stackoverflow.com/questions/16392260/which-websocket-library-to-use-with-node-js

**Comment by nfriedly** [comment]
I put in [a warning message](https://github.com/watson-developer-cloud/node-sdk/blob/v1.0/services/speech_to_text/v1.js#L529) that the older `recognizeLive` and friends are deprecated. But like I said on #89, we might just want to nix them from the WDC v1.0 release.

Right now, though, I'm thinking that we should match what the service provides and maybe the STT service should release a v2 API w/out `recognizeLive` (and patch up anything else that we want).

**Comment by daniel-bolanos** [comment]
I agree @nfriedly , we should be releasing a v2 next year... hopefully following the lessons learned

**Comment by germanattanasio** [comment]
Fixed bt @nfriedly
