### ISSUE TITLE
Add support for CSV in personality insights

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/node-sdk#114]
We need to add support to get a profile as csv

Probably something like:

```js
service.profile({csv: true, text: ''}, callback);
service.profile({csv: true, contentItems: [...]}).pipe(fs.createWriteStream('./profile.csv'));
```

**Comment by nfriedly** [comment]
Done w/ tests and an example. I also cleaned up the integration tests a bit and then published it as `v1.0.0-beta.2`
