### ISSUE TITLE
AlchemyVision getImageLinks should support html input

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/node-sdk#129]
The service supports retrieving image links from a url or html in the request, but the SDK requires a url (and erroneously supports in image input). Note that the AlchemyAPI documentation and https://github.com/watson-developer-cloud/node-sdk/blob/master/lib/alchemy_endpoints.json seems to be incorrect here -- the endpoint seems to be `/html/HTMLGetImage`, not `/url/HTMLGetImage`

**Comment by nfriedly** [comment]
BTW, I just reported this and one other related bug (result sometimes has a mangled url for the image) to alchemyAPI
