### ISSUE TITLE
List the required dependencies along with their licenses

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/node-sdk#131]
| Dependency        | License           | url  |
| ------------- | ------------- | ----- |
|async | MIT | https://github.com/caolan/async|
|cookie | MIT | https://github.com/jshttp/cookie|
|csv-stringify | BSD-3-Clause | http://www.github.com/wdavidw/node-csv-stringify|
|extend | MIT | https://github.com/justmoon/node-extend|
|isstream | MIT | https://github.com/rvagg/isstream|
|object.omit | MIT | https://github.com/jonschlinkert/object.omit|
|object.pick | MIT | https://github.com/jonschlinkert/object.pick|
|request | Apache-2.0 | https://github.com/request/request|
|solr-client | MIT | https://github.com/lbdremy/solr-node-client|
|string | MIT | https://github.com/jprichardson/string.js|
|vcap_services | MIT | https://github.com/germanattanasio/vcap_services|
|websocket | Apache-2.0 | https://github.com/theturtle32/WebSocket-Node|

**Comment by nfriedly** [comment]
done (see parent comment). It looks like we're all good except for solr client...

**Comment by nfriedly** [comment]
Never mind, it's MIT: https://github.com/lbdremy/solr-node-client/blob/master/LICENCE
