### ISSUE TITLE
Running into error running watson example speech to text

### ISSUE THREAD

**Issue by YonasBerhe** [watson-developer-cloud/node-sdk#140]
Hello,

I'm having trouble running an example application. The the example application is called speech_to_text.v1.js. I'm following this [doc](
https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/getting_started/gs-quick-nodejs.shtml 
)

I have my credentials for Speech To Text service on Bluemix plugged in. Each time I try running my application using node I keep this error: 

```
var recognizeStream = speech_to_text.createRecognizeStream(params);
                                     ^

TypeError: speech_to_text.createRecognizeStream is not a function
    at Object.<anonymous> (/Users/sanoy/Code/learning/node-sdk/examples/speech_to_text.v1.js:18:38)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

Could this error be caused by **"Breaking Changes for v1.0"**?

**Comment by germanattanasio** [comment]
@YonasBerhe you are trying to run an example that belong to the v1.0 which is still in beta. You can install the beta version by doing:
```bash
npm install watson-developer-cloud@1.0.0-beta.2
```

**Comment by YonasBerhe** [comment]
That was it, Thank you.
