### ISSUE TITLE
Skip integration tests in merge requests

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/node-sdk#154]
All of the CI tests for #153 failed with `The command "openssl aes-256-cbc -K $encrypted_d4f181ef7c79_key -iv $encrypted_d4f181ef7c79_iv -in auth.js.enc -out test/resources/auth.js -d" failed and exited with 1 during .`: https://travis-ci.org/watson-developer-cloud/node-sdk/builds/91876275 - can travis not decrypt it in merge requests? In that case, we should figure out how to make it skip the integration tests but still run the lint & unit tests.

**Comment by germanattanasio** [comment]
I think this was fixed today. Is that right @nfriedly ?

**Comment by nfriedly** [comment]
Yes, sorry, forgot about this ticket. Closed via #171
