### ISSUE TITLE
Investigate a way to generate the documentation from the source code

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/node-sdk#161]
We want to generate the static documentation from each commit and each tag starting from v1.0.3

Some links to start the discusion:
 * http://stackoverflow.com/questions/5841490/generating-javascript-documentation
 * http://jashkenas.github.io/docco/
 * http://usejsdoc.org/

**Comment by nfriedly** [comment]
Done with http://usejsdoc.org/

Note: the generated documentation is currently somewhat lacking because many of the methods have minimal or even no comments. This will take a lot longer to improve.
