### ISSUE TITLE
missing example folder when installing via npm

### ISSUE THREAD

**Issue by zenified** [watson-developer-cloud/node-sdk#168]
After running the install command for watson-developer-cloud as specified in the instruction there,https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/getting_started/gs-quick-nodejs.shtml, the folder recreated is missing the example folder

**Comment by germanattanasio** [comment]
I think you are looking at an old page. The getting started nodejs page is: https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/getting_started/gs-quick-nodejs.shtml

**Comment by nfriedly** [comment]
Actually, the instructions there are wrong.. I think the author didn't realize that we don't publish everything in the github repo to npm. We've sent a note to the docs team. 

In the meanwhile, the examples/ folder it's referring to is available at https://github.com/watson-developer-cloud/node-sdk/tree/master/examples

**Comment by germanattanasio** [comment]
The documentation was updated so I think we can close this.
![screen shot 2015-12-21 at 7 15 30 pm](https://cloud.githubusercontent.com/assets/313157/11942715/3d7fe5e8-a817-11e5-9ff1-6b69a4ab3767.png)
