### ISSUE TITLE
question and answer service withdrawn?

### ISSUE THREAD

**Issue by mg1075** [watson-developer-cloud/node-sdk#185]
According to IBM, the Q & A service is being withdrawn.
https://developer.ibm.com/watson/blog/2015/11/11/watson-question-and-answer-service-to-be-withdrawn/

Does that mean the Q & A service needs to be updated?
https://github.com/watson-developer-cloud/node-sdk/blob/master/services/question_and_answer/v1-beta.js

**Comment by germanattanasio** [comment]
If you try to use it you will get a WARNING. The service will be removed soon

**Comment by mg1075** [comment]
@germanattanasio - OK.
And because node-sdk has services for the suggested replacements (Natural Language Classifier, Dialog, Retrieve and Rank, Document Conversion), node-sdk is already prepared for the withdrawal.
