### ISSUE TITLE
[speech-to-text] calling multiple times to recognize using WebSockets should create individual sessions

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/node-sdk#187]
Looking at https://developer.ibm.com/answers/questions/244090/multiple-speech-to-text-consecutive-queries.html

I think the problem is that we call `v1/recognize` multiple times. We should create and use a session when calling recognize. That session will be using WebSockets.

@daniel-bolanos what do you think ?

**Comment by germanattanasio** [comment]
@nfriedly whenever you have a change

**Comment by nfriedly** [comment]
I don't think we should create a session unless the user explicitly requests one. I left some comments on the original question, but I haven't been able to reproduce the bug using his code and node.js version (v0.10.29 - which is technically no longer supported, but still worked as correctly for me)

**Comment by daniel-bolanos** [comment]
@germanattanasio @nfriedly , what do you mean with sessions? If you mean an STT session, please lets stay away from that... On WebSockets you create the connection calling wss://.../recognize and then every time the user can push multiple files, or chunks of audio over that same connection by sending binary messages. Do you need functionality different than that?

thank you

**Comment by nfriedly** [comment]
Yea, I don't think that we need stt sessions with websockets, and given that German closed the issue already, I think he agrees.

**Comment by daniel-bolanos** [comment]
good :)
