### ISSUE TITLE
Retrieve and Rank FCSELECT 

### ISSUE THREAD

**Issue by ollycox** [watson-developer-cloud/node-sdk#208]
The API documentation for Retrieve and Rank (https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/retrieve-and-rank/api/v1/#query_ranker) makes reference to the fcselect endpoint for searching and ranking results.

Can anyone tell me where this is in the node-sdk? or if an alternative function is providing the same functionality?

**Comment by nfriedly** [comment]
Hi @ollycox,

`fcselect` may be passed in as the first option to `retrieve_and_rank.createSolarClient(/*...*/).get()`. https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/retrieve-and-rank/api/v1/?node#query_ranker has a complete example in the right column.

**Comment by ollycox** [comment]
Nathan,

Confirmed and working as expected. Thank you

Oliver
