### ISSUE TITLE
Unsupported API version when using 'Tone analyzer'

### ISSUE THREAD

**Issue by iamgroot42** [watson-developer-cloud/node-sdk#209]
```
var tone_analyzer = watson.tone_analyzer({
  url: 'https://gateway.watsonplatform.net/tone-analyzer-beta/api/',
  isStreaming: false,
  username: 'XXX',
  password: 'YYY',
  // version_date: '2016-11-02',
  version: 'v2-experimental'
});

```

**Comment by nfriedly** [comment]
Hi Groot, 

It looks like there's a mismatch between your beta URL and experimental API version. Try either commenting out the url field, or switching the version to `'v3-beta'` and let me know if either of those work for you.

**Comment by iamgroot42** [comment]
The error's gone now.

I hadn't updated the package for <i>watson</i> and was using this.However, this has been outdated and using `v3` requires the new package. Upgrading did it (using `v3-beta`)

Thanks

**Comment by nfriedly** [comment]
Awesome!

Thanks,
-Nathan
