### ISSUE TITLE
Remove question and answer (?)

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/node-sdk#215]
I believe the Question and Answer service has been sunset, but I can't seem to find many specifics.

I think we should at least remove it from the readme, since it's no longer possible to create new instances, but I'm not sure if existing instances can still be used. That should determine whether or not we should remove the actual code from the library.

(Note: I also just updated the readme to indicate that the Concept Expansion service is sunset. We should plan on [removing that after march 30](http://watson.stage1.mybluemix.net/smarterplanet/us/en/ibmwatson/developercloud/concept-expansion.html))

**Comment by germanattanasio** [comment]
I think we can remove Question and Answer

**Comment by nfriedly** [comment]
yea, I was starting to think that. I'll take care of it here soon.
