### ISSUE TITLE
[retrieve-and-rank] When the retrieve_and_rank_solr.v1.js example is run, I get a 400 error

### ISSUE THREAD

**Issue by adityagai** [watson-developer-cloud/node-sdk#216]
When I run the retrieve_and_rank_solr.v1.js, I get the following error:
```
Error uploading Solr config: {
  "code": 400,
  "error": {
    "msg": "WRRCSS028: Unable to open ZIP file for configuration [example_config]. error in opening zip file",
    "code": 400
  }
}
```
This is returned by default. Has something changed in the service or am I using the correct version of sdk
Please let me know.

**Comment by germanattanasio** [comment]
@gjs29 is this something you can take a look ?

**Comment by gjs29** [comment]
Looks like we were not uploading the zip file correctly. This commit should fix the issue: https://github.com/watson-developer-cloud/node-sdk/pull/217

**Comment by bastianentrup** [comment]
I get the same message using the curl command from the tutorial (the zip file is in the correct place and available, but I get the same message when the zip file is missing)

**Comment by jyothisankar** [comment]
Hi Adityagai,
This will occur if you don't specify '@' before your file path.

I added that and it gave 200 Ok.

Here is my **response**.
{"message":"WRRCSR026: Successfully uploaded named config [example_config] for Solr cluster [scba337b3a_29df_4e15_8160_c7ce4fae2970].","statusCode":200}
