### ISSUE TITLE
[personality-insights] SDK overrides content-items' language.

### ISSUE THREAD

**Issue by arypbatista** [watson-developer-cloud/node-sdk#220]
When using `node-sdk`'s Personality Insights wrapper, and using `contentItems` as payload without specify a language, the wrapper will assume that the payload is in English. 

This is a desired thing when sending `text/plain` payload, but if you do the same for `application/json` payload (content-items), then the service ignores each individual content-item language and tries to process all the content items with the wrapper's language choice.

**Comment by germanattanasio** [comment]
I will assign this to nathan since I'm working on the java-skd now

**Comment by nfriedly** [comment]
Oh, that's no good. Let me take a look.

**Comment by nfriedly** [comment]
Actually, this kind of feels like a service bug. But I added a fix (and a couple of tests) to the Node SDK.

Do you know if this also affects the other SDKs?

**Comment by nfriedly** [comment]
Oh, and it should be released as v1.3.1 once the CI loop finishes. Can you try it out and confirm that it resolves your issue @arypbatista ?

**Comment by arypbatista** [comment]
Solved my issue @nfriedly . Thanks. I will raise an issue on the service too. Regards

**Comment by nfriedly** [comment]
Cool, thanks!
