### ISSUE TITLE
Don't hit third party websites in integration tests

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/node-sdk#222]
One of our integration tests hits tech crunch, and a couple others hit the washington post. We should really use our own assets for testing.

**Comment by germanattanasio** [comment]
I created an app to host the resources we use in the integration tests

Bluemix app: https://watson-test-resources.mybluemix.net 
Initially, I copied the resources folder into that app but we can add more to it like html pages to test the alchemy microformat extraction
code: https://github.com/germanattanasio/watson-test-resources

**Comment by nfriedly** [comment]
I agree, we should probably add some html pages to the site and make all the tests use it. But for now, I think hitting things on ibm.com and alchemyapi.com is OK.
