### ISSUE TITLE
[text-to-speech] Add support for customizations

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/node-sdk#223]
Add support for customizations. See: https://watson-api-explorer.mybluemix.net/apis/text-to-speech-v1
There are new endpoints like `/v1/pronunciation` and `/v1/customizations`

**Comment by jeffpk62** [comment]
You can also refer to the documentation in the API reference, which may be easier to work with:
http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/text-to-speech/api/v1/?curl#customization_methods

**Comment by nfriedly** [comment]
Fixed in v2.2.0
