### ISSUE TITLE
[text-to-speech] Provide support for setting X-Watson-Learning-Opt-Out 

### ISSUE THREAD

**Issue by swgraham** [watson-developer-cloud/node-sdk#226]
For many compliance related implementations, we need to use the X-Watson-Learning-Opt-Out Header on requests.  Instantiating the text_to_speech with options should provide a documented and clear way to do it, for example:
```
watson.text_to_speech({
   username: blah,
   password: blah,
   voice: blah,
   opt-out: true,
});
```
Though I'm not sure on the tag we should use.  You can work around this (it seems) by overriding the headers completely this way:
```
watson.text_to_speech({
   username: blah,
   password: blah,
   voice: blah,
   headers: {
        'content-type': 'application/json',
        'X-Watson-Learning-Opt-Out' : true }
   }
});
```
But you have to pass in the content-type or it will get overridden.

**Comment by nfriedly** [comment]
I just added in support for including `X-Watson-Learning-Opt-Out` as an option for the `synthesize()` method - does that sound like a good solution to you.
