### ISSUE TITLE
[speech-to-text] connect ETIMEDOUT 158.85.132.94:443

### ISSUE THREAD

**Issue by prasanta303** [watson-developer-cloud/node-sdk#229]
- [speech-to-text] connect ETIMEDOUT 158.85.132.94:443
- Take a example script as below,

```js
var watson = require('watson-developer-cloud');
var speech_to_text = watson.speech_to_text({
  username: '*****************',
  password: '****************',
  version: 'v1'
});

speech_to_text.getModel({model_id:'en-US_BroadbandModel'}, function(err, model) {
  if (err)
    console.log('error:', err);
  else
    console.log(JSON.stringify(model, null, 2));
});
```
- On executing getting Error:
error: { [Error: connect ETIMEDOUT 158.85.132.94:443]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '158.85.132.94',
  port: 443 }
- Node version : v5.10.1
- NPM version:  v3.8.3

**Comment by nfriedly** [comment]
Hi @prasanta303 

It seems to work for me: when I enter a username and password and run it, I get

```js
{
  "name": "en-US_BroadbandModel",
  "language": "en-US",
  "sessions": "https://stream.watsonplatform.net/speech-to-text/api/v1/sessions?model=en-US_BroadbandModel",
  "url": "https://stream.watsonplatform.net/speech-to-text/api/v1/models/en-US_BroadbandModel",
  "rate": 16000,
  "description": "US English broadband model."
}
```
Does it always fail for you, or just occasionally? Do other services work?

**Comment by prasanta303** [comment]
It always fail for me. I am explaining you the before steps.
1. Installed watson-developer-cloud from command line as "npm install watson-developer-cloud" from working directory. 
2. I try to execute the script and getting the error as mentioned.
So, I have uninstalled the "watson-developer-cloud". And again try to install it again as "npm install watson-developer-cloud --save" and this time it is throwing same error with an error log which I am attached here with. The only difference of "watson-developer-cloud" installation from previous is added extra parameter "--save".
[npm-debug.txt](https://github.com/watson-developer-cloud/node-sdk/files/219336/npm-debug.txt)

ing herewith.

**Comment by nfriedly** [comment]
I think the issue is probably outside of the SDK then. It sounds more like a connectivity issue. `158.85.132.94` is the same IP that I get for `stream.watsonplatform.net` so DNS is working well. 

What's the output of the command `traceroute 158.85.132.94`?

**Comment by nfriedly** [comment]
Also, is it possible to test from a different computer, and from a different internet connection?

**Comment by prasanta303** [comment]
Update...
The error which I was getting during installation of  watson-developer-cloud due to mentioning wrong module name watson-developer-clou instead of watson-developer-cloud. Thanks again for pointing out the mistake.

About the ETIMEOUT error....It's due to DNS setting problem. After configuring DNS in my system, it works fine. So, I am closing the ticket.
