### ISSUE TITLE
[retrieve-and-rank] uploadConfig API call does not work in Bluemix

### ISSUE THREAD

**Issue by DanCunnington** [watson-developer-cloud/node-sdk#230]
The uploadConfig API call for Retrieve and Rank can't be used in Bluemix as it requires a .zip file path instead of a .zip file.

http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/retrieve-and-rank/api/v1/?node#upload_config

**Comment by nfriedly** [comment]
I believe this is also fixed, please re-open if I'm wrong.

**Comment by DanCunnington** [comment]
Yes this is fine, I used the 'temp' npm module as a workaround for Bluemix environments
