### ISSUE TITLE
[retrieve-and-rank] getConfig returns a zip file of 0 bytes

### ISSUE THREAD

**Issue by DanCunnington** [watson-developer-cloud/node-sdk#233]
Tried to call getConfig to return a zip file of the cluster configuration and an empty file is returned.

Node v4, SDK v1.4.1

**Comment by nfriedly** [comment]
Hey @DanCunnington sorry it took me ages to look at this. Can you let me know if there's an error returned?

For example, if I run this on a newly created cluster:

```js
var params = {
  cluster_id: id,
  config_name: 'example_config'
};

retrieve_and_rank.getConfig(params, function(err, data) {
  console.log(err, data);
}).pipe(fs.createWriteStream('config_example.zip'));
```

I get a small .zip file... but it's not actually a .zip - it's the error message below:

```
{ code: 404,
  error: 
   { msg: 'WRRCSS005: Configuration [example_config] does not exist.',
     code: 404 } }
```

**Comment by DanCunnington** [comment]
Tested with my cluster id and configuration name.. Looks good to me, correct zip file is returned @nfriedly :+1:

**Comment by nfriedly** [comment]
Cool beans.
