### ISSUE TITLE
[Dialog]sample template 'pizza.xml' doesn't work

### ISSUE THREAD

**Issue by qubing** [watson-developer-cloud/node-sdk#234]
I'm using SDK and CURL command to do upload template file of 'test/resource/pizza.xml' to Dialog Service on BlueMix, the encountered error. It seams there are something wrong with pizza.xml, I'd tried to modify the file just like below, it works fine.
Node version: 4.3.1
SDK Version: 1.2.4

**pizza.xml(original version):**
[https://raw.githubusercontent.com/watson-developer-cloud/node-sdk/master/test/resources/pizza.xml](url)

**Error:**
{ code: 409,
  error: 'The name already exists. Specify a unique name.' }

**pizza.xml(modified version):**
`<?xml version="1.0" encoding="UTF-8"?>
<dialog xsi:noNamespaceSchemaLocation="WatsonDialogDocument_1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <flow>
        <folder label="Main">
            <output>
                <prompt selectionType="RANDOM">
                    <item>Hi, I'm Watson! I can help you order a pizza, what size would you like?</item>
                </prompt>
            </output>
        </folder>
    </flow>
</dialog>`
**Result:**
`{dialog_id: "9a4a6007-c040-4a76-beec-e0c45ef97a38"}`

Please validate the pizza.xml in repository.

By the way, where can I find the **WatsonDialogDocument_1.0.xsd**?

**Comment by nfriedly** [comment]
Hi @qubing 

That error is not actually an issue with the xml file - when you do the cur command, it looks something like this:

```curl -u "{username}":"{password}" \
  -X POST
  --form file=@pizza.xml
  --form name=<NAME HERE>
  "https://gateway.watsonplatform.net/dialog/api/v1/dialogs"```

The `<NAME HERE>` part has to be unique. Pick a different name and it should work.

**Comment by qubing** [comment]
I'd run the get dialogs API first, the response is `{"dialogs":[],
  "language_packs":[
    {"name":"en-us-legacy", "dialog_id":"en-us-legacy"},
    {"name":"es-es", "dialog_id":"es-es"},
    {"name":"pt-br", "dialog_id":"pt-br"},
    {"name":"cs-cz", "dialog_id":"cs-cz"},
    {"name":"en-us", "dialog_id":"en-us"},
    {"name":"it-it", "dialog_id":"it-it"},
    {"name":"fr-fr", "dialog_id":"fr-fr"},
    {"name":"ja-jp", "dialog_id":"ja-jp"}]
}`

And then, I run the command below.
`curl -u "3967d191-b808-4bfd-8519-0e2017deb504":"AxxrPNjRAy7A" -X POST --form file=@pizza_sample.xml  --form name=pizza "https://gateway.watsonplatform.net/dialog/api/v1/dialogs"`
the response as below, so I think it's not the reason as you talked.
`{ code: 409,
error: 'The name already exists. Specify a unique name.' }`

**Comment by qubing** [comment]
OK. I found the reason, the quote after the parameter "form name" was missed. THX.
