### ISSUE TITLE
[speech-to-text] Getting error when trying to bind another service

### ISSUE THREAD

**Issue by prasanta303** [watson-developer-cloud/node-sdk#235]
- The service name : Speech To Text
- A description of the problem trying to solve : Trying to bind another service say AlchemyAPI in the same app and getting error message as......Service broker error: {"description"=>"Only one free key is allowed per account in a 24-hour period."} 
- A suggested solution if possible : Should be able to bind as many as services in one app, because an app may require to use more services one after another.

**Comment by nfriedly** [comment]
I think that error means that you can only create one free AlchemyAPI instance per day in bluemix, and it looks to be correctly enforcing the policy. Did you previously create a different AlchemyAPI service in Bluemix? If not, then you probably want to contact bluemix about that: https://console.ng.bluemix.net/?direct=classic/#/contactUs/cloudOEPaneId=contactUs

Either way, I'm pretty sure it's not an issue in the node SDK, so I'm closing this for now.

**Comment by prasanta303** [comment]
Yes, you said correctly I have created AlchemyAPI service previously. I will check it out after one day.
