### ISSUE TITLE
[language-translation] Example on the readme.md page for language translation gives an error 

### ISSUE THREAD

**Issue by prashantgupta24** [watson-developer-cloud/node-sdk#240]
The error is:  
      
``` 
{
  error_code: 404,
  error_message: 'cannot find service matching the request data'
}
```

It seems to be having an extra parameter, which is not present in the example on language translation in the docs.

Suggested solution is to remove the extra parameter present in the example on the readme.md page

**Comment by nfriedly** [comment]
Fixed in cafcec4
