### ISSUE TITLE
[text-to-speech] Early documentation for TTS customization interface leaking to node doc

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/node-sdk#255]
The documentation for the Node SDK is leaking early information about the TTS customization interface.  The information is unformatted and preliminary; we just need to suppress it for now.

_createCustomizations()
new customization features Summary of API calls API Number Method API URL Description API-01 POST /api/v1/customizations Create new custom model API-02 GET /api/v1/customizations?language="en-US" List custom models for a language API-03 DELETE /api/v1/customizations/{customization_id} Delete custom model API-04 GET /api/v1/customizations/{customization_id}? Query contents of custom model (optionally converts IPA to SPR phones) API-05 POST /api/v1/customizations/{customization_id} Update contents of custom model, including adding one or more words API-06 PUT /api/v1/customizations/{customization_id}/words/{word} Add a single word to custom model API-07 POST /api/v1/customizations/{customization_id}/words Add one or more words to custom model API-08 GET /api/v1/customizations/{customization_id}/words/{word} Query details for a word in custom model API-09 GET /api/v1/customizations/{customization_id}/words List contents of words in custom model API-10 DELETE /api/v1/customizations/{customization_id}/words/{word} Delete single word from custom model API-11 GET /api/v1/pronunciation?text=aword&voice=voiceModel&format=ipa|spr Gets the IPA (or optionally the SPR) pronunciation of a given word for a given voice model (default=en-US_MichaelVoice) TTS API Implementation_

**Comment by germanattanasio** [comment]
This will get fix along with #223

**Comment by nfriedly** [comment]
Closing as this is now public. (I've started work on #223 although it's not yet complete.) Sorry it took a while :/
