### ISSUE TITLE
[text-to-speech] Changes to interface of synthesize() method

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/node-sdk#256]
The interface of the synthesize() method needs to be changed in two ways:

**1.** The options parameter needs to be changed back to params for consistency with the rest of the Node SDK interface.
**2.** The X-Watson-Opt-Out-Header needs to be removed from the list of parameters and specified the way it is elsewhere in the Node SDK interface.

**Comment by nfriedly** [comment]
1. is fixed
2. *also* works the normal way, but this allows it to be changed on a per-request basis, a feature that is currently used by the demo,

**Comment by nfriedly** [comment]
On second thought, I think we should just remove the feature from both the SDK and the demo... it looks like it doesn't even work properly in the demo anyways: https://github.com/watson-developer-cloud/text-to-speech-nodejs/blob/master/public/js/demo.js#L64

**Comment by ammardodin** [comment]
This is resolved in the upcoming release. Closing.
