### ISSUE TITLE
[speech-to-text] Clarify example of createRecognizeStream() in README file

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/node-sdk#258]
The example of the createRecognizeStream() method in the README for the Node SDK could be improved in a couple of ways.  The current example reads as follows:

```
var watson = require('watson-developer-cloud');
var fs = require('fs');

var speech_to_text = watson.speech_to_text({
  username: '<username>',
  password: '<password>',
  version: 'v1'
});

var params = {
  // From file
  audio: fs.createReadStream('./resources/speech.wav'),
  content_type: 'audio/l16; rate=44100'
};

speech_to_text.recognize(params, function(err, res) {
  if (err)
    console.log(err);
  else
    console.log(JSON.stringify(res, null, 2));
});

// or streaming
fs.createReadStream('./resources/speech.wav')
  .pipe(speech_to_text.createRecognizeStream({ content_type: 'audio/l16; rate=44100' }))
  .pipe(fs.createWriteStream('./transcription.txt'));
```

I would suggest two changes:
- Either show two separate examples of the method for file and streaming input, or show just a single example; either approach would make the example code a little more straightforward.
- If we preserve the streaming example, change the code to demonstrate how to see results on the console.  Currently, only the text of the final transcript is made available, and that's written to a file.  It would be better to use an example that demonstrates how to pass parameters to the call and how to display them on the console.

**Comment by loretoparisi** [comment]
@germanattanasio I'm adding here instead of opening a new issue to add a en example about a real world usage like to pipe a input read stream from audio device to the api when in `streaming` mode:

See [here](http://stackoverflow.com/questions/40751922/buffer-readstream-in-node-from-sox-to-ibm-watson-speech-to-text) a question about how to use `SOX` to record voice and pipe using node `stream`  to the `createRecognizeStream`

```
 bufferStream
  .pipe(speech_to_text.createRecognizeStream({ content_type: 'audio/l16; rate=16000' }))
  .pipe(fs.createWriteStream('./transcription.txt'));
```

This is not exactly that simple, so a full example would be awesome.

Thank you.

**Comment by nfriedly** [comment]
I just talked to Josh Zheng earlier today, he's doing a demo next week running STT on a Raspberry Pi with microphone input. He said he'd make his code available and probably write up a tutorial sometime soon. I'll put a link here, and probably in the repo once that's ready.

**Comment by loretoparisi** [comment]
@nfriedly that would be awesome, thank you.

**Comment by loretoparisi** [comment]
@nfriedly any update on this?

**Comment by nfriedly** [comment]
Yep, here you go: https://github.com/boxcarton/tjbot-raspberrypi-nodejs/blob/master/tj_raspberrypi/run_raspberry.js

Thanks @boxcarton

**Comment by nfriedly** [comment]
@loretoparisi also see 

https://medium.com/ibm-watson-developer-cloud/build-a-chatbot-that-cares-part-1-d1c273e17a63#.o9hj0v4ap

and 

https://medium.com/ibm-watson-developer-cloud/build-a-chatbot-that-cares-part-2-66367cf26e4b#.ho3stavwy

for additional instructions.

**Comment by loretoparisi** [comment]
@nfriedly thanks this helped a lot!

**Comment by ammardodin** [comment]
This will be fixed in the upcoming release. Closing this issue.

**Comment by wandonye** [comment]
I don't think this issue has been addressed. It's still two examples mixed together. 
I also checked the links @nfriedl posted above. But they are out of date. I modified it according to the new api into the codes below 

```
const micParams = { 
  rate: 44100, 
  channels: 2, 
  debug: false, 
  exitOnSilence: 6
}
export const micInstance = mic(micParams);
export const micInputStream = micInstance.getAudioStream();

let pauseDuration = 1;
micInputStream.on('pauseComplete', ()=> {
  console.log('Microphone paused for', pauseDuration, 'seconds.');
  setTimeout(function() {
      micInstance.resume();
      console.log('Microphone resumed.')
  }, Math.round(pauseDuration * 1000)); //Stop listening when speaker is talking
});

export const textStream = micInputStream.pipe(
  speechToText.createRecognizeStream({
    content_type: 'audio/l16; rate=44100; channels=1',
  })).setEncoding('utf8');

textStream.on('data', (user_speech_text) => {
  console.log(user_speech_text.toLowerCase());
});
```

gives the following error after `micInstance.start()` is triggered:

```
Uncaught Error: Unable to determine content-type from file header, please specify manually.
    at RecognizeStream._write
```

In particular I was trying to get the microphone streamed directly to the speechToText service. I believe this is the most common way of using mic, not piping it into a .wav and then stream the .wav file to stt.

**Comment by vkjuju** [comment]
Hi, in 2018 speech_to_text version ,there might be a little different, how can I pip it without generating .wav? sample code is as follows:

var mic;
var SpeechToTextV1 = require('watson-developer-cloud/speech-to-text/v1');
var fs = require('fs');
var watson = require('watson-developer-cloud');
var cp = require('child_process');
 mic = cp.spawn('arecord', ['--device=plughw:1,0', '--format=S16_LE', '--rate=44100', '--channels=1']); //, '--duration=10'
 mic.stderr.pipe(process.stderr);
 stt();
 
 function stt() {
	console.log("openCMDS");
        var speech_to_text = new SpeechToTextV1({
        username: '06fb1d83-0837-49df-a71d-6293c4dd998b',
        password: 'ok742F7q7VHy'
        });

	var params = {
	content_type: 'audio/wav',
	model: 'zh-CN_BroadbandModel',
	continuous: true,
	inactivity_timeout: -1
	};

	recognizeStream = speech_to_text.createRecognizeStream(params);
        mic.stdout.pipe(recognizeStream);
        //mic.stdout.pipe(require('fs').createWriteStream('test.wav')); 
 
        // Pipe in the audio.
        fs.createReadStream('test.wav').pipe(recognizeStream);
        recognizeStream.pipe(fs.createWriteStream('transcription.txt'));

	recognizeStream.setEncoding('utf8'); 
	console.log("start record");
       
       recognizeStream.on('data', function(event) { onEvent('Data:', event); });
       recognizeStream.on('error', function(event) { onEvent('Error:', event); });
       recognizeStream.on('close', function(event) { onEvent('Close:', event); });

// Display events on the console.
function onEvent(name, event) {
    console.log(name, JSON.stringify(event, null, 2));
     }
		
}

**Comment by vkjuju** [comment]
@dpopp07 , Thanks for your response, I don't quite understand on "content_type for params 'audio/l16; rate=44100; channels=1'",  could you modify and paste them on my sample codes?

**Comment by dpopp07** [comment]
In your code, you have:
```
var params = {
content_type: 'audio/wav',
model: 'zh-CN_BroadbandModel',
continuous: true,
inactivity_timeout: -1
};
```
To change, the `content_type`, change that block to:

```
var params = {
content_type: 'audio/l16; rate=44100; channels=1', // this is the new code
model: 'zh-CN_BroadbandModel',
continuous: true,
inactivity_timeout: -1
};
```

**Comment by jeffpk62** [comment]
By the way, the `continuous` parameter is a no-op.  It was deprecated last year.  It's now essentially always `true`.

**Comment by vkjuju** [comment]
0 byte on  transcript.txt and there's no text on my screen with the following codes:

	var speech_to_text = new SpeechToTextV1({
			username: '06fb1d83-0837-49df-a71d-6293c4dd998b',
			password: 'ok742F7q7VHy'
			});

			var params = {
			//content_type: 'audio/wav',
			content_type: 'audio/l16; rate=44100; channels=1',
			model: 'zh-CN_BroadbandModel',
			continuous: true,
			inactivity_timeout: -1
			};

			recognizeStream = speech_to_text.createRecognizeStream(params);//創建stream辨識
			mic.stdout.pipe(recognizeStream);//將mic音訊pipe至recognizetream
			//mic.stdout.pipe(require('fs').createWriteStream('test.wav'));

			// Pipe in the audio.
			//fs.createReadStream('test.wav').pipe(recognizeStream);
			mic.stdout.pipe(recognizeStream).pipe(fs.createWriteStream('transcription.txt'));
			//recognizeStream.pipe(fs.createWriteStream('transcription.txt'));

			recognizeStream.setEncoding('utf8');
			console.log("start record");
		   // recognizeStream.on('results',  function(event){//如果有結果則進入

			// Listen for events.
		   recognizeStream.on('data', function(event) { onEvent('Data:', event); });
		   recognizeStream.on('error', function(event) { onEvent('Error:', event); });
		   recognizeStream.on('close', function(event) { onEvent('Close:', event); });

	// Display events on the console.
	function onEvent(name, event) {
		console.log(name, JSON.stringify(event, null, 2));
		 }

	}
