### ISSUE TITLE
[Documentation] Anchor links broken on watson-developer-cloud.github.io/node-sdk/master/

### ISSUE THREAD

**Issue by maxbridges** [watson-developer-cloud/node-sdk#260]
The anchor links on the document that's generated from readme.md do not work at http://watson-developer-cloud.github.io/node-sdk/master/.

**Comment by germanattanasio** [comment]
This is a valid issue but there is no easy fix since the markdown links will not match the autogenerated documentation.
The autogenerated html based on the readme doesn't have the anchor links.
