### ISSUE TITLE
[speech-to-text] observeResult() not returning interim results

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/node-sdk#262]
I realize the observeResult() method is deprecated, but it's still available, so I need to have a functional example.  The following small Node program (renamed for attachment) tests the STT interface with sessions: [sessions.txt](https://github.com/watson-developer-cloud/node-sdk/files/291927/sessions.txt).  Everything works fine except for observeResult(), which returns no interim results. I've tried reversing the order of the calls to observeResult() and recognize(), and I've tried using setTimeout() to delay the call to recognize().  But in all cases, I get the following error at the end of program execution:

```
{
  "code_description": "Not Found",
  "code": 404,
  "session_closed": true,
  "error": "Session was closed."
}
```

If I remove the call to deleteSession(), I still don't get interim results, but the call to observeResult() times out with the following error:

```
{
  "code_description": "Request Time-out",
  "code": 408,
  "session_closed": true,
  "error": "Session timed out due to inactivity after 30 seconds."
}
```

Getting interim results with this method is not straightforward, so maybe I've made a mistake somewhere.  Otherwise, the method itself may have an issue.

**Comment by germanattanasio** [comment]
@jeffpk62 try with this example https://gist.github.com/germanattanasio/359580d99ea22f47c6ba#file-app-js

**Comment by jeffpk62** [comment]
I have this working now, so I'm closing it.  I had to do a better job of delaying execution of the recognize method and also use cookie_session. which appears to be required only for observeResult().  Sorry for the false issue.
