### ISSUE TITLE
[AlchemyLanguage] Execution instruction

### ISSUE THREAD

**Issue by prasanta303** [watson-developer-cloud/node-sdk#263]
Hello,
I have downloaded the source and trying to execute. Could you please help me with steps how to execute the above mentioned ?

**Comment by kognate** [comment]
For language, you can have a look at the examples in https://github.com/watson-developer-cloud/node-sdk/blob/master/examples/alchemy_language.v1.js

You can also access tutorials and documentation at http://www.ibm.com/developerworks/

Lastly,  there is a demo at http://www.alchemyapi.com/products/demo/alchemylanguage?cm_mc_uid=77258961851314623689163&cm_mc_sid_50200000=1464962333

that lets you experiment with the api.
