### ISSUE TITLE
[speech-to-text] Update example in README

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/node-sdk#265]
#### @jeffpk62

While testing the STT `createRecognizeStream()` call from the Node SDK, I found some things that you may want to improve in the examples:
I found the current example in the README a little confusing. It might be better either to show just one approach or to show two separate examples.
The example for reading from a stream doesn't appear to consider the `content-type` parameter for me.  I have the following code:

``` js
var watson = require('watson-developer-cloud');
var fs = require('fs');

var speech_to_text = watson.speech_to_text({
  username: 'USERNAME',
  password: 'PASSWORD'
  version: 'v1'
});

var params = {
  content_type: 'audio/flac',
  continuous: true,
  interim_results: true
};

fs.createReadStream('../resources/audio-file.wav')
  .pipe(speech_to_text.createRecognizeStream(params))
  .pipe(fs.createWriteStream('./transcription.txt'));
```

Even though the content_type doesn't match the audio file, it still produces a correct transcript.  If I use the same inconsistency with the following example, the transcript is again correct but the interim results and their values are not the same and the service appears to be less sure of the results.  The same may be true in the previous example, but I can't tell since all I have is the final transcript and that's correct.  One related comment is that the example doesn't demonstrate how to see any results but the final transcript, which it pipes to a file.
The following code from `node-sdk/examples/speech_to_text.v1.js`, which we use in the documentation now, doesn't display events properly for me:

``` js
var watson = require('watson-developer-cloud');
var fs = require('fs');

var speech_to_text = watson.speech_to_text({
  username: 'USERNAME',
  password: 'PASSWORD',
  version: 'v1'
});

var params = {
  content_type: 'audio/wav',
  continuous: true,
  interim_results: true
};

// Create the stream.
var recognizeStream = speech_to_text.createRecognizeStream(params);

// Pipe in the audio.
fs.createReadStream('../resources/audio-file.wav').pipe(recognizeStream);

// Pipe out the transcription to a file.
recognizeStream.pipe(fs.createWriteStream('transcription.txt'));

// Get strings instead of buffers from 'data' events.
recognizeStream.setEncoding('utf8');

// listen for 'data' events for just the final text
// listen for 'results' events to get the raw JSON with interim results, timings, etc.

['data', 'results', 'error', 'connection-close'].forEach(function(eventName) {
    recognizeStream.on(eventName, console.log.bind(console, eventName + ' event: '));
});
```

It produces the following output:

```
results event:  { results: [ { alternatives: [Object], final: false } ], result_index: 0 }
results event:  { results: [ { alternatives: [Object], final: false } ], result_index: 0 }
results event:  { results: [ { alternatives: [Object], final: true } ], result_index: 0 }
data event:  hello world
```

I replaced the previous event-handling code with the following code to get what I would normally expect from a call to the service API with some intro headings added for clarity:

``` js
// Listen for events.
recognizeStream.on('data', function(event) { onEvent('Data:', event); });
recognizeStream.on('results', function(event) { onEvent('Results:', event); });
recognizeStream.on('error', function(event) { onEvent('Error:', event); });
recognizeStream.on('close-connection', function(event) { onEvent('Close:', event); });

// Displays events on the console.
function onEvent(name, event) {
    console.log(name, JSON.stringify(event, null, 2));
};
```

We might consider using this in the example, since it produces something a little more clear.

**Comment by ammardodin** [comment]
I will update the examples for the upcoming release to be more consistent.

**Comment by germanattanasio** [comment]
duplicate of #259
