### ISSUE TITLE
[speech-to-text] RecognizeStream does not emit a "connection-close" event.

### ISSUE THREAD

**Issue by crunchex** [watson-developer-cloud/node-sdk#274]
See https://github.com/watson-developer-cloud/node-sdk/blob/master/services/speech_to_text/recognize_stream.js Line 122.

The documentation and examples for speech-to-text assume an event for "connection-close". Yet instead, the actual event is a "close".

SDK version: 1.5.0
node version: 5.12.0

**Comment by nfriedly** [comment]
Good catch, thanks.
