### ISSUE TITLE
support for  X-Watson-Learning-Opt-Out

### ISSUE THREAD

**Issue by jwickens** [watson-developer-cloud/node-sdk#284]
An option to set the header  X-Watson-Learning-Opt-Out would be very useful in this library. Some companies have very strict privacy requirements and as such, without such a configurable option the wdc node sdk would not be usable in these cases.

**Comment by nfriedly** [comment]
Yes, you're right. A few of the entries in the SDK support it, but it's been kind of ad-hoc. We need a better method that works across the entire library.

**Comment by nfriedly** [comment]
Oh, actually, it is supported everywhere, it just isn't documented very well...  When creating the service instance, add a headers object like so:

```js
var myInstance = watson.whatever_service({
  /* username, password, version, etc... */
  headers: {
    "X-Watson-Learning-Opt-Out": "1"
  }
});
```

I'll add a note to the readme.

**Comment by jwickens** [comment]
thanks, that will do just fine.
