### ISSUE TITLE
[alchemy_language] Uncaught undefined Error

### ISSUE THREAD

**Issue by tlindener** [watson-developer-cloud/node-sdk#298]
- node 6.3.4
 - node-sdk 2.0.2

I have a couple of integration tests which use the alchemy api. Those tests sometimes run into the following error:

     Uncaught Error: Uncaught, unspecified "error" event. ([object Object])
      at classification-engine.js:208:26
      at node_modules/async/lib/async.js:726:13
      at node_modules/async/lib/async.js:52:16
      at done (node_modules/async/lib/async.js:241:17)
      at node_modules/async/lib/async.js:44:16
      at node_modules/async/lib/async.js:723:17
      at node_modules/async/lib/async.js:167:37
      at classification-engine.js:197:25
      at node_modules/watson-developer-cloud/alchemy-language/v1.js:33:7
      at Request._callback (node_modules/watson-developer-cloud/lib/requestwrapper.js:69:5)
      at Request.self.callback (node_modules/request/request.js:187:22)
      at Request.<anonymous> (node_modules/request/request.js:1044:10)
      at Gunzip.<anonymous> (node_modules/request/request.js:965:12)
      at endReadableNT (_stream_readable.js:913:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by nfriedly** [comment]
Hi @tlindener,

Any chance you could get a prettyprint of that `[object Object]`? My guess is that the service itself hit some kind of error and the library passed it allong as the error object in your callback function at `classification-engine.js:197:25`. (Although, right now the library sometimes returns regular objects rather than Error instances right now. Let me see if I can change that real quick...)

**Comment by nfriedly** [comment]
I just pushed `v2.0.3` with a small change to ensure `error` objects passed to callbacks are always `instanceof Error`, which may help getting clearer messages out of your tests when something fails.

It should be up on npm as soon as the CI loop finishes.

**Comment by tlindener** [comment]
Hi, thanks for the quick response. I haven't been able to reproduce the error (at least after I upgraded to the latest version):

I actually don't no where the [object Object] comes from. I have printed all errors to a log file. But it didn't catch this.

As a follow up, I've been extending my test coverage and found another "Uncaught Error". I simply left the password blank. Although it's pretty obvious, I guess this should be covered, right?

     Uncaught Error: Unauthorized: Access is denied due to invalid credentials.
<HTML><HEAD><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><TITLE>Watson Error</TITLE></HEAD><BODY><HR><p>Invalid access to resource - /natural-language-classifier/api/v1/classifiers/33fffex86-nlc-188/classify</p><p>User access not Authorized.</p><p>Gateway Error Code : ERCD04-NOAUTHHDR-PLTFRMREQ</p><p>Unable to communicate with Watson.</p><p>Request URL : https://158.85.132.88:443/natural-language-classifier/api/v1/classifiers/33fffex86-nlc-188/classify</p><p>Error Id :  gateway-dp01-180383972</p><p>Date-Time : 2016-08-11T06:28:09-04:00</p></BODY></HTML>
      at Request._callback (node_modules/watson-developer-cloud/lib/requestwrapper.js:68:15)
      at Request.self.callback (node_modules/request/request.js:187:22)
      at Request.<anonymous> (node_modules/request/request.js:1044:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:965:12)
      at endReadableNT (_stream_readable.js:913:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by nfriedly** [comment]
Yea, that makes sense, although I probably shouldn't stuff the HTML into the error message. 

For the "uncaught" part, does your code look something like this:

```js
watson.do_whatever({/*...*/}, function(err, res) {
  if (err) {
    throw err; // <-- this line in particular
  }
  // do stuff with result
});
```
The SDK should not be `throw`ing errors, just returning them to the callback. So I don't think it would get the "uncaught error" prefix unless your code was doing the `throw` (?)

**Comment by nfriedly** [comment]
Closing for now, please re-open or file a new ticket if you're still experiencing this issue.
