### ISSUE TITLE
[language-translator] example incorrect

### ISSUE THREAD

**Issue by stevenatkin** [watson-developer-cloud/node-sdk#301]
Description in comments

**Comment by stevenatkin** [comment]
The require statement for the Language Translator example is incorrect:

var LanguageTranslatorV2 = require('watson-developer-cloud/language_translator/v2');

This should be replaced with:

The underscore character is incorrect it should be "-"

var LanguageTranslatorV2 = require('watson-developer-cloud/**language-translator**/v2');

**Comment by nfriedly** [comment]
Good catch, should be fixed in v2.1.1 once the CI loop runs
