### ISSUE TITLE
[Alchemy vision] this service no longer available in Bluemix

### ISSUE THREAD

**Issue by josepmao** [watson-developer-cloud/node-sdk#308]
Hi Alchemy vision no longer available and it has been replaced by Visual recognition.  would it be better move related code to avoid confusion.
Thanks.

**Comment by kognate** [comment]
Thanks for filing this issue.   We'll be removing this in the future.

**Comment by nfriedly** [comment]
To add some details, although no new users can sign up for Alchemy Vision, existing users can continue to use the service until May 20, 2017 - so we won't remove support from the SDK until after that point. 

I'll update the readme to clarify this point, though.
