### ISSUE TITLE
Conversation Error "Require is not defined"

### ISSUE THREAD

**Issue by hayslan1** [watson-developer-cloud/node-sdk#310]
What the hell ????
![print](https://cloud.githubusercontent.com/assets/17702862/18481859/39f109f6-79b4-11e6-8c67-1c9ecb35c22b.png)

**Comment by germanattanasio** [comment]
You are trying to use the library on the client side without compiling it with `browserify` or `webpack`. The browser doesn't know what `require` is.

There is a `browserify` section in the README: https://github.com/watson-developer-cloud/node-sdk#client-side-support-via-browserify

In the future please spend some time looking at the documentation before opening issues. This is not the first time you have opened an issue for a problem that is not related to the repository.
