### ISSUE TITLE
[Speech-to-text] Support customization model feature

### ISSUE THREAD

**Issue by zywind** [watson-developer-cloud/node-sdk#311]
New version of Watson STT supports customization model, which allows the user to point to a customized language model.  This is done through setting the header, but is not currently supported by the nodejs SDK.

I added the following lines at https://github.com/watson-developer-cloud/node-sdk/blob/master/speech-to-text/recognize_stream.js#L64 to support this:
```
  if (options['customization-local-path']) {
    options.headers['customization-local-path'] = options['customization-local-path'];
  }
```
It would be great if you can incorporate this change.  Thanks.

**Comment by germanattanasio** [comment]
When creating a service you can specify headers and those will use on each API call.

```js
var SpeechToTextV1 = require('watson-developer-cloud/speech-to-text/v1');

var service = new SpeechToTextV1({
  username: '<Text to Speech username>',
  password: '<Text to Speech password>'
  url: watson.TextToSpeechV1.URL,
  headers: {
    'customization-local-path': '<your-customization-path>'
  }
});
```

We will be adding Speech to Text customization in  few weeks.
