### ISSUE TITLE
STT using old initialisation structure invokes TTS getModels

### ISSUE THREAD

**Issue by chughts** [watson-developer-cloud/node-sdk#313]
I had code looking like - 

````
   var watson = require('watson-developer-cloud');
  
    var stt = watson.speech_to_text({
      username: username,   
      password: password, 
      version: 'v1',
      url: 'https://stream.watsonplatform.net/speech-to-text/api'
    });

    stt.getModels({}, function(err, models){
      if (err) {
        res.json(err);
      } else {
        res.json(models);
      }
    }); 
````

but the returned data is TTS models.

I have had to change and use the new flat structure require to fix the problem.

**Comment by nfriedly** [comment]
That's strange. It works as expected for me. Is there any chance that you have multiple endpoints responding to the same request url, and a different models one is responding before this one? Can you post your complete code?

**Comment by germanattanasio** [comment]
Apparently, it was a problem in @chughts environment.
