### ISSUE TITLE
Support for React native.

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/node-sdk#315]
Some of our APIs don't work when using it React Native.
 https://facebook.github.io/react-native/

**Comment by kognate** [comment]
Which ones?

**Comment by germanattanasio** [comment]
I don't remember but it think it was Visual Recognition or the speechs

**Comment by nfriedly** [comment]
Probably STT, because it uses the native (C++) websocket library.

> React Native combines smoothly with components written in Objective-C, Java, or Swift.

I don't recall anything else that uses C++ code, but there might be other service wrappers that do.

**Comment by onosol** [comment]
Any chance on getting full react-native support?

**Comment by nfriedly** [comment]
Hi @onosol 

I haven't had the time to do much testing myself; can I ask what you've tried and what worked or didn't work?

**Comment by onosol** [comment]
I haven't tried recently. I originally tried integrating with React-Native back in Sept 2016 utilizing TextToSpeech, SpeechToText, and WatsonConversation. Was just curious if any work had been done on React-Native integration since then.....

**Comment by zunair-syed** [comment]
Are there ANY APIs supported? I'm trying to integrate STT and TTS into a React-native app, but its a really painful process. Also, the module 'Watson-Speech' does not work as it is for web only. So at the moment, there seems to be 0 support for React-Native.

**Comment by nfriedly** [comment]
Hi @zunair-syed,

Unfortunately I still haven't had any time to really look into this, but I do have a couple of ideas:

Could you try doing something similar to https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/recognize-microphone.js only replace `get-user-media-promise` with the `getUserMedia` implementation from https://www.npmjs.com/package/react-native-webrtc ?

That *might* be enough to make it work properly. 

Also, you can try using Text to Speech without the SDK and see if you have better luck that way? If you generate an Auth token, then it's just a url to an audio file, so you may be able to use it with a different React Native audio player.

**Comment by pwcremin** [comment]
I am building a React Native module for the Watson sdk and I had no problem with text to speech or speech to text.  You can use the module or see the code for any example.

[react-native-bluemix](https://www.npmjs.com/package/react-native-bluemix)

**Comment by nfriedly** [comment]
That's awesome @pwcremin - thank you!

**Comment by bgbraga** [comment]
Closed with no support?

**Comment by anweshan** [comment]
@bcbraga see comment from pwcremin

**Comment by jsstylos** [comment]
@bgbraga Can you elaborate more on what you're looking for?

I think this issue was originally created to track a problem that some services in the SDK were reported to not work when called from React Native. @pwcremin indicated that the services he tried *did* work, and provided a community library around them, so we closed this issue.

At this time we have no plans to provide an official React Native specific SDK like @pwcremin's, and don't have any concrete reports of services or methods not working through React Native. If you have a specific problem about a service or method not working that you think we can fix by addressing in the Node SDK, we'd be interested to hear about them.

**Comment by bgbraga** [comment]
@jsstylos I'm looking for a official support. Maybe that project can get @pwcremin effort (that is really nice) and support it. @pwcremin does not support all APIs and I don't know if he will have time to keep it working and compatible with new SDK versions.

But I understand. No plans to support RN. So I will use another solution: a node.js app as a "proxy" receiving mobile requests and using node SDK to access Watson APIs.
