### ISSUE TITLE
[conversation] - Only able to call starting dialog.

### ISSUE THREAD

**Issue by mohamedsahadkp** [watson-developer-cloud/node-sdk#316]
Only able to call starting dialog after that not working. but it is working fine in "https://www.ibmwatsonconversation.com" portal.

**Comment by chughts** [comment]
@mohamedsahadkp 
The issue log for this repo is not the right place for your question. This forum is for developers reporting bugs in the SDK. Your question is not a bug. I know what you are doing wrong, but I will not answer the question here, as that would set a poor precedence. 

Please ask this question to the developerworks forum - https://developer.ibm.com/answers/topics/watson/
where you will receive all the help you need.
