### ISSUE TITLE
[speech-to-text] please support customization_id

### ISSUE THREAD

**Issue by zywind** [watson-developer-cloud/node-sdk#320]
For some reason, this is supported by speech-javascript-sdk (as can be seen here: https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/recognize-stream.js#L31) but not by node-sdk.

**Comment by nfriedly** [comment]
Hey, sorry for the delay in responding. You're right, this should be supported. Do you think you can send me a Pull Request with the change + a unit test to go with it?

**Comment by nfriedly** [comment]
Op, I didn't realize quite how big this update was yesterday, I was just thinking of adding a new `customization_id` parameter to the existing methods. If you want to do that (or the entire task of adding support for managing custom models/copra/words), let me know; but if not, I'll try and get it all finished in the next couple of weeks.

**Comment by zywind** [comment]
Please go ahead. I won't be working on this. Thanks!

**Comment by nfriedly** [comment]
Fixed in #329, should be released in `v2.7.0` once the CI loop finishes.
