### ISSUE TITLE
[text-to-speech] Add "Repair WAV Header" (as in the ios-sdk)

### ISSUE THREAD

**Issue by tanmayb123** [watson-developer-cloud/node-sdk#324]
In the ios-sdk on the WDC, for the TtS service, there's functionality that can repair the WAV Header once it's received from Watson. I'd like to add that to the Node SDK.

Steps to reproduce: 
1 - Use the following code:

``` javascript
     var text_to_speech = new TextToSpeechV1({
        username: '[YOUR_USERNAME]',
        password: '[YOUR_PASSWORD]'
      });
      var params = {
        text: response.output.text[0],
        voice: 'en-US_MichaelVoice', // Optional voice
        accept: 'audio/wav'
      };
      var stream = text_to_speech.synthesize(params).pipe(fs.createWriteStream('output.wav'));
      stream.on('finish', function() {
        console.log('finished!');
      })
```

2 - Run the code, and open "output.wav" in iTunes.
3 - It plays, but if you notice, the duration of the file is ~20 hours long...
**NOTE - It does play properly, and when the file is "over" (Watson is done speaking), iTunes does stop playing. It does NOT play for ~20 hours. Although, I think this may depend on the media player you use.**

I know the cause of this problem: The header of the WAV file isn't able to indicate the "length" of the file properly. This is causing me problems when trying to play the WAV file from Node.

The ios-sdk handles this nicely, by repairing the header of the file. In fact, here's an excerpt of some code from the ios-sdk:

``` swift
func dataToUTF8String(data: NSData, offset: Int, length: Int) -> String? {
    let range = NSMakeRange(offset, length)
    let subdata = data.subdata(with: range)
    return String(data: subdata, encoding: String.Encoding.utf8)
}

func dataToUInt32(data: NSData, offset: Int) -> Int {
    var num: UInt32 = 0
    let length = 4
    let range = NSMakeRange(offset, length)
    data.getBytes(&num, range: range)
    return Int(num)
}

//This is the actual function that repairs the Header:
func repairWAVHeader(data: NSMutableData) {

    // resources for WAV header format:
    // [1] http://unusedino.de/ec64/technical/formats/wav.html
    // [2] http://soundfile.sapp.org/doc/WaveFormat/

    // update RIFF chunk size
    let fileLength = data.length
    var riffChunkSize = UInt32(fileLength - 8)
    let riffChunkSizeRange = NSMakeRange(4, 4)
    data.replaceBytes(in: riffChunkSizeRange, withBytes: &riffChunkSize)

    // find data subchunk
    var subchunkID: String?
    var subchunkSize = 0
    var fieldOffset = 12
    let fieldSize = 4
    while true {
        // prevent running off the end of the byte buffer
        if fieldOffset + 2*fieldSize >= data.length {
            return
        }

        // read subchunk ID
        subchunkID = dataToUTF8String(data: data, offset: fieldOffset, length: fieldSize)
        fieldOffset += fieldSize
        if subchunkID == "data" {
            break
        }

        // read subchunk size
        subchunkSize = dataToUInt32(data: data, offset: fieldOffset)
        fieldOffset += fieldSize + subchunkSize
    }

    // compute data subchunk size (excludes id and size fields)
    var dataSubchunkSize = UInt32(data.length - fieldOffset - fieldSize)

    // update data subchunk size
    let dataSubchunkSizeRange = NSMakeRange(fieldOffset, fieldSize)
    data.replaceBytes(in: dataSubchunkSizeRange, withBytes: &dataSubchunkSize)
}
```

It would be great if we could add this functionality to the Node SDK. In fact, I'm working on a Pull Request, it's just that I have constraints on time right now. I may not be able to get this done too soon.
If anyone else has any suggestions or can submit a PR, please do!

Also, for now, I was able to "patch" the problem by bridging some Swift code (the above) with my Node.JS code (very "workaround"-y, not a permanent solution).

My SDK Version is 2.4.6.

Thanks!
- Tanmay Bakshi (TajyMany)

**Comment by nfriedly** [comment]
Hi Tahmay,

Thanks, this will be a great addition.

You may want to look at how the [wav package](https://www.npmjs.com/package/wav) handles this: https://github.com/TooTallNate/node-wav/blob/master/lib/writer.js

Although, now that I think about it, it may make more sense to just use that package directly rather than re-writing the same code.

**Comment by tanmayb123** [comment]
Hi -

Thanks for getting back to me - I'm working on a Pull Request for this using the wav package.

- Tanmay Bakshi (TajyMany)

**Comment by ammardodin** [comment]
This has already been added to the SDK. I will also make sure to include it in the upcoming release.
