### ISSUE TITLE
AlchemyAPI breaks with simple input

### ISSUE THREAD

**Issue by fxfactorial** [watson-developer-cloud/node-sdk#327]
Trying out the AlchemyAPI, sentiment, I gave it this input

"I love programming"

and received an error: 

```
 {"error":"unsupported-text-language","code":400}
```

I'm not sure if the error is with this api or more fundamentally with watson, or whatever is powering it. 

Please close if not the responsibility of this SDK .

**Comment by kognate** [comment]
The error message is unhelpful here.  The problem is that you are using a text snippet too short to be recognized as english.

You need to pass the language for short snippets like this.

See this gist https://gist.github.com/kognate/2b9b76e11af65f5e61dc7a00fb0ee8d1 for an example.

**Comment by fxfactorial** [comment]
@kognate I've given it single word input before and received a score, I love programming seemingly have a positive sentiment.

**Comment by kognate** [comment]
@fxfactorial Yes,  that is true.  Sometimes single words are identifiable as english.  I don't know what it is about "I love programming"  but it is not recognized as english.   If you specify 'english' (as in the gist I posted) you get a positive sentiment.

**Comment by fxfactorial** [comment]
@kognate One frustrating thing about this SDK is that what parameters are validate aren't documented anywhere, what keys are going to be recognized and what is supposed to be the type of the corresponding value, I've been having to look at the REST api, guessing.

**Comment by kognate** [comment]
One thing that can sometimes help is the api explorer https://watson-api-explorer.mybluemix.net/apis/alchemy-language-v1#/   

it's at least much easier to use (and debug) than trying to do things in bluemix.  

The rest of your comment is definitely something we are working on to make it better (though I know that doesn't really help you at this moment).
