### ISSUE TITLE
[document-conversion] Incorrectly forces UTF-8 for HTML

### ISSUE THREAD

**Issue by mfulgo** [watson-developer-cloud/node-sdk#332]
In the current `master` branch of the SDK, the `DocumentConversionV1` incorrectly forces the `UTF-8` charset on HTML documents.  See https://github.com/watson-developer-cloud/node-sdk/blob/master/document-conversion/v1.js#L70

It should do one or both of the following:
1. Allow the user to specify the charset `X` of the input document and set the file part's `contentType` to `text/html; charset=X`.
2. Default the file part's `contentType` to `text/html` without specifying the `charset`.

The assertion that the service [requires utf-8](https://github.com/watson-developer-cloud/node-sdk/blob/master/document-conversion/v1.js#L66) is incorrect: If the charset is not specified in the file part, the service will look for it in the HTML's `meta` tags.

**Comment by mfulgo** [comment]
This also has the unfortunate side-effect of incorrectly-converting non-UTF-8 HTML input files in the demo.

**Comment by kognate** [comment]
The sdk accepts a param for content type already,  though that doesn't fix the demo.  

What happens with the service if the HTML meta tags do not indicate a charset?  For example, if the charset is not specified and the meta tags are ambiguous?

**Comment by mfulgo** [comment]
It depends: If there's a byte order mark at the beginning, from which we
can determine the charset, we use that otherwise, it falls back to UTF-8.

On Sat, Nov 12, 2016, 00:53 Joshua Smith <notifications@github.com> wrote:

The sdk accepts a param for content type already, though that doesn't fix
the demo.

What happens with the service if the HTML meta tags do not indicate a
charset? For example, if the charset is not specified and the meta tags are
ambiguous?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/watson-developer-cloud/node-sdk/issues/332#issuecomment-259987479>,
or mute the thread
