### ISSUE TITLE
[speech-to-text] recognize() sessions/sessionless returning only first keyword

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/node-sdk#335]
When you specify the keywords parameter with the session-based or sessionless recognize() methods, you get only the first keyword.  This same problem appears to now be fixed with the WS createRecognizeStream() method.  It looks like the same problem is an issue here, though I believe it used to work.  Perhaps the change for the WS method reversed some logic for the HTTP REST calls?

@bvonhag fyi

**Comment by nfriedly** [comment]
This should be fixed for `recognize()` as of v2.8.3 - https://github.com/watson-developer-cloud/node-sdk/blob/master/speech-to-text/v1.js#L89

It always worked on `createRecognizeStream()` because the `keywords` param is passed in the opening JSON message rather than in the querystring, so no conversion is needed.

Are you still seeing the issue somewhere?

**Comment by jeffpk62** [comment]
I just did a `node install watson-develop-cloud --save` about 20 minutes ago, and the issue with WS method is fixed, but now I'm seeing it in the REST calls.

**Comment by nfriedly** [comment]
Without `@latest`, the `npm install` command will limit itself to the version range allowed by your current package.json.

Can you run ` npm ls watson-developer-cloud` to see what version you're currently on, and then run `npm install watson-develop-cloud@latest --save` if it's not `v2.9.0`?

**Comment by jeffpk62** [comment]
OK, thanks a lot, Nathan.  That updated to the latest release, and keywords are now working properly, so I'll close this.  You guys should add the command for getting the latest version of the SDK to the README.  I incorrectly thought doing an install of the latest package would force an update.

**Comment by nfriedly** [comment]
That's an NPM thing to protect against breaking changes, and the standard is to recommend installing without the `@latest` tag. If you don't already have it listed in your package.json (which is the case for most users installing the library), then it will install the latest version anyways. It's only if you have a package.json which depends on an older version that installing will give you the older version.

The command `npm outdated` will tell you if any of your dependencies have newer versions available.

**Comment by jeffpk62** [comment]
Thanks for the brief npm tutorial, Nathan.  I'm recording all of this so that I have it for future reference, hopefully avoiding the need to bother you about it in the future!
