### ISSUE TITLE
[speech-to-text] regression; support for customization_id is gone

### ISSUE THREAD

**Issue by zywind** [watson-developer-cloud/node-sdk#336]
It was fixed in #329, but now it's gone. Please add it back.

**Comment by germanattanasio** [comment]
it was not removed. See https://github.com/watson-developer-cloud/node-sdk/blob/master/speech-to-text/v1.js#L34

**Comment by nfriedly** [comment]
This wasn't a regression, but support was never added to the RecognizeStream. Fixed in #337 / https://github.com/watson-developer-cloud/node-sdk/commit/425767d710e1002a2f2fc856c11f946bf717b40b
