### ISSUE TITLE
[speech-to-text] customization_id does not work

### ISSUE THREAD

**Issue by zywind** [watson-developer-cloud/node-sdk#337]
You need to add 'customization_id' to the QUERY_PARAMS_ALLOWED in the following line.
https://github.com/watson-developer-cloud/node-sdk/blob/master/speech-to-text/recognize_stream.js#L30

I tested it. Once I have that there, customization works.

**Comment by nfriedly** [comment]
Right, thanks. Sorry your last ticket was closed prematurely.

Should be released in `v2.9.1` once Travis CI is done.

**Comment by zywind** [comment]
v2.9.1 is still not released yet... any reason why?

**Comment by nfriedly** [comment]
Op, I'm sorry, I never pushed the tag, which is what triggers Travis to ship a new release. It's done now, though.
