### ISSUE TITLE
[speech-to-text] Reduce descriptive text for methods

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/node-sdk#352]
The descriptions in the JSDoc for a number of methods are long and difficult to read.  The most prevalent examples are

- addCorpus()
- addWords()
- getCustomization()
- getWords()
- trainCustomization()

In addition to be being difficult to read, the information is not current with updates to the documentation.  I would strongly suggest that the JSDoc provide minimal descriptions of the methods, as it does in most cases, and rely on the documentation for more detailed information.  Trying to maintain the JSDoc information, keep it consistent, and present it in a meaningful fashion isn't worth the effort.

**Comment by nfriedly** [comment]
Op, sorry, they were initially copied from the api ref. Can you send me a PR that just trims offending things down to 1-liners and maybe a link to the relevant docs?

Also, anchor links don't seem to be reliably working for the API ref in firefox - e.g. http://www.ibm.com/watson/developercloud/speech-to-text/api/v1/#add_corpora usually takes me to the top of the page (although I did get it to work once). Not sure what the deal is there.

**Comment by jeffpk62** [comment]
Have you updated to the version of the API reference with German's fix to the TOC linking problem?  Links were badly broken for a while.  This is either an artifact of that issue or a new problem.  This link in the documentation source file is fine, and it's working for me.

I can send you something for the method descriptions, but it won't be soon, unfortunately.  I'm really buried at the moment.  I'll open an issue against myself to get to this when I can, which may be next year at this point.

**Comment by nfriedly** [comment]
OK, that's fine. I think we're all scrambling right now. 

I haven't looked at the API ref code recently.

**Comment by jeffpk62** [comment]
Nathan, shouldn't we leave this one open for the work on the SDK?

**Comment by nfriedly** [comment]
Take a look at the commit that closed it ;)
 
I did a bunch of work on this for other PRs today, so I went ahead and took care of this one while I was already looking at it. 

http://watson-developer-cloud.github.io/node-sdk/master/SpeechToTextV1.html should look much nicer once the CI loop finishes.

**Comment by jeffpk62** [comment]
Thanks, Nathan!  I thought you were still waiting for me.  Nice job!  Now I can get rid of my issue. :-)

**Comment by nfriedly** [comment]
Yep, I was just starting to write a comment on that one :D
