### ISSUE TITLE
[speech-to-text] Add getCorpus() method

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/node-sdk#359]
The service recently added the equivalent of a getCorpus() method to return information about a single corpus.  It returns the same information as getCorpora() but for a single specified corpus only.  It's very useful for learning the status of an addCorpus() call, and it's the analog of all of the get one/many methods offered by the service.

**Comment by kognate** [comment]
This has been added (and has been there for a few weeks).

**Comment by jeffpk62** [comment]
OK, thanks.  It wasn't there when I opened the issue; glad to know that it's been added.
