### ISSUE TITLE
[text-to-speech] Add support for streaming WebSocket interface

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/node-sdk#360]
The Text to Speech service, like Speech to Text, supports a WebSocket interface.  For Text to Speech, the WS interface provides extra functionality not available with the HTTP REST interface, specifically use of the SSML <mark> tag and word timing output.  This interface should also be available from the Node SDK.

**Comment by nfriedly** [comment]
This one is also being tracked internally in https://github.ibm.com/Watson/developer-experience/issues/1326

**Comment by nfriedly** [comment]
Additional info from internal ticket:

http://www.ibm.com/watson/developercloud/text-to-speech/api/v1/#wss_methods

Should be a [DuplexStream](https://nodejs.org/api/stream.html#stream_implementing_a_duplex_stream) that can accept text input and outputs binary audio.

The STT `createRecognizeStream()` method and `RecognizeStream()` show some example streams that work in the opposite direction; the [implementation in the JS SDK](https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/recognize-stream.js) is a better, more up-to-date example.

Ideally this stream (when browserfied) will be usable client-side also, helping with https://github.ibm.com/Watson/developer-experience/issues/312

**Comment by dpopp07** [comment]
Available in [3.14.0](https://github.com/watson-developer-cloud/node-sdk/blob/master/CHANGELOG.md#3140-2018-12-06)
