### ISSUE TITLE
[speech-to-text] Handle interim_results parameter with recognize() method

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/node-sdk#361]
We don't document that this is supported currently, but the method does accept the interim_results parameter.  However, the response output is really ugly.  We should either clean up the output that we return or prevent the user from including the parameter with the method altogether.

**Comment by nfriedly** [comment]
ugly? It should just be returning whatever the service sends back.

 Although it doesn't really make sense to use `interim_results` with `recognize()` because all the results are going to come back at the same time anyway, right?

**Comment by jeffpk62** [comment]
Without interim results, I print out nice results.  With interim results, it looks a lot like one long continuous line of this:

`"{\n   \"results\": [\n      {\n         \"alternatives\": [\n            {\n               \"timestamps\": [\n                  [\n                     \"the\", \n                     0.03, \n                     0.09\n                  ], \n                  [\n                     \"latest\", \n                     0.09, \n                     0.6\n                  ], \n                  [\n                     \"weather\", \n                     0.6, \n                     0.91\n                  ]\n               ], \n               \"transcript\": \"the latest weather \"\n            }\n         ], \n         \"final\": false\n      }\n   ], \n   \"result_index\": 0\n}{\n   \"results\": [\n      {\n         \"alternatives\": [\n            {\n               \"timestamps\": [\n                  [\n                     \"the\", \n                     0.03, \n                     0.09\n                  ], \n                  [\n                     \"latest\", \n                     0.09, \n                     0.6\n                  ], \n                  [\n                     \"weather\", \n                     0.6, \n                     0.85\n                  ], \n                  [\n                     \"report\", \n                     0.85, \n                     1.52\n                  ]\n               ], \n               \"transcript\": \"the latest weather report \"\n            }\n`

I understand that I'm not using it programmatically, but this is the first time I've seen something this ugly in a response.  I also understand that interim results aren't totally useful when they arrive with final results.  But there's a difference between not supporting a parameter at all and supporting once whose results may be of dubious worth. :-)

I wanted to make you aware of this in case you wanted to either suppress it entirely or could do something to beautify what's returned.

**Comment by nfriedly** [comment]
Ohm I understand now. Normally it parses the JSON - but with interim results, the service apparently sends multiple JSON objects, concatenated together, rather than a single big object - see the `0\n}{\n` near the middle. Since this isn't valid JSON (if passed directly to `JSON.parse()`), the SDK just returns the result as a string.

**Comment by jeffpk62** [comment]
Is there an easy way to disable the parameter with this method so that it can't be called?  That's probably a reasonable response in this case.

**Comment by nfriedly** [comment]
Yea, I suppose we could do that.

**Comment by ammardodin** [comment]
@nfriedly It seems like you've added a `formatChunk()` helper that, after a quick peek, looks like it's making a reasonable attempt at handling this ? Can this issue be closed ?
