### ISSUE TITLE
[conversation-api] Unable to connect and the bot is sending back an error

### ISSUE THREAD

**Issue by vickylance** [watson-developer-cloud/node-sdk#364]
When I try to send a message to the conversation api, I am not getting a response from the bot instead I am seeing this error in the console.

error: { [Error: getaddrinfo EAI_AGAIN]
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'gateway.watsonplatform.net' }

Is this a network issue if so what is the actual url that the nodejs is trying to hit?
I am just using the conversation-enhanced demo.

- [ v0.12.2 ] Node version
- [ v2.11.1 ] SDK version

EDIT: I am using this inside a corporate proxy. Its working fine in my home.

**Comment by kognate** [comment]
Can you resolve `gateway.watsonplatform.net` from inside your corp. network?

**Comment by vickylance** [comment]
@kognate  Yes I can, but I have to allow only this "https://gateway.watsonplatform.net/*" right? No other urls are required? also its https right?

**Comment by germanattanasio** [comment]
It's `https` and you need gateway.watsonplatform.net and stream.watsonplatform.net

**Comment by vickylance** [comment]
@germanattanasio Thank You. I will unblock them and let you know.

**Comment by vickylance** [comment]
@germanattanasio @kognate 
When I simply hit this "https://gateway.watsonplatform.net/" I am getting 
{ "code" : 403 , "error" : "Forbidden" , "description" : "2016-12-22T00:12:24-05:00, Error ERCD-NOCONFIG occurred when accessing https://158.85.132.88:443/, Tran-Id: gateway-dp01-597640048 - " } 

And when I hit this "https://stream.watsonplatform.net" I am getting
{ "code" : 403 , "error" : "Forbidden" , "description" : "2016-12-22T00:13:48-05:00, Error ERCD-NOCONFIG occurred when accessing https://158.85.132.94:443/, Tran-Id: stream-dp02-118588836 - " } 

Which means I am able to hit the servers via my network and then I got this error response back right? I am not getting any proxy issues in my browser. So is there any other problem? Because I am able to run the same example from my home.

**Comment by vickylance** [comment]
Ok I have found a solution.

I had to run the following commands before npm start

npm config set https-proxy http://username:password@proxy.company.com:8080/
npm config set proxy http://username:password@proxy.company.com:8080/
set https_proxy=http://username:password@proxy.company.com:8080/
set http_proxy=http://username:password@proxy.company.com:8080/

and then finally npm start
