### ISSUE TITLE
Language translator (v2) : Error : this request accepts only application/(x-www-form-urlencoded|json) content-type

### ISSUE THREAD

**Issue by Cheyenne55** [watson-developer-cloud/node-sdk#367]
Hello,

I am using Node.js and when running the example provided for the language translator service (https://www.npmjs.com/package/watson-developer-cloud#language-translator) I encounter the following error :
![error](https://cloud.githubusercontent.com/assets/14312865/21581837/0232bdc2-d042-11e6-819a-7642f31833cf.png)

**Comment by nfriedly** [comment]
Hi @Cheyenne55,

I believe this was resolved in #362 - can you confirm that you're on the latest version (2.14.4)?

To check, run 

    npm ls watson-developer-cloud --depth 0

And, to update, run

   npm install watson-developer-cloud@latest --save

(Without the `@latest` part, it will honor your package.json and possibly install an older version)
