### ISSUE TITLE
[visual-recognition] Support getting a token for visual recognition service

### ISSUE THREAD

**Issue by cfjedimaster** [watson-developer-cloud/node-sdk#372]
The getToken aspect of the Authorization feature expects you to tell it a username and password for the service in question. But the latest version of the visual recognition service uses an API key instead. I want to use the Authorization feature so I can directly "speak" to the VR service in my mobile app using the token.

**Comment by nfriedly** [comment]
Unfortunately, this is not currently supported at the service level. Alchemy APIs and Visual Recognition (which is partially based on Alchemy Vision), only support access via API keys.

I'll pass your request along to the service team, though.
