### ISSUE TITLE
Sample for Translator errors with request accepts only application/(x-www-form-urlencoded|json) content-type

### ISSUE THREAD

**Issue by csantanapr** [watson-developer-cloud/node-sdk#378]
Currently using npm package version 2.15.0 and node 6.7.0

Following the example in [README](https://github.com/watson-developer-cloud/node-sdk/blob/master/README.md) where it states to specify the url with `v2`
```
var LanguageTranslatorV2 = require('watson-developer-cloud/language-translator/v2');

var language_translator = new LanguageTranslatorV2({
  username: '<username>',
  password: '<password>',
  url: 'https://gateway.watsonplatform.net/language-translator/api/v2/'
});

language_translator.identify({
  text: 'The language translator service takes text input and identifies the language used.' },
  function (err, language) {
    if (err)
      console.log('error:', err);
    else
      console.log(JSON.stringify(language, null, 2));
});
```

Using the value `https://gateway.watsonplatform.net/language-translator/api/v2/`
It produce an error
```
this request accepts only application/(x-www-form-urlencoded|json) content-type
```

When debugging the package in [lib/requestwrapper.js#L162](https://github.com/watson-developer-cloud/node-sdk/blob/master/lib/requestwrapper.js#L162) `options.url` for the http request becomes one with double `v2/v2` like this `https://gateway.watsonplatform.net/language-translator/api/v2/v2/identify`

Since [language-translator/v2.js#L223](https://github.com/watson-developer-cloud/node-sdk/blob/master/language-translator/v2.js#L223) it's already adding the `v2/`:
```
  var parameters = {
    options: {
      url: '/v2/identify',
      method: 'POST',
      body: params.text
    },
```
Then the url should not contain the v2 when the user configures the library.

I think the README should be updated to have the url without the v2
```
var language_translator = new LanguageTranslatorV2({
  username: '<username>',
  password: '<password>',
  url: 'https://gateway.watsonplatform.net/language-translator/api'
});
```

**Comment by nfriedly** [comment]
Yes, I believe you are correct.

**Comment by nfriedly** [comment]
Should be fixed in `v2.15.1` once the CI loop completes 

I changed the documentation, example, and error message that it emits if the url is unset to show the correct URL (without the v2).

**Comment by csantanapr** [comment]
Wow @nfriedly that was fast 👍

**Comment by nfriedly** [comment]
Sorry, I just ran into this yesterday, and I figured out that I had the wrong URL pretty quickly, but I didn't realize where it came from at the time. So, thanks for the bug report :)

**Comment by csantanapr** [comment]
@nfriedly It was reported to use by an user our IBM Bluemix OpenWhisk service.
