### ISSUE TITLE
[text-to-speech] getCustomizations(language) reporting all languages instead of specified language

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/node-sdk#380]
The TTS `getCustomizations()` method, when given a language, is supposed to return the custom models only for the specified language.  Instead, the method returns the models for all languages.  Also, the description of the language parameter says that only US English is supported, but all languages are supported for TTS customization.

**Comment by nfriedly** [comment]
You must pass in an object, not the language string directly, then it works as expected.

**Comment by jeffpk62** [comment]
Nathan, I'm not sure what object you're referring to.  The method's only parameter is a language string:

`language String <optional> optional filter. Currently only en-US is supported.`

I don't think there is an object for the language?

**Comment by nfriedly** [comment]
Where are you seeing that?

The method takes two parameters, an object named params, and a callback function. In the params object, there is an optional field named language.

The bit about en-US only is wrong, I updated the code to remove that.

**Comment by jeffpk62** [comment]
We're just using the same term for two different things, @nfriedly; sorry.  I pass the method a JSON object whose sole field is language; I'm referring to language as a parameter, since it's what's passed to the method via the formal object parameter.  Sorry for not being more clear.

On a brighter and stupider note, the method is working fine.  I had an idiotic logic error in a simple statement in my code, a statement so simple that I neglected to validate it correctly and so never found the defect until now.  It's a dumb error that's totally my fault.  Thanks for the quick responses.
