### ISSUE TITLE
[speech-to-text] whenCustomizationReady() should not fail with no corpus

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/node-sdk#382]
When creating a custom model. the user does not need to add corpora to the model.  The user can add only individual words with the words methods of the interface, without using corpora at all.  So a valid custom model can exist that has no corpora, and this method should not fail due to a lack of corpora in the model.

**Comment by nfriedly** [comment]
Aah, good catch.

**Comment by nfriedly** [comment]
Should be released in v2.15.3 shortly
