### ISSUE TITLE
[speech-to-text] Add sort parameter to customization getWords() method

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/node-sdk#384]
The `getWords()` method of the STT customization interface accepts an additional parameter, `sort`.  I've pasted the description of the parameter below to make it easier for you to add it:

![sort](https://cloud.githubusercontent.com/assets/10051651/22306829/bafb921e-e30e-11e6-9305-17f3d8541e18.png)

This was a somewhat recent addition to the interface.

**Comment by adrien2p** [comment]
i've added the parameter i waiting for these merging.

**Comment by nfriedly** [comment]
Fixed in #400
