### ISSUE TITLE
Update the SDK documentation on the NPM page

### ISSUE THREAD

**Issue by felipefiali** [watson-developer-cloud/node-sdk#388]
The TOC and code examples are outdated for some services. I know for sure that the Discovery documentation is outdated, but all of them should be updated:

https://www.npmjs.com/package/watson-developer-cloud

**Comment by nfriedly** [comment]
Hi,

Can you give me specifics?

I see that discovery is still showing experimental instead of v1 - is there anything else?

**Comment by felipefiali** [comment]
I believe that the DocumentConversion is also outdated, I remember following the code there some time ago and it wouldn't work. 

That's why I mentioned all of them. I think it's worth at least going through them to check if they're updated. Or maybe just remove the code examples from there and point users to the actual documentation which also has some code examples for Node.

**Comment by felipefiali** [comment]
The Discovery API Reference is actually very poor. I'm not sure if you guys could update it though:

https://www.ibm.com/watson/developercloud/discovery/api/v1/?node#list_environment

**Comment by nfriedly** [comment]
Yea, the SDK documentation there is generally slightly behind the initial release of the SDK.
