### ISSUE TITLE
[watson-developer-cloud/node-sdk] Installing breaks meteor application

### ISSUE THREAD

**Issue by Dschuli** [watson-developer-cloud/node-sdk#392]
After getting an error, which breaks the whole Meteor setup,  when installing watson-developer-cloud  for use in a rather complex Meteor project (Error: Segmentation fault (core dumped) | Meteor App exited with code 139), I was able to reproduce the error with the most basic Meteor setup (demo app - simple todo) to avoid any interference from other packages. 

- [x] Steps to reproduce (on working meteor application): meteor npm install watson-developer-cloud --save  
- [x] Expected behavior: Successful meteor startup (actually watson is not even used in the apppplication yet)
- [x] Actual behavior: Application terminates with error 
    * Under fish: fish: “meteor” terminated by signal SIGSEGV (Address boundary error)
    * Under bash: Segmentation fault (core dumped)
- [x] Node version: node v6.9.5. npm 3.10.10
- [x] SDK version: 2.17.1

After removal of the package the meteor application starts up fine again.

**Comment by nfriedly** [comment]
Confirmed, very strange.

On my mac, bash errors with 

```
[[[[[ ~/simple-todos ]]]]]                    

=> Started proxy.                             
Bus error: 10or web.browser                  /
```

And fish errors with:
```
[[[[[ ~/simple-todos ]]]]]                    

=> Started proxy.                             
fish: Job 1, 'meteor' terminated by signal SIGBUS (Misaligned address error)
```

Which isn't exactly the same, but sounds like it's the same issue. I'll see if I can narrow it down further, but I'm honestly pretty stumped.

**Comment by nfriedly** [comment]
I narrowed it down to the `gh-pages` folder, which is an artifact of the build process and shouldn't have been included in npm releases in the first place. So, with that removed, you can now install `watson-developer-cloud@2.18.0` and meteor works again.

I have no idea why the presence of the `gh-pages` folder causes meteor to segfault, but I'll file a ticket there and let them look into it if they want.

**Comment by Dschuli** [comment]
@nfriedly Thx a million for fixing that issue so fast! Appreciated!
