### ISSUE TITLE
Visual recognition doesn't accept request variables as image_file 

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/node-sdk#4]
@jthomas found a problem with:

```js
var watson = require('watson-developer-cloud'); 
var request = require('request'); 
  
var visual_recognition = watson.visual_recognition({ 
  username: '<username>', 
  password: '<password>', 
  version: 'v1' 
}); 
  
var params = { 
  image_file: request('http://visual-recognition-demo.mybluemix.net/images/horses.jpg') 
}; 
visual_recognition.recognize(params, function(err, res) { 
  if (err) 
    console.log(err); 
  else 
    console.log(JSON.stringify(res, 'labels', 2)); 
}); 
```

Aparently the request to get horses.jpg start after the recognize request.

**Comment by germanattanasio** [comment]
We should be able to handle this case by getting the data from the image_file Stream before calling the `/recognize` function.

**Comment by germanattanasio** [comment]
hey @nfriedly  can you look at this?

**Comment by nfriedly** [comment]
My first guess is that this stemming from a missing `Content-Length` header - http://visual-recognition-demo.mybluemix.net/images/horses.jpg uses `Transfer-Encoding: chunked` rather than declaring the file size in the headers, so perhaps our request to the visual recognition service is also getting sent without a content-length (I don't think that you can do chunked POSTs.) 

I'll look into it more on Monday and let you know.

**Comment by germanattanasio** [comment]
Last time I tried to fix this it was related to `Content-Length` so I think you are right.  
Should we throw an error if `Content-Length` is not specified or try to guess it based on the file

**Comment by nfriedly** [comment]
Yea, that's probably the best route.  (Assuming this is the issue.)

We could just buffer the file in memory and then get the length, but that
could lead to trouble with big files or busy servers.

**Comment by germanattanasio** [comment]
What if we open a bug in `request` and ask them to fix this. This is actually something they should do if they support streams.

**Comment by nfriedly** [comment]
Yea, that's a good point too.

**Comment by germanattanasio** [comment]
I put a question in stackoverflow and I'm giving 50 points... that's how you call the sharks.

http://stackoverflow.com/questions/29040797/fire-a-get-request-and-get-the-node-stream

**Comment by jxm262** [comment]
@germanattanasio  just posted an answer on SO.  If you get really stuck, I can try to dig into the actual code for you.

**Comment by germanattanasio** [comment]
Thanks @jxm262,  I will take a look at that.

**Comment by germanattanasio** [comment]
Check if we can use `options` as described here: https://github.com/request/request#multipartform-data-multipart-form-uploads

**Comment by germanattanasio** [comment]
After trying with `options` as described here: https://github.com/request/request#multipartform-data-multipart-form-uploads I realized that `request` doesn't tell us the file name and the service needs the file extension. If I write a filename as part of the request to the VR service I won't be able to choose the right extension without looking at the incoming request. Let's just ask for a `fileReadStream()`, and I'm going to mark this as **wontfix**.
