### ISSUE TITLE
[speech-to-text] Provide access to transaction ID in recognize stream

### ISSUE THREAD

**Issue by bensechrist** [watson-developer-cloud/node-sdk#412]
It would be helpful to expose the transaction ID for the STT WebSocket connection for debugging and reporting errors.

**Comment by nfriedly** [comment]
Thanks for filing the issue here, I almost forgot about this!

**Comment by nfriedly** [comment]
Starting with `v2.24.0` (which should be released by CI shortly), RecognizeStream instances should have a `.getTransactionId()` method that returns a Promise that will resolve with the Transaction ID.
