### ISSUE TITLE
[speech-to-text] asynchronous creation, can't get `recognitions.completed_with_results`

### ISSUE THREAD

**Issue by micahbrich** [watson-developer-cloud/node-sdk#415]
Hey there! I seem to have hit some issue in defining asynchronous callback events — [the docs](https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/?node#create_job) mention you can pass an extra query parameter to request the completed callback to include results, but I can't make that happen.

I've got this:

```js
const params = {
    'content_type': 'audio/wav',
    audio: request(`https://${clip.wav}`),
    'callback_url': hostname + '/callback',
    'user_token': clip.id,
    model: 'en-US_NarrowbandModel',
    content_type: 'audio/wav',
    inactivity_timeout: -1,
    interim_results: false,
    max_alternatives: 4,
    word_confidence: true,
    timestamps: true,
    profanity_filter: false,
    smart_formatting: true,
    speaker_labels: true,
    'word_alternatives_threshold':0.5,
    events: "recognitions.started,recognitions.completed_with_results,recognitions.failed",
  };

  Watson.createRecognitionJob(params, function(error, job) {
    if (error)
      console.log('Error:', error);
    else
      console.log(JSON.stringify(job, null, 2));
  });
```

The callback registration, transcription, and everything else is working great, just not the specified callback `events`. I get something like the last two events shown here:

<img width="724" alt="screen shot 2017-03-14 at 11 26 33" src="https://cloud.githubusercontent.com/assets/25366/23923801/80c4758e-08de-11e7-9327-0d5a24abbd02.png">

I tried specifying `events` in the `params` as a comma-separated string like the docs suggest & an array of strings (which the source looks like converts to a comma-separated string). I tried `events` as the key, but also `event` as a Hail Mary attempt. I tried writing the list as both `recognitions.completed_with_results` and just `completed_with_results`, in case it was a misunderstanding.

I _can_ successfully use that `recognitions.completed` event ID to do a new `GET` request and get the results, but it's an extra step in a pretty time-sensitive app, so I'm hoping I can get the event & result in one like the docs suggest.

Does anyone have any ideas what's up? Am I missing something, or doing anything wrong? Is this a bug?

**Comment by adrien2p** [comment]
Thank you for your back, i ´ll work on it as soon as possible and i give you a return on this issue.

**Comment by micahbrich** [comment]
Thanks @adrien2p ! If I can do anything, let me know.

**Comment by jeffpk62** [comment]
@adrien2p, it looks like the `event `parameter is coded to accept a single string rather than a comma-separated list of strings at line 134 of `node-sdk/speech-to-text/v1.js`:

`@param {string} [params.event] - recognitions.started|recognitions.completed|recognitions.failed|recognitions.completed_with_results`

**Comment by adrien2p** [comment]
@jeffpk62 you right, it's codded to accep string were you can pass ´event1,event2,event3, ...´

**Comment by nfriedly** [comment]
@micahbrich This should be fixed in v2.26.1 which is now available on npm. Can you test and confirm?

**Comment by micahbrich** [comment]
Hmmmm @nfriedly I can't explain it yet, but this isn't quite working.

It _does_ successfully pass the events now, but it seems like when I include:
```
events: ["recognitions.started","recognitions.failed","recognitions.completed_with_results"]
```
in the options object, I don't ever get any `completed_with_results` callback. And I'm thinking that means _something_ is working, because I _also_ don't get a `completed` callback when I do that, either, which would be expected if the former were working.

I did dig into the library folder and saw that the `events` option was returning two functions along with the strings — I can't tell if that's how `request` works or not.

```js
...
options: { qs: 
   { callback_url: 'https://testurl.ngrok.io/callback',
     events: 
      [ 'recognitions.started',
        'recognitions.failed',
        'recognitions.completed_with_results',
        sum: [Function],
        average: [Function] ],
     continuous: true,
     max_alternatives: 0,
     timestamps: true,
     word_confidence: true,
     inactivity_timeout: -1,
     model: 'en-US_NarrowbandModel',
     interim_results: false,
     profanity_filter: false,
     smart_formatting: true,
     speaker_labels: false },
  url: 'https://stream.watsonplatform.net/speech-to-text/api/v1/recognitions',
...
```

I can't figure out how to see the final URL that gets sent, though. Does that look normal?

**Comment by micahbrich** [comment]
Wait! 🙌 Update, I spoke too soon. It looks like it works when I pass it a string. I swear I tried that before, I'm not crazy. I'm successfully getting both `recognitions.started` and `recognitions.completed_with_results` back! Awesome awesome awesome, so great!

**Comment by adrien2p** [comment]
Yes you should give a coma separated dtring as 
`events: 'event1, event2, ...'`

**Comment by nfriedly** [comment]
Doh. We should make the SDK handle that. Users should be able to pass in an array and have it work.

not sure where the sum & average functions are coming from, I wonder if something is mucking with Array.prototoye somewhere...

**Comment by nfriedly** [comment]
Starting with v2.27.1, it should accept either a comma-separated string or an array of strings.

**Comment by micahbrich** [comment]
You guys are so on it. 🏀

**Comment by adrien2p** [comment]
@nfriedly Well done man :)
