### ISSUE TITLE
Access RNR behind a proxy

### ISSUE THREAD

**Issue by CDeschietere** [watson-developer-cloud/node-sdk#421]
I think I've found a problem when trying to use RNR service behind a proxy in the node sdk. 

I've talked to the support team which said to me that there was no problems when accessing this service behind a proxy. But after some investigations I've found that the problem only occurs when I'm using the SolrClient Library.

In fact, I'm no Node expert but, it seems that the 'http' package used by [Solr Node Client](https://github.com/lbdremy/solr-node-client) doesn't let you do request through proxies [Http.get doc](https://nodejs.org/api/http.html#http_http_get_options_callback). And that's why you can't fully use Rank & Retrieve behind a proxy.

Let me know if that seems correct to you. The problem isn't really yours but it affects the SDK because of the faulty package. If that's correct your support teams doesn't seem to be aware of it.

**Comment by nfriedly** [comment]
Hi @CDeschietere, it sounds like you're right. 

This SDK uses [request](https://github.com/request/request) for most things, which has built-in proxy support. It looks like the Solr Node Client library actually uses request in one or two places, but not for the majority of connections that it makes.

I'll file an issue on Solr Node Client requesting that they add support for proxies, and once it's updated, I can update the Node.js SDK.

In the meanwhile, I'm not sure that I have a good answer for you - is there any chance that your network could be modified to allow connections to Watson to bypass the proxy?

**Comment by CDeschietere** [comment]
I can't bypass the proxy, but I've managed to do a quick'n dirty fix directly in the solr library. As I'm currently prototyping it will do the job.
I'm waiting for your update 

(Don't forget to send a little note to your support team :yum: )

Thank you for your answer !

**Comment by nfriedly** [comment]
Fair enough. Can I ask what the quick'n dirty fix was? (And, would it be worth posting on https://github.com/lbdremy/solr-node-client/issues/195?)

**Comment by CDeschietere** [comment]
I just used [request](https://github.com/request/request) instead of the node http.get method. The import was already done on the top this [file](https://github.com/lbdremy/solr-node-client/blob/master/lib/solr.js)

And I changed the following [method](https://github.com/lbdremy/solr-node-client/blob/master/lib/solr.js#L932)
