### ISSUE TITLE
[document conversion] verify that conversion_target is specified

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/node-sdk#422]
## Context
It seems like `conversion_target` needs to be specified twice during a call to `convert()`

1. As a top level parameter
2. As parameter in the `config` object

Example code:

```js 
document_conversion.convert({
    file: {
      value: new Buffer(contents),
      options: {
         content_type:'application/pdf'
          }
      },
      conversion_target: document_conversion.conversion_target.ANSWER_UNITS,
      config: {
            conversion_target: document_conversion.conversion_target.ANSWER_UNITS,
            html_to_answer_units: {selectors: [ 'h1', 'h2','h3', 'h4']}
            }
          },
      function (err, answerUnits) {});
```

If you remove one of those `conversation_target` variables you will get an error from the API.
This was reported by a customer who also found the workaround described above.

We should copy the `conversation_target` from the root directory into the `config` object before calling `convert()`
## Acceptance criteria

 - [ ] The SDK detects when `conversion_target` is only specified in one place and returns an error.

**Comment by germanattanasio** [comment]
#420 is an example of this problem

**Comment by ammardodin** [comment]
This service has been deprecated. Closing.
