### ISSUE TITLE
Feature request: ES5-compatible version

### ISSUE THREAD

**Issue by Cleanshooter** [watson-developer-cloud/node-sdk#423]
Steps: Use this project with webpack and try to uglify code during production build step. 
See https://github.com/webpack-contrib/uglifyjs-webpack-plugin for webpack uglify details. 

Expected Behavior: Node projects written in ES6 syntax are usually compiled with Babel prior to being made available to the public so that there are not conflicts with browsers and servers that do not support ES6 syntax yet.  

Actual Behavior: frequent unconverted use of "let" (instead of ES5 compatible "var") prevents things like uglification from working properly.

Node Version: 6.10.0

SDK Version: 2.27.1

**Comment by nfriedly** [comment]
Hi @Cleanshooter 

This is something that you will need to address on your end, either by targeting newer environments or else by adding babel to your webpack flow. 

The IBM Watson Node.js SDK requires Node.js 4.x or newer, and has limited browser compatibility;  I do not anticipate these going backwards at this point.

I do think the webpack + babel flow could be helpful as a compliment to the existing webpack example, however. If you go that route, would you be willing to send a PR with webpack config to help other folks out?

**Comment by nfriedly** [comment]
Oh, and from your link, it looks like there is a branch of uglify-js that does support ES6:

> **Important!** The plugin has a peer dependency to uglify-js, so in order to use the plugin, also uglify-js has to be installed. The currently (2017/1/25) available uglify-js npm packages, however, do not support minification of ES6 code. In order to support ES6, an ES6-capable, a.k.a. harmony, version of UglifyJS has to be provided.
> 
> If your minification target is ES6:
> 
> ```bash
> yarn add git://github.com/mishoo/UglifyJS2#harmony --dev
> ```

https://github.com/webpack-contrib/uglifyjs-webpack-plugin#install

**Comment by Cleanshooter** [comment]
@nfriedly  Yeah I was aware of harmony but it hardly seemed reasonable to switch my target from es2015 because of one package... I thought about going one of two routes in my project:

1. Use axios to write the request directly to the endpoint, bypassing the need for this SDK.  I'm currently only using it for the NLC Create command.  I've already created axios versions for the NLC classify command and the tone analyzer (because I wanted them to execute simultaneously using axios.all).   But axios doesn't support sending formData from the server and after a while I gave up on trying... the format accepted for the NLC Create API is really picky and I couldn't figure out a way to do it that it would accept and all the documentation just points to this SDK... so dead end. 
2. Fork this library and compile it with babel myself.  clones... mods.. tests... fixes... and Done! now my build is able to uglify properly.  REPO here for example: https://github.com/Cleanshooter/node-sdk

**Comment by Cleanshooter** [comment]
@nfriedly your version comment confused me at first... realized I fat fingered the version when I first typed it in... updated original post.  (Sorry about that)

**Comment by nfriedly** [comment]
For some reason I was under the impression that babel included `node_modules` by default, but apparently that's not the case. However, it is pretty easy to turn it on, and not too much more work to write a filter that would apply it to a few specific modules but ignore the rest:

https://babeljs.io/docs/usage/babel-register/#usage-ignores-node-modules-by-default

I'd recommend that for short-term.

I'll also take a look at distributing things in ES5 syntax, but I'm not sure how soon it can be accomplished.

**Comment by Cleanshooter** [comment]
@nfriedly it's not too tough the link to my version should show you the basics. Hope it helps!

**Comment by ammardodin** [comment]
We're switching to TypeScript for the upcoming release, and we'll have ES5 compatibility.
