### ISSUE TITLE
[visual-recognition] Allow basicauth credentials for dedicated instances

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/node-sdk#426]
Visual Recognition dedicated uses basicauth instead of api_key -- the SDK should allow either.

**Comment by nfriedly** [comment]
Is this true for other services that use API keys (Alchemy)?

**Comment by jsstylos** [comment]
No, only Visual Recognition dedicated.

**Comment by nfriedly** [comment]
Ok, thanks. I'll get it fixed soon.

**Comment by jsstylos** [comment]
Sweet.

**Comment by nfriedly** [comment]
Should be released in v2.28.1 shortly
