### ISSUE TITLE
[conversation] environment vars and local vars are not handled gracefully

### ISSUE THREAD

**Issue by amirsobhi** [watson-developer-cloud/node-sdk#428]
Node version: 6.10.1
SDK version: watson-developer-cloud@2.28.1 

if environment variables for CONVERSATION_URL (PASSWORD, WORKSPACE_ID, etc) is defined and node app is run and if it sets app variables and then use those vars to start conversation, the error is generated that JSON is bad, and so on. It seems that the SDK does not gracefully handle existence of both environment variables and values provided during the call 
```js
// use the lconf credential components

var conversation = new watson.ConversationV1 ({
    username: lconf.username,
    password: lconf.password,
    path : { workspace_id :  lconf.workspace },
    version_date: watson.ConversationV1.VERSION_DATE_2017_02_03
})
```

The proper behaviour is:
1. if parameters are given on the call use them
2. if a parameter is missing, then use env var if given
3. if still having parameter missing, generate error / exception

**Comment by nfriedly** [comment]
The node.js SDK has built-in support for pulling credentials (username, password, and url) from environment properties, and should have [roughly the behavior you describe](https://github.com/watson-developer-cloud/node-sdk#usage). However, it does not currently have support for pulling `WORKSPACE_ID` out of the environment - perhaps that's what's causing trouble?

Also, in your example code, you're specifying username and password in the call, so they would never be pulled from the environment with that code, even if they're set to `null` or `''`. (`undefined` might work, but I wouldn't recommend it.)

Although, I don't see how any of that would lead to JSON errors... Can you give me a more complete  example (ideally, a [unit tests like this](https://github.com/watson-developer-cloud/node-sdk/blob/master/test/unit/test.visual_recognition.v3.js#L93)), and the exact error message?
