### ISSUE TITLE
The library should consider beta and GA to be different versions

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/node-sdk#43]
...and require "beta" (or "experimental") in the version to differentiate between them.

The services that are not GA and we will have to update are:

- [x] Question and Answer: v1-beta
- [ ] Message Resonance: (?)
- [x] Concept Expansion: v1-beta (?)
- [x] Relationship Extraction: v1-beta
- [x] Visual Insights: v1-experimental
- [x] Visual Recognition: v1-beta
- [x] Tone Analyzer: v1-experimental
- [x] Tone Analyzer: v2-experimental
- [x] Document Conversion: v1-experimental (already done in current release)

Also:  the test, examples, and readme, and docs will need to be updated, and example apps after v1.0 ships.

**Comment by germanattanasio** [comment]
Good idea. We will mock the future functionality :+1:

**Comment by nfriedly** [comment]
BTW, I'm doing this with one upcoming service - instead of `v1.js`, it's `beta-v1.js` (although I think I should rename that to `experimental-v1.js`)

**Comment by germanattanasio** [comment]
probably `v1-experimental.js`

**Comment by germanattanasio** [comment]
but that will require users to specify the version as `v1-experimental` while the service is adding experimental in the path.. kind of weird.

**Comment by jsstylos** [comment]
+1 for v1-experimental

**Comment by nfriedly** [comment]
@germanattanasio I think if the version is in the version number, then users won't need to specify the url any more - we can still allow it, but `v1-experimental.js` can have default to the experimental api url while `v1-beta.js` can have the beta url and so on.

**Comment by nfriedly** [comment]
we probably don't even need to document it anymore (although the authorization service uses it.. maybe we could just pass the service name and version to the auth service though..?)

**Comment by jsstylos** [comment]
Yeah, I think with beta/experimental in the version we eliminate most of the need for overriding the url, although we should leave that in. What do we do about existing beta/experimental services that we had published as "v1"? Do we make a breaking change to rename these v1-experimental, or wait for everything to age out?

**Comment by nfriedly** [comment]
yea, for the 1.0 release, I think that should probably be a breaking change

we can put in a check that detects it and throws a clear error message that says "change service foo v1 to v1-experimental" or whatever.

**Comment by germanattanasio** [comment]
I like that idea @nfriedly. 

The services that are not GA and we will have to update are:

- [ ] Question and Answer
- [ ] Message Resonance
- [ ] Concept Expansion (?)
- [ ] Relationship Extraction
- [ ] Visual Insights
- [ ] Visual Recognitions

**Comment by nfriedly** [comment]
Done, except for Message Resonance which I couldn't find listed on our website or in bluemix - is it deprecated?

Also, when the requested service version is not available, but a similar one with `-beta` or `-experimental` is, we now include "Did you mean v1-experimental" or whatever in the error message to aid users in updating their code.

**Comment by germanattanasio** [comment]
Message Resonance is gone so we can remove it.
![selfie-0](http://i.imgur.com/GT6QEUG.gif)

**Comment by germanattanasio** [comment]
Fixed by @nfriedly in the v1.0.0-beta release
