### ISSUE TITLE
[text-to-speech] calling synthesize() with wrong credentials doesn't raise an error

### ISSUE THREAD

**Issue by arlemi** [watson-developer-cloud/node-sdk#430]
Using the Node code provided in the API, if I call the synthesize method with wrong credentials this will not raise an error but instead pipe the JSON saying 401 wrong credentials to the creation of the audio file and therefore ending with a corrupted audio file. 

Let me know if you need more info to reproduce.

**Comment by germanattanasio** [comment]
You can add a catch to the pipe if you want to catch the error

**Comment by arlemi** [comment]
I did try like this:
```
text_to_speech.synthesize(params).on('error', function(err) {
		return res.status(500).send('Could not create an audio file from the provided text!')
	}).pipe(fs.createWriteStream('./public/uploads/' + timestamp + '-result.ogg').on('error', function(err) {
		console.log('error caught', err)
	}).on('finish', function() {
		res.send({timestamp: timestamp})
	}))
```

But the return from the api is still sent to the audio file. 
I also tried with `on('uncaughtException', ...` without any success.

Was that what you were saying? Or were you thinking of an other way to do it?

**Comment by arlemi** [comment]
Other endpoints are catching the wrong credentials error.
For now I'm making a (useless) call to getVoices() to check if the credentials are ok and if so then I'm calling synthesize().

**Comment by nfriedly** [comment]
If you pass in a callback as the second argument to synthesize(), it should be triggered with the error. I agree that this is a bit awkward, though, I'll see if I can make it behave better.

**Comment by arlemi** [comment]
Yep it works thanks, agree that it is a bit awkward...

**Comment by germanattanasio** [comment]
It's up to you nathan
