### ISSUE TITLE
[speech-to-text] interim_results: false in stream disables all results?

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/node-sdk#431]
With the default of `interim_results: true` in a Speech to Text stream I get final `data` events and interim and final `results` events. When setting `interim_results: false` I get no `data` or `results` events. Not sure what's going on here.

**Comment by manigurusankar10** [comment]
@jsstylos I tried setting the `interim_results: false` and I got `data`, `results`, and `close` event.

**Comment by jsstylos** [comment]
I think the issue here was a lack of clarity on the intended behavior of `interim_results`. I had assumed that `interim_results: false` would give me final results _for each utterance_, but it seems like it only gives final results for the entire input and so requires the audio stream to be finished before any results are returned. I'll try to check with the team that this is the desired behavior.

**Comment by jsstylos** [comment]
Talked to the service team: this is "by design" but an acknowledged source of confusion for users, so may get changed in a future version.
