### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by Waldo000000** [watson-developer-cloud/node-sdk#448]
Bundling TypeScript typings with this library would be very useful for developers who would like to use watson services in TypeScript applications. 

Is this something the watson team might take on? 

If not, the alternative is for the community to create typings and push to https://github.com/DefinitelyTyped/DefinitelyTyped to serve the typings via the `@types` organization (https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).

**Comment by germanattanasio** [comment]
We were talking about this yesterday. I don't have an ETA but we are going to work on this soon. We could see something in ~ 2 months.

**Comment by stevenmusumeche** [comment]
Any update on this?

**Comment by nfriedly** [comment]
Not really, things always take longer than we want them to :(

If you'd like to help with this, I'd be happy to accept a PR with the changes, especially if you can add some automated tests to ensure that future additions don't get merged in without typings. 99% of the methods in this lib have the same basic signature of `method(options, callback): ReadableStream` but the options are different for essentially every single one. 

Many of the methods have good JSDoc comments that define the options object, so in theory a tool could use those to create a decent TS definition to start with. I'm not familiar enough with TS tooling to know if that tool actually exists though :/

**Comment by germanattanasio** [comment]
@glennrfisher is working on this.

**Comment by vigneshmahalingam** [comment]
https://www.npmjs.com/package/@types/watson-developer-cloud

**Comment by stevenmusumeche** [comment]
@vigneshmahalingam is there an update? It says "Last updated: Tue, 02 May 2017 17:31:59 GMT"

**Comment by Naktibalda** [comment]
No updates since initial release: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/watson-developer-cloud/index.d.ts

**Comment by Naktibalda** [comment]
I made some updates https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20330

**Comment by germanattanasio** [comment]
@Waldo000000 @Naktibalda @stevenmusumeche  We have a beta release with typescript support
```
npm install watson-developer-cloud@beta
```

**Comment by glennrfisher** [comment]
@Waldo000000 @Naktibalda @stevenmusumeche It would be great to get your thoughts on the new TypeScript support, if you get a chance to check it out!

**Comment by nfriedly** [comment]
The PR with typescript is at https://github.com/watson-developer-cloud/node-sdk/pull/562

**Comment by Naktibalda** [comment]
I am not an expert of Typescript, but I skimmed Conversation file and I think that it looks good.

**Comment by glennrfisher** [comment]
Thanks, @Naktibalda. Appreciate you taking the time to look it over!

**Comment by Naktibalda** [comment]
Oh, you made a 3.0.0 release already.
I will try to use it soon.
