### ISSUE TITLE
[conversation] gateway does not support Germany region, only US 

### ISSUE THREAD

**Issue by lionelmace** [watson-developer-cloud/node-sdk#449]
If credentials are unspecified like in the code below, the SDK will fall back to the bluemix-provided VCAP_SERVICES environment property
```js
var conversation = new Conversation({
  // username: '<username>',
  // password: '<password>',
  // url: 'https://gateway.watsonplatform.net/conversation/api',
  version_date: '2017-04-21',
  version: 'v1'
});
```
That works fine if the app is deployed in the Bluemix Public us region. Yet, that does not work if the same app is deployed in the Frankurt region as the gateway url is different: ```https://gateway-fra.watsonplatform.net/conversation/api```

Yet, the credentials of the service has the correct url
```json
{
  "url": "https://gateway-fra.watsonplatform.net/conversation/api",
  "username": "xxxxx",
  "password": "xxxxx"
}
```

The SDK [conversation/v1.js](https://github.com/watson-developer-cloud/node-sdk/blob/master/conversation/v1.js) should pick the url from the VCAP credentials instead of using the hardcoded gateway of `https://gateway.watsonplatform.net/conversation/api`.
 
To reproduce:
1. Create a Watson Conversation service in Bluemix Public in Germany.
2. Get the app https://github.com/watson-developer-cloud/conversation-simple
3. Comment the line 35 of app.js `url: 'https://gateway.watsonplatform.net/conversation/api'`
4. Update the manifest.yml
5. Push the app to Frankfurt.

**Comment by germanattanasio** [comment]
Can you share the `VCAP_SERVICES` value? Please hide the credentials

**Comment by lionelmace** [comment]
@germanattanasio below is the `VCAP_SERVICES` of the CloudFoundry app binding the Watson Conversation service:
```
{
    "conversation": [
        {
            "credentials": {
                "url": "https://gateway-fra.watsonplatform.net/conversation/api",
                "username": "xxxxxxxxxxx",
                "password": "xxxxxxxxxxx"
            },
            "syslog_drain_url": null,
            "label": "conversation",
            "provider": null,
            "plan": "free",
            "name": "watson-conversation-de-20170327",
            "tags": [
                "watson",
                "ibm_created",
                "ibm_dedicated_public"
            ]
        }
    ]
}
```

**Comment by germanattanasio** [comment]
Are you specifying the credentials with the environment variables
`CONVERSATION_USERNAME` or `CONVERSATION_PASSWORD` ?

**Comment by lionelmace** [comment]
@germanattanasio I'm not harcoding them since the app will pick them up automatically from the VCAP.

**Comment by nfriedly** [comment]
I'm not sure what the issue is exactly, but I don't think it's a bug in the SDK.  It uses [vcap_services]](https://www.npmjs.com/package/vcap_services) to pull the bluemix credentials, which includes the url.  

Using the credentials that were in the top of the issue (I have since removed them), I get this error:

```json
{
  "code": 401,
  "error": "Not Authorized",
  "description": "2017-05-09T14:27:39Z, Error ERCDPLTFRM-DNLKUPERR occurred when accessing https://gateway-fra.watsonplatform.net/conversation/api/v1/workspaces/%3Cworkspace_id%3E/message?version=2017-04-21, Tran-Id: gateway-fra-dp01-4826701 - Invalid UserId and/or Password. Please confirm that your credentials match the end-point you are trying to access. A common error is trying to use credentials from an experimental or beta release against a GA release or vice versa"
}
```

That was the same whether I hard-coded the URL or let it pull from the VCAP_SERVICES environment property, and message shows that it's using the correct URL.

Is that still the credentials set you are trying to use (username b2b5f64b-...)? Is that the same error message that you are getting?

**Comment by nfriedly** [comment]
I just sent a PR to the demo to remove the hard-coded URL and clean up a couple of other things: https://github.com/watson-developer-cloud/conversation-simple/pull/119

**Comment by lionelmace** [comment]
@germanattanasio I updated the watson sdk and removed the url. I was able to deploy it successfully in Germany without the URL. The vcap_services was picked up fine.
