### ISSUE TITLE
Alchemy API Key

### ISSUE THREAD

**Issue by dosberg** [watson-developer-cloud/node-sdk#451]
It appears that new Alchemy API Key's are not being issued? How do I use Alchemy services?

```
var alchemy_language = new AlchemyLanguageV1({
  api_key: 'API_KEY'
});
```

**Comment by germanattanasio** [comment]
Alchemy was deprecated. You need to use [Natural Language Understanding](https://www.ibm.com/watson/developercloud/natural-language-understanding.html) as the replacement.
