### ISSUE TITLE
Cannot make api call from node app : personality trait(twitter)

### ISSUE THREAD

**Issue by suhail339** [watson-developer-cloud/node-sdk#452]
error: 'Not Authorized',
  description: '2017-05-15T07:32:58-04:00, Error ERCDPLTFRM-DNLKUPERR occurred when accessing https://158.85.132.88:443/personality-insight
s/api/v3/profile?version=2016-10-19&amp;consumption_preferences=true, Tran-Id: gateway-dp02-1006542948 - Invalid UserId and/or Password. Pl
ease confirm that your credentials match the end-point you are trying to access. A common error is trying to use credentials from an experi
mental or beta release against a GA release or vice versa' }

**Comment by nfriedly** [comment]
I think it says the problem right there in your message: Invalid UserId and/or Password. Note that this is *not* the username/password you use to sign into bluemix, but rather a randomly generated one that was created for your instance of the personality insights service. See https://www.ibm.com/watson/developercloud/doc/common/index.html#get-service-credentials
