### ISSUE TITLE
[Conversation] React Native issues, modules missing?

### ISSUE THREAD

**Issue by FMGordillo** [watson-developer-cloud/node-sdk#453]
### When reporting a bug, please be sure to include the following:  
I installed with npm the `watson-developer-cloud`, then I put it on my module ChatScreen the following:

`const ConversationV1 = require('watson-developer-cloud/conversation/v1');`
`var conversation = new ConversationV1({`
`    username: CHAT_USERNAME,`
`     password: CHAT_PW,`
`     version_date: ConversationV1.VERSION_DATE_2017_04_21`
` });`

And when a user clicks a button (using `react-native-gifted-chat`), it exectues a fuction, similar to the one in the example. 

`        conversation.message({`
`            input: {messages},`
`            workspace_id: 'df165f57-6337-4282-a078-155b72e63eb1'`
`        }, (err, response) => {`
 `           if(err) {`
 `               alert(err);`
`            } else {`
`                alert(JSON.stringify(response, null, 2));`
`            }});`

Then, in the moment I compile using `react-native run-android`, I got an unexpected error, of a module missing (`utils`), from the v1.js file. So, I've installed manually, just to workaround the issue. Then, another dependency, `stream`. Also, I've installed (always using npm), and again another dependency.

This time it was `crypto`, but it stayed there. I've reseted the cache, deleted node_modules and reinstalled everything, and still getting the same issue with crypto.

My package.json
`"react": "16.0.0-alpha.6",`
`"react-native": "0.44.0",`
...

Node version: 7.10.0
SDK version: V1

**Comment by germanattanasio** [comment]
I don't think we support `react-native`. There is an open issue related to this already #315

**Comment by pwcremin** [comment]
I just added Conversation to my react-native-watson module: 

https://www.npmjs.com/package/react-native-watson

**Comment by bgbraga** [comment]
Closed with no support?

**Comment by anweshan** [comment]
@bcbraga see comment from pwcremin

**Comment by bgbraga** [comment]
@anweshan it is not the official solution.
