### ISSUE TITLE
Remote Memory Exposure Vulnerability

### ISSUE THREAD

**Issue by aartiles** [watson-developer-cloud/node-sdk#456]
You are using a version of `solr-client` (v0.6.0) that is using a vulnerable version of `request`. 

## How to fix
Upgrade request to version 2.68.0 or higher. Note that versions 2.47.0-2.51.0 are not vulnerable due to a node level error that occurs when a number is passed as the body.
Upgrading to `solr-client` to v0.6.1 (not published on npm yet) should solve it

More info: https://nodesecurity.io/advisories/309

**Comment by nfriedly** [comment]
Hi @aartiles,

Thanks for reminding me about this. 

I reviewed our usage a while back and concluded that it was not vulnerable to this, but nonetheless submitted a [PR](https://github.com/lbdremy/solr-node-client/pull/200) to solr-client. 

Now that it's been merged and released in solr-client v0.7.0, I'm updating the SDK to use that.  It should be released by CI shortly.

**Comment by aartiles** [comment]
Brilliant, thanks!
