### ISSUE TITLE
Name not being passed into discovery.createCollection(

### ISSUE THREAD

**Issue by chughts** [watson-developer-cloud/node-sdk#457]
If this is a usage problem, then let me know and I will post a question in the appropriate forum, but I have had a look and I think that its a problem with the SDK. 

The discovery.createCollection builds the body for the underlying REST API as
`          body: JSON.stringify(pick(params, ['collection_name', 'description', 'configuration_id', 'language_code']))`

but the API is expecting a body of 
```
{
  "name": "{collection_name}",
  "description": "{description}",
  "configuration_id": "{configuration_id}"
}
```

which means that `name` is never getting set. So every time I try to invoke the method through the SDK I get 

> "Invalid or missing collection name, name is a required parameter"

**Comment by nfriedly** [comment]
I suspect you're right, can you send a PR with the change and a test?

**Comment by chughts** [comment]
Yes I can. I would propose the change to

`body: JSON.stringify(pick(params, ['name', 'description', 'configuration_id', 'language_code']))`

would that be OK ?

**Comment by nfriedly** [comment]
Yep. Make sure the JSDoc is also updated
