### ISSUE TITLE
[Discovery] createEnvironment size 0 not supported

### ISSUE THREAD

**Issue by alex-thewsey-ibm** [watson-developer-cloud/node-sdk#461]
As currently documented for [API v1](https://www.ibm.com/watson/developercloud/discovery/api/v1/#create_environment), environment size 0 should create a free trial environment where available.

However, argument defaulting in discovery/v1.js `DiscoveryV1.prototype.createEnvironment` does not account for the fact that zero is falsy:

```
// size is an int of 1,2,3, default 1
if (!params.size) {
    params.size = 1;
}
```

Therefore when I try to create a trial environment through the Node SDK, the size spec is coerced to 1 and I get the error message "Creating environment of size: 1 is not allowed in your plan".

Therefore suggest using a more specific check like:
```
if (typeof params.size === "undefined" || params.size === null) {
    params.size = 1;
}
```

**Comment by nfriedly** [comment]
Yep, I think you're right. Can you send a Pull Request with a unit test and your fix?

**Comment by alex-thewsey-ibm** [comment]
Pull request #463 opened
