### ISSUE TITLE
[Discovery] [Documentation] [NodeJS]

### ISSUE THREAD

**Issue by marc-mclean1** [watson-developer-cloud/node-sdk#462]
There is a documentation bug for NodeJS example [Add a document](https://www.ibm.com/watson/developercloud/discovery/api/v1/?node#add-doc).

It has nested parenthesis:
```javascript
discovery.addDocument(('{environment_id}', '{collection_id}', file),
function(error, data) {
  console.log(JSON.stringify(data, null, 2));
});
```
It should be a nested JSON object:
```javascript
discovery.addDocument({ environment_id:environment_id, collection_id:collection_id, file:file },
function(error, data) {
  console.log(JSON.stringify(data, null, 2));
});
```

**Comment by nfriedly** [comment]
Doh, yep. Can you send a PR with the fix?

**Comment by marc-mclean1** [comment]
@nfriedly - I think this is autogenerated documentation - not sure how/where to fix directly.  Could you show me for future reference?

**Comment by germanattanasio** [comment]
That code is not open source @marc-mclean1 I will talk to the documentation team and let them know

**Comment by nfriedly** [comment]
Oh, right, sorry about that.

**Comment by evenfrost** [comment]
@germanattanasio Any idea when it will be fixed? The documentation for Discovery is invalid in every endpoint, e.g.:
```js
discovery.getCollections(('{environment_id}'), function(error, data) {
  console.log(JSON.stringify(data, null, 2));
});
```
Was fighting the `Missing required parameters: environment_id` for plenty of time until found this issue.

**Comment by ammardodin** [comment]
I've submitted a PR to fix this in the api ref. The changes should be reflected shortly.
