### ISSUE TITLE
[Tone Analyzer] The tone_chat() utterances parameter is required

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/node-sdk#467]
The Node.js documentation for the Tone Analyzer `tone_chat()` method states that the `utterances` parameter is optional, but it's actually required.

`utterances  string  <optional>  The utterances to analyze. Utterances must be a JSON object.`

Small but kind of important correction.

**Comment by germanattanasio** [comment]
@jeffpk62 can you write  PR for this?

**Comment by jeffpk62** [comment]
Sure, @germanattanasio, I'll try to get to in the next day or two.

**Comment by ammardodin** [comment]
This has already been fixed in the current SDK and will be included in the upcoming release. Closing.
