### ISSUE TITLE
Discovery Node SDK - Query method wrong parameter definition

### ISSUE THREAD

**Issue by lgbaeza** [watson-developer-cloud/node-sdk#469]
https://www.ibm.com/watson/developercloud/discovery/api/v1/?node#query-collection

At the page above, the method for query has a wrong definition of the parameters, instead of:
discovery.query(('{environment_id}', '{collection_id}', '{query_string}'), ...)

should be 
discovery.query({'{environment_id}', '{collection_id}', '{query_string}'}, ...)

because according to SDK doc found at https://github.com/watson-developer-cloud/node-sdk/blob/master/discovery/v1.js line 457, the method receives a parameter object "{}"

**Comment by nfriedly** [comment]
Yep, good catch.

@SirSpidey Can you handle / delegate this one?

**Comment by SirSpidey** [comment]
@lgbaeza @nfriedly: Got it. Have created an issue against our internal repo

**Comment by SirSpidey** [comment]
Closing this because it's not an SDK issue. Luis, ping me if you want the internal issue
