### ISSUE TITLE
URL Parameter [speech-to-text] 

### ISSUE THREAD

**Issue by hkgian** [watson-developer-cloud/node-sdk#470]
Doing a conversation with a customer today, we found out that the URL for Watson Speech-to-text service deployed in Frakfurt is different, which brakes compatibility with the Frakfurt datacenter for this service. 
## To recreate: 
- create a watson service in the Frankfurt region.
- try to use this npm package to connect to the services
- you will receive a 401 error (the Watson endpoint is different for the frankfurt region and so url and credential don't match, hence the 401) 

### Suggestion: 
My idea would be to hide this complexity to the developer, and provide an optional parameter to select the location of the service, using a standard format.
Internally keep track of this relation using an array with services url for each reagion for each service

**Comment by chughts** [comment]
There already is an option parameter - url 

Eg.

    ```
var lt = new LanguageTranslatorV2({
      username: username,
      password: password,
      version: 'v2',
      url: endpoint
    });
```
