### ISSUE TITLE
[visual-recognition] Documentation issue for Visual Recognition API

### ISSUE THREAD

**Issue by cfjedimaster** [watson-developer-cloud/node-sdk#471]
While looking at the documentation for VR usage, which I believe is only in the main readme, I noticed it doesn't provide a full listing of the methods you can use, specifically I do not see detectFaces() documented.

**Comment by nfriedly** [comment]
Sorry, the readme is intended to be a quick intro to every service, but not the primary documentation.  The main docs are at https://www.ibm.com/watson/developercloud/visual-recognition/api/v3/?node#detect_faces and then there are also auto-generated docs at http://watson-developer-cloud.github.io/node-sdk/master/VisualRecognitionV3.html#detectFaces

**Comment by cfjedimaster** [comment]
Ah - does the github readme here link to this? I swear I looked and couldn't find it.

**Comment by nfriedly** [comment]
No, and I'm going to remedy that right now.
