### ISSUE TITLE
[discovery] Missing method to get document / "list document details"

### ISSUE THREAD

**Issue by alex-thewsey-ibm** [watson-developer-cloud/node-sdk#472]
Discovery API V1 docs describe a method they refer to as [List Document Details](https://www.ibm.com/watson/developercloud/discovery/api/v1/#get-doc) (which I might prefer to see described as getDocument or getDocumentDetails): `GET /v1/environments/{environment_id}/collections/{collection_id}/documents/{document_id}`

Current master [discovery/v1.js](https://github.com/watson-developer-cloud/node-sdk/commit/1044b6c06458bbefc03582757d263372af3d8fc5) seems to offer no such method, unless I'm missing something obvious...

If the method should be added, I could probably start work on a pull request? Opinions welcome on method name etc.

**Comment by nfriedly** [comment]
I see what you're saying about list vs get - @SirSpidey is that something we should change?

I think `getDocumentDetails()`, is probably a good name if you want to add a PR with it.

**Comment by SirSpidey** [comment]
@nfriedly If you the method gets added, please let me know so we can update the API reference.

@alex-thewsey-ibm I understand the preference for the `VERB endpoint` label over the "friendly" name. We chose the latter because it's not REST/SDK specific. I'll note your feedback.

**Comment by nfriedly** [comment]
Thanks!

@alex-thewsey-ibm: I just added some notes to https://github.com/watson-developer-cloud/node-sdk/blob/master/.github/CONTRIBUTING.md#tests on how to set up the integration tests, since it's kind of confusing right now.

**Comment by ammardodin** [comment]
This has been added to current SDK already and will be included in the upcoming release. Closing.
