### ISSUE TITLE
STT/TTS update 7/14

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/node-sdk#479]
From @jeffpk62:

> TTS
> 
>  * Now supports `audio/mp3` and `audio/mpeg` for all methods that accept an audio format.
> 
> 
> STT
> 
>   *  Now supports `audio/mp3` and `audio/mpeg` for all methods that accept an audio format.
> 
>   * The model names `en-UK_BroadbandModel` and `en-UK_NarrowbandModel` are now deprecated.  They are still functional for backward-compatibility, just not recommended and not returned with the `GET /v1/models` method.  Users can still see details about the models with the `GET /v1/models/{model_id}` method.
> 
> *  The new UK model names are `en-GB_BroadbandModel` and `en-GB_NarrowbandModel`.  These are fully supported and returned by both the `GET /v1/models` and `GET /v1/models/{model_id}` methods.
> 
>  * Language model customization now supports `es-ES_BroadbandModel` and `es-ES_NarrowbandModel`.
> 
>   * Custom language models now have a new field:  `dialect`.  For `en-US` and `ja-JP` models, this will always match the name of the language (`en-US` or `ja-JP`).  For `es-ES` models, this will be `es-ES` by default but can also be `es-LA` or  `es-US` if specified by the user.
> 
>   * The new `dialect` field is optionally specified with the `CustomModel` object that is passed as part of the `POST /v1/customizations` method and is always returned as part of the `Customization` object by the `GET /v1/customizations` and `GET /v1/customizations/{customization_id}` methods.
> 

I believe that the only code change necessary is to enable the `dialect` field. The others may need doc changes, though, and it wouldn't be a bad idea to provide constants for the various supported formats.

**Comment by jeffpk62** [comment]
In addition to the dialect field, which may have a broader impact, I think the only changes are for the Java SDK, where audio and language model constants are used in a few places.  They aren't used exclusively, but they need to be addressed where they are used.  I think these changes are fairly transparent for Node and Python.
