### ISSUE TITLE
[Conversation] When I update or create wcs workspace using node js library, jump_to link is disappeared.

### ISSUE THREAD

**Issue by blbird** [watson-developer-cloud/node-sdk#485]
1. Node Version : 6.10.0
2. SDK Version : 2.34.0
3. Step to reproduce.
 1) In case of updating wcs workspace (updateWorkspace())
 - Unzip the attached file. 
 - Import conversation.json to WCS. You can see the jump_to links such like below image.
<img width="557" alt="screen shot 2017-07-26 at 6 42 34 pm" src="https://user-images.githubusercontent.com/6425614/28614881-3cbf4306-7232-11e7-9f05-502d5a03f1d8.png">

  - Run 'node loadwcs <id for wcs> <password for wcs>' after 'npm install'. loadwcs.js read the conversation.json file and updating workspace which has same name by using updateWorkspace().
  - You can see the jump_to links are disappeared after refreshing your workspace.
 
 2) in case of creating workspace (createWorkspace())
 - Delete your workspace.
 - Run 'node loadwcs <id for wcs> <password for wcs>' after 'npm install'. loadwcs.js create new workspace by using createWorkspace().
 - You can see also the jump_to links are disappeared after refreshing your workspace. 

[loadwcs.zip](https://github.com/watson-developer-cloud/node-sdk/files/1176125/loadwcs.zip)

**Comment by nfriedly** [comment]
This can happen when you export with one API version_date but import with another later version. You should re-import with the same API version_date used to export.

(The team is aware that this is a bit awkward and actually has a fix in place that should be released soon. But, in the meanwhile, the above should work for you.)
