### ISSUE TITLE
ERROR - speech-to-text

### ISSUE THREAD

**Issue by EduardoMoraesRitter** [watson-developer-cloud/node-sdk#488]
eu galera eu utilizo a alguns meses o speech-to-text de vcs com o node e parou de funcionar de repente ja criar um novo usuário e novas credencias, ate mesmo outro projeto ate agora todos os áudio q envio para o watson e fica com status pra sempre como "waiting".

**Comment by nfriedly** [comment]
_Google Tradutor:_

Não tenho certeza, mas não acredito que seja um erro de SDK. Você pode tentar perguntar em https://developer.ibm.com/answers/questions/ask/?topics=watson ou http://stackoverflow.com/questions/ask?tags=ibm-watson-cognitive

Eu vou fechar esse bilhete por enquanto, mas se ele provar ser um erro SDK, sinta-se livre para abri-lo novamente com mais detalhes.

------

_Original English:_

I'm not certain, but I don't believe that's an SDK bug. Can you try asking at https://developer.ibm.com/answers/questions/ask/?topics=watson or http://stackoverflow.com/questions/ask?tags=ibm-watson-cognitive

I'm going to close this ticket for now, but if it does prove to be an SDK bug, feel free to re-open it with more details.

**Comment by EduardoMoraesRitter** [comment]
Obrigado, ja voltou a funciona, mais não modifiquei nada ficou instável por 4 dias.
