### ISSUE TITLE
Suport for in-memory JSON documents is not working

### ISSUE THREAD

**Issue by haroldo-ok** [watson-developer-cloud/node-sdk#489]
Hello, 

I'm trying to index a JSON document, but it simply isn't working; so far, I have tried the solutions posted in https://developer.ibm.com/answers/questions/361808/adding-a-json-document-to-a-discovery-collection-u/ , but it simply does not work;

If I try:

		discovery.addDocument({
			environment_id: config.watson.environment_id,
			collection_id: config.watson.collection_id,
			file: JSON.stringify({
				"ocorrencia_id": 9001
			})
		}, (error, data) => {
			if (error) {
				console.error(error);
				return;
			}

			console.log(data);
		});

It returns me this error: 

		The Media Type [text/plain] of the input document is not supported. Auto correction was attempted, but the auto detected media type [text/plain] is also not supported. Supported Media Types are: application/json, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/pdf, text/html, application/xhtml+xml .

On the other hand, if I try:

		discovery.addDocument({
			environment_id: config.watson.environment_id,
			collection_id: config.watson.collection_id,
			file: JSON.parse(JSON.stringify({
				"ocorrencia_id": 9001
			}))
		}, (error, data) => {
			if (error) {
				console.error(error);
				return;
			}

			console.log(data);
		});

I get this error:

	TypeError: source.on is not a function
		at Function.DelayedStream.create (C:\Temp\teste-watson\watson-orchestrator\node_modules\delayed-stream\lib\delayed_stream.js:33:10)
		at FormData.CombinedStream.append (C:\Temp\teste-watson\watson-orchestrator\node_modules\combined-stream\lib\combined_stream.js:43:37)
		at FormData.append (C:\Temp\teste-watson\watson-orchestrator\node_modules\form-data\lib\form_data.js:68:3)
		at appendFormValue (C:\Temp\teste-watson\watson-orchestrator\node_modules\request\request.js:324:21)
		at Request.init (C:\Temp\teste-watson\watson-orchestrator\node_modules\request\request.js:337:11)
		at new Request (C:\Temp\teste-watson\watson-orchestrator\node_modules\request\request.js:130:8)
		at request (C:\Temp\teste-watson\watson-orchestrator\node_modules\request\index.js:54:10)
		at createRequest (C:\Temp\teste-watson\watson-orchestrator\node_modules\watson-developer-cloud\lib\requestwrapper.js:177:10)
		at DiscoveryV1.addDocument (C:\Temp\teste-watson\watson-orchestrator\node_modules\watson-developer-cloud\discovery\v1.js:516:10)
		at client.query.then.res (C:\Temp\teste-watson\watson-orchestrator\populate\populate.js:36:13)
		at process._tickCallback (internal/process/next_tick.js:109:7)
		

Similarly, by saving to a temp file, and then using it:
		
		const tempy = require('tempy');
		const f = tempy.file({extension: 'json'});
		fs.writeFileSync(f, JSON.stringify({
				"ocorrencia_id": 9001
		}));
				
		discovery.addDocument({
			environment_id: config.watson.environment_id,
			collection_id: config.watson.collection_id,
			file: fs.readFileSync(f)
		}, (error, data) => {
			if (error) {
				console.error(error);
				return;
			}

			console.log(data);
		});

Then this happens:

	The Media Type [application/octet-stream] of the input document is not supported. Auto correction was attempted, but the auto detected media type [text/plain] is also not supported. Supported Media Types are: application/json, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/pdf, text/html, application/xhtml+xml .
	
Considering other posts recommend using JSON.parse(), it seems that the API accepts a JS object, but none of the examples, and nothing that I have tried so far seems to be working. Seems to be a bug?

**Comment by nfriedly** [comment]
The service checks filename and then content to determine type, but doesn't seem to recognize JSON as JSON - it just sees text. And, since it was in-memory, there's no filename (ditto for Buffers from `fs.readFileSync()`; `fs.createReadStream()` would have worked there though). 

It's possible to "fake" a .json filename, but we added [`.addJsonDocument()`](http://watson-developer-cloud.github.io/node-sdk/v2.37.0/DiscoveryV1.html#addJsonDocument) and [`.updateJsonDocument()`](http://watson-developer-cloud.github.io/node-sdk/v2.37.0/DiscoveryV1.html#updateJsonDocument) methods to make it just work without needing hacks. Try this out (make sure you're on a fairly up-to-date version of the SDK):

```js
	discovery.addJsonDocument({
		environment_id: config.watson.environment_id,
		collection_id: config.watson.collection_id,

		// note: no JSON.stringify needed with addJsonDocument()
		file: { 
			"ocorrencia_id": 9001
		}
	}, (error, data) => {
		if (error) {
			console.error(error);
			return;
		}

		console.log(data);
	});
```

And, man, that developerWorks question is a mess. I'm going to post this answer there also.

**Comment by haroldo-ok** [comment]
For the record, thanks to someone on StackOverflow, I finally managed to make it work:

	discovery.addDocument({			
		environment_id: config.watson.environment_id,
		collection_id: config.watson.collection_id,
		file: {
			value: JSON.stringify(doc),
			options: {
				filename: 'ocorrencia_' + doc.ocorrencia_id + '.json',
				contentType: 'application/json; charset=utf-8'
			}
		}
	}, (error, data) => {
		if (error) {
			console.error(error);
			return;
		}
		console.log(data);
	});


[post on StackOverflow](https://stackoverflow.com/a/45677829/679240); somehow, I failed to find this on the documentation (well, I still can't find it... :P).

**Comment by nfriedly** [comment]
Yea, that works too. It's basically what the .addJsonDocument method does.
