### ISSUE TITLE
[Text to speec] : Problem running the example code

### ISSUE THREAD

**Issue by RoshanRIshav** [watson-developer-cloud/node-sdk#493]
I am fairly new to programming so I might be doing something wrong here, but my issue is when I am trying to use the text to speech example code (with my credentials), and then trying to play the .wav file, it shows that the .wav file has a duration of 00:00. Itll be great if anyone could help me out.

**Comment by germanattanasio** [comment]
`.WAV` stores the file length in the first 80 bytes and the service doesn't know the file size until it finishes synthesizing the text. You will be able to reproduce the audio but the duration won't be known until the service finishes synthesizing the text. 

Try using a different format like mp3.
