### ISSUE TITLE
Update conversation_tone_analyzer_integration/tone_detection.js to be consistent with Tone Analyzer API v4

### ISSUE THREAD

**Issue by aprilwebster** [watson-developer-cloud/node-sdk#494]
Tone Analyzer v4 is removing social and language tones. Demo needs to be updated accordingly.
https://github.ibm.com/people-insights/tone-analyzer/issues/798

**Comment by aprilwebster** [comment]
@jsstylos - suggestions re backwards compatibility?

**Comment by jsstylos** [comment]
The example at https://github.com/watson-developer-cloud/node-sdk/blob/master/examples/conversation_tone_analyzer_integration/tone_detection.js should be updated to use the new version (removing social and language tones). We shouldn't have to do anything else for backward compatibility in the example

**Comment by aprilwebster** [comment]
@jsstylos - thanks!

**Comment by germanattanasio** [comment]
@aprilwebster we just pushed 3.0.1 please update your fork and fix your example based on the latest changes. Please use es5
