### ISSUE TITLE
Unable to call watson conversation api behind corporate proxy

### ISSUE THREAD

**Issue by iamkulo** [watson-developer-cloud/node-sdk#498]
I have similar issue reported already by another user . I am developing a nodejs app that calls watson conversation api.  Since my nodeapp runs behind proxy server, its not able to call watson api. There is no mechanism to specify proxy server to the request wrapper used in the watson-cloud-developer node module. I tried setting setting http proxy via npm, still it didn't resolve the issue.  Can this be fixed?

https://developer.ibm.com/answers/questions/337990/nodejs-cannot-call-watson-document-conversion-serv/

**Comment by nfriedly** [comment]
I think the npm setting only applies to downloading and installing modules. This library uses `request` under the hood for most things, and request allows configuring proxies via environment properties: https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables.

In bash, the command would look something like this:

```sh
HTTPS_PROXY="https://your-proxy-server" node your-script.js
```

I think that will work for your use-case (?)

**Comment by iamkulo** [comment]
Yes. It worked now. i didn't notice underscore (http_proxy) as npm use (-hypen).
