### ISSUE TITLE
[Visual Recogntion] is that possible to have multi-language support for face detect?

### ISSUE THREAD

**Issue by TitiHl** [watson-developer-cloud/node-sdk#499]
Hi,

For Visual Recogntion, we can pass Accept-language to SDK params to have multi-language support when calling image **classify**, wondering is that possible to have this support for **detect_faces** endpoint as well.

Thanks,
Alex

**Comment by nfriedly** [comment]
I don't believe the service supports that, although I can pass this along to the team. I'm not sure I see the need though - what part of the response would you expect to be translated?

**Comment by TitiHl** [comment]
I guess is the gender, not sure how Watson response the identity(name) of a Japanese/Korean person, never seeing Watson successfully recognized a Asian person yet.

**Comment by TitiHl** [comment]
I guess is the gender, not sure how Watson response the identity(name) of a Japanese/Korean person, never seeing Watson successfully recognized a Asian person yet.

**Comment by nfriedly** [comment]
OK. I passed your request along to the team, they're taking it under consideration.
