### ISSUE TITLE
[discovery] passage extraction parameters not supported

### ISSUE THREAD

**Issue by don-tjandra** [watson-developer-cloud/node-sdk#500]
Following passage extraction parameters have no effect with current version of SDK.

```
queryParams['passages.fields'] = 'description,text';
queryParams['passages.characters'] = 2000;
queryParams['passages.count'] = 15;
```

When DIscovery url is called directly using curl or similar tool with these parameters the passages are extracted correctly. Is there a timeline for adding the parameters to the SDK?

**Comment by nfriedly** [comment]
Hi @don-tjandra,

Thanks for the report; can you send a pull request that adds in the missing params? I can get that merged and released fairly quickly.

**Comment by ruchiranet1** [comment]
This is worked properly with HTTP calls, but not working properly with node.js SDK. 
        params.natural_language_query= 'My questions'
        params.count = 2;
        params.passages = true;
       // params.passages.fields ="Body";
        params.passages.count=1;

 discovery.query(params, function (error, response) {

It supposed to send one passage only, but it is returning more than 1 passages from different documents.

**Comment by don-tjandra** [comment]
Passage parameters should be literal strings in node.js not json fields. This worked for me.

```
var params = {
    query: 'apples',
    passages: true
  };

  params['passages.fields'] = 'description,text';
  params['passages.count'] = 1;
  params['passages.characters'] = 2000;
```

**Comment by arilishu** [comment]
Is there any update about this?
Based on @don-tjandra , i couldn´t make it works!
This is my code.
Is there something wrong?
var query_options = {
    'natural_language_query': text,
    'passages': true,
  };
  query_options['passages.fields'] = 'description,text';
  query_options['passages.count'] = 1;
  query_options['passages.characters'] = 2000;
discovery.query({ environment_id: 'XXXX', collection_id: 'XXXX', query: query_options }, function(error, data) {

**Comment by ammardodin** [comment]
@arilishu Can you try thre following

```javascript
var query_options = {
  natural_language_query: text,
  passages: true,
  environment_id: 'XXXX',
  collection_id: 'XXXX',
};

query_options['passages.fields'] = 'description,text';
query_options['passages.count'] = 1;
query_options['passages.characters'] = 2000;

discovery.query(query_options, function(err,res) {
  if (err) {
    console.log(err);
  } else {
    console.log(res);
  }
}
```
