### ISSUE TITLE
security advisory: vulnerability in dependency "string"

### ISSUE THREAD

**Issue by boneskull** [watson-developer-cloud/node-sdk#502]
References:

- [Snyk](https://snyk.io/vuln/npm:string:20170907)
- [NSP](https://nodesecurity.io/advisories/536)

as of this writing, there are no fixes.

My recommendation is to drop the dependency (it's only used [here](https://github.com/watson-developer-cloud/node-sdk/blob/1557aca4a2378fab120a4684ac4b5305142155a4/lib/requestwrapper.js#L42)) and use a ES6 template string or something else.

**Comment by nfriedly** [comment]
Yea, I think you're right. Thanks for reporting it!

Is the fix something you'd be up to doing and sending a PR for?

**Comment by boneskull** [comment]
sure
