### ISSUE TITLE
continuous security checks

### ISSUE THREAD

**Issue by boneskull** [watson-developer-cloud/node-sdk#503]
To avoid stuff like #502 happening again, this project should consume [nsp](https://npm.im/nsp) or a similar service.

[Snyk](https://snyk.io) provides a service and GitHub integration which automates the process of fixing these issues.

**Comment by nfriedly** [comment]
We have NSP set up to check Pull Requests, I just added Snyk and set it to check daily. Neither are currently reporting anything, although it looks like you found a couple of others (?)
