### ISSUE TITLE
security advisory: ReDoS vulnerability in debug

### ISSUE THREAD

**Issue by boneskull** [watson-developer-cloud/node-sdk#505]
See https://nodesecurity.io/advisories/534   

The fix is to upgrade `websocket`.

**Comment by nfriedly** [comment]
There doesn't appear to be a new release of `websocket` out yet - is there a ticket or PR on https://github.com/theturtle32/WebSocket-Node for that yet?

**Comment by boneskull** [comment]
This is what NSP is telling me

![image](https://user-images.githubusercontent.com/924465/30992006-7687aa90-a45c-11e7-92f6-c2ec89101b3f.png)

**Comment by boneskull** [comment]
if `websocket` has a fuzzy range, an `npm upgrade` might work, let me try it..

**Comment by boneskull** [comment]
still there. may not yet be actionable.
