### ISSUE TITLE
[Conversation] Dialog node actions are missing in SDK

### ISSUE THREAD

**Issue by Naktibalda** [watson-developer-cloud/node-sdk#510]
Dialog node actions are documented at https://www.ibm.com/watson/developercloud/conversation/api/v1/?curl#dialog_nodes
but they are missing in https://github.com/watson-developer-cloud/node-sdk/blob/master/conversation/v1.js

Is there a reason for that?

**Comment by nfriedly** [comment]
No, sorry, we just haven't gotten to it yet. Would you like to send a PR with the additions? I can get it released pretty quickly if you do.

**Comment by Naktibalda** [comment]
Thanks, it was the quickest release ever.
