### ISSUE TITLE
[Discovery] CreateCollection expects language to be specified as language and not language_code

### ISSUE THREAD

**Issue by chughts** [watson-developer-cloud/node-sdk#512]
As per this question on DeveloperWorks Answers - https://developer.ibm.com/answers/questions/404970/unable-to-create-non-english-discovery-collection/

The CreateCollection method in the SDK (version 2.40.0) is expecting the language to be specified as language_code. If not provided it sets the `language_code` to 'en'. The API method is actually expecting the collection language to be specified as `language`. 

I have tried to specify both, and set to 'de', but the method invocation with the SDK always creates an English Collection. 

I think the fix would be to line 356

          `body: JSON.stringify(pick(params, ['name', 'description', 'configuration_id', 'language_code']))`

to pick language only or both language and language_code

**Comment by nfriedly** [comment]
Thanks, do you have time to send me a PR with the fix?

**Comment by chughts** [comment]
Yes I can. If it works I will set `language` only.

**Comment by chughts** [comment]
PR #514
