### ISSUE TITLE
[discovery] not accepting word files through node.js API call

### ISSUE THREAD

**Issue by paldebayan** [watson-developer-cloud/node-sdk#513]
**Getting the following error while uploading a word file to a collection, working fine for HTML and PDF**

{ Error: The Media Type [application/octet-stream] of the input document is not supported. Auto correction was attempted, but the auto detected media type [application/x-tika-ooxml] is also not supported. Supported Media Types are: application/json, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/pdf, text/html, application/xhtml+xml .
    at Request._callback (C:\Users\Dell\Desktop\dan\node_modules\watson-developer-cloud\lib\requestwrapper.js:85:15)
    at Request.self.callback (C:\Users\Dell\Desktop\dan\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Users\Dell\Desktop\dan\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Gunzip.<anonymous> (C:\Users\Dell\Desktop\dan\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
  code: 415,
  error: 'The Media Type [application/octet-stream] of the input document is not supported. Auto correction was attempted, but the auto detected media type [application/x-tika-ooxml] is also not supported. Supported Media Types are: application/json, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/pdf, text/html, application/xhtml+xml .' }

**the code is as follows:**

```js
var DiscoveryV1 = require('watson-developer-cloud/discovery/v1');

var discovery = new DiscoveryV1({
    username: 'xx',
    password: 'xx',
    version_date: '2017-09-01',
    endpoint: 'https://gateway.watsonplatform.net/discovery/api'
});

var fs = require('fs');
var file = fs.readFileSync('C:/Users/Dell/Desktop/ccc.docx');

discovery.addDocument({environment_id: 'xx', collection_id: 'xx', file}, function(err, response) {
  if (err) {
      console.error(err);
  } else {
  var y = JSON.stringify(response, null, 2);
    console.log(y);
  }
});
```

**Comment by nfriedly** [comment]
Hum.. try using `fs.createReadStream` instead of `readFileSync`:

```js
var file = fs.createReadStream('C:/Users/Dell/Desktop/ccc.docx');
```

This may work better because a ReadStream preserves the filename, which the service can then use as a hint of the file type. `readFileSync` just returns a generic Buffer with the contents of the file, but not the filename.  

(The ReadStream version is also a little more efficient, but it probably wouldn't be noticeable in this case.)

If that doesn't work, can you email me a copy of the file? nfriedly@us.ibm.com

**Comment by paldebayan** [comment]
thanks for the lightning fast reply...saved my day!
