### ISSUE TITLE
Can't generate a token

### ISSUE THREAD

**Issue by alansutherland** [watson-developer-cloud/node-sdk#536]
I cannot generate a token following your documentation, I've tried this example (along with many others) and I get myriad errors. With this particular one which I've added to a react/webpack project I get these errors:

> request.js:132 OPTIONS https://stream.watsonplatform.net/authorization/api/v1/token?url=https%3A%2F%2Fstream.watsonplatform.net%2Fspeech-to-text%2Fapi 401 (Processed)
> 
> Failed to load https://stream.watsonplatform.net/authorization/api/v1/token?url=https%3A%2F%2Fstream.watsonplatform.net%2Fspeech-to-text%2Fapi: 
> 
> Response for preflight has invalid HTTP status code 401
> Failed to fetch

 here's my code

```
    var watson = require('watson-developer-cloud');

      var authorization = new watson.AuthorizationV1({
      username: 'username',
      password: 'password',
      url: watson.SpeechToTextV1.URL
    });

    authorization.getToken(function (err, token) {
      if (!token) {
        console.log('error:', err);
      } else {
        console.log(token)
      }
    });
```

I've [followed these instructions](https://github.com/watson-developer-cloud/node-sdk/tree/master/examples/webpack) for getting this working in webpack but not having any luck. I'm testing locally btw.

Help me @nfriedly you're my only hope :)

**Comment by alansutherland** [comment]
[Please also see this related issue I've raised](https://github.com/watson-developer-cloud/node-sdk/issues/537)

**Comment by nfriedly** [comment]
Is that code on the client or on the server? If it’s on the server, then you might not be using the right credentials. If it’s on the client,  then it won’t work. Tokens must be retrieved server side. See here for an example token server: https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/examples/server.js

**Comment by alansutherland** [comment]
thanks very much dude :) got it working now, I overlooked that crucial part of the docs. I was trying to run it client-side.

**Comment by nfriedly** [comment]
Yea, the idea with tokens is that it prevents you from leaking your credentials to clients. Also, the browser WebSocket API does not allow you to set custom headers, so they would have to go into the querystring there, which is even worse because URLs get recorded in all kinds of places that shouldn't store your credentials.

**Comment by alansutherland** [comment]
@nfriedly would you mind explaining how the credentials are passed from server.js to the static index.html file? is this all bundled within bower_components/watson-speech/dist/watson-speech.js ?

I'm also trying to deploy the static folder which I can do but then server.js isn't included so the tokens aren't fetched. How would I deploy this?

**Comment by nfriedly** [comment]
The actual credentials never go to the client, just the auth token (which is only valid for 1 hour, so it wouldn't make sense to include in a bundle.)

`server.js` is running on a Node.js server somewhere (bluemix, your laptop, wherever). Your client-side code makes a HTTP request to this server. `server.js` takes your service credentials (that could be in an environment property, or hard-coded into the file) and uses those to request an auth token from Bluemix (Watson). It then passes that token back to the client in the HTTP response.

This cannot be done with static hosting alone, you need a Node.js server. A 256mb server on the [Bluemix free tier](https://www.ibm.com/cloud/pricing) should be sufficient to get you started.

**Comment by alansutherland** [comment]
thanks again, I'm a node noob :) I grok it now. We already have a bluemix account at work, which service would I use? create a SDK for Node.js cloud foundry app? then just create a space etc and cf push the entire examples folder?

**Comment by alansutherland** [comment]
not to worry I figured it out :) created a cloud foundry app, connected my stt & tts services and pushed the examples folder, worked like a charm :)
