### ISSUE TITLE
Add recognizeMicrophone() to node-sdk

### ISSUE THREAD

**Issue by alansutherland** [watson-developer-cloud/node-sdk#537]
I would like to use speech-to-text on the client side since I'm having trouble generating a token. This sdk allows me to use my credentials rather than generate a token as [demonstrated here](https://github.com/watson-developer-cloud/node-sdk#speech-to-text)

The problem is that on this sdk only recognizeStream is available. However, on the [watson-speech sdk](https://github.com/watson-developer-cloud/speech-javascript-sdk/tree/master/examples/) recognizeMicrophone is an option. But watson-speech sdk doesn't seem to offer a method for using the service without generating a token.

If you could add the recognizeMicrophone function to the main node-sdk that would help me out a lot.

**Comment by nfriedly** [comment]
You cannot use the service from a web browser with the service credentials. Instead a token must be generated server-side. See https://github.com/watson-developer-cloud/speech-javascript-sdk/tree/master/examples for several examples that work in web browsers. Also note that you will need to use https in most cases, although there is an exception for http://localhost when you are developing. (This is enforced by Chrome, not Watson)
