### ISSUE TITLE
Is support for acoustic customizations going to be added to speech to text?

### ISSUE THREAD

**Issue by RawStewage** [watson-developer-cloud/node-sdk#538]
Hi, with the recent addition of acoustic customizations to the Watson Speech To Text API I was wondering when support would be added for it in the node-sdk? If it is not coming soon can I contribute it?

**Comment by anweshan** [comment]
Unsure about the answer to your question, but feel free to contribute anything you want, read https://github.com/watson-developer-cloud/node-sdk/blob/master/.github/CONTRIBUTING.md

**Comment by ammardodin** [comment]
@RawStewage We are on the verge of a major release and the `acoustic customizations` support will be added in that release.

**Comment by ammardodin** [comment]
This is available in the beta release soon to be 3.0.0.
