### ISSUE TITLE
[discovery] add multiple collection query to node sdk

### ISSUE THREAD

**Issue by chethan-89** [watson-developer-cloud/node-sdk#545]
Discovery now supports querying across multiple collections. A new function is added to other SDKs but yet to be added in Node SDK. The changes are quite simple to make. Please add it to the SDK or I have already made a commit with those changes and have created a pull request. Please verify it and merge into the master if the changes look good. We have a release around the corner and are dependent on this change. Please look into it and take necessary action.

**Comment by ammardodin** [comment]
@chethan-89 We are on the verge of a new release which will include those changes that you desire. The release should be sometime in the next week or so.

**Comment by ammardodin** [comment]
There's a beta release available that includes the methods you mention above. We will release a 3.0.0 soon, but you can try out the beta release via `npm install watson-developer-cloud@beta`
