### ISSUE TITLE
Contact the typescript team and let them know that we support typescript

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/node-sdk#571]
We need to determine if the DefinitelyTyped typing for v2 of this SDK will interfere with [v3 (which is moving from JavaScript to TypeScript)](https://github.com/watson-developer-cloud/node-sdk/pull/562), and if so, what the appropriate resolution is.

Relates to:

* #448 
* https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16254
* https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20330

**Comment by anweshan** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/21896

**Comment by anweshan** [comment]
The answer was 

> If a user wants to use an old version of your library (like v2) and wants the types, then they can set their package.json to request a version from @types/.... that corresponds to the version of your lib that they want to use.

Or, to avoid confusion types can be removed https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package

-
