### ISSUE TITLE
Forbidden : Error ERCD-NOCONFIG occurred when accessing https://gateway.watsonplatform.net/visual-recognition/api/v3/classify

### ISSUE THREAD

**Issue by rupeshpawar** [watson-developer-cloud/node-sdk#580]
I am trying to use Visual Recognition service. My code is as follows.

```
var VisualRecognitionV3 = require('watson-developer-cloud/visual-recognition/v3');
var fs = require('fs');

var visual_recognition = new VisualRecognitionV3({
  api_key: '<api_key>',
  version_date: VisualRecognitionV3.VERSION_DATE_2016_05_20
});

var params = {
  images_file: fs.createReadStream('./resources/car.png')
};

visual_recognition.classify(params, function(err, res) {
  if (err)
    console.log(err);
  else
    console.log(JSON.stringify(res, null, 2));
});
```

Service credentials page in my account says to use "https://gateway-a.watsonplatform.net/visual-recognition/api" URL. But this library uses "https://gateway.watsonplatform.net/visual-recognition/api/". There is no way to pass the API URL.

**Comment by ammardodin** [comment]
@rupeshpawar You can pass in the URL when you instantiate the service, i.e 

```javascript
var visual_recognition = new VisualRecognitionV3({
  api_key: '<api_key>',
  version_date: VisualRecognitionV3.VERSION_DATE_2016_05_20,
  url: <YOUR URL> 
});
````

**Comment by germanattanasio** [comment]
Hi @rupeshpawar,

While the fix provided by @ammardodin will work, you are right and this is a problem in our SDK
This https://github.com/watson-developer-cloud/node-sdk/blob/master/visual-recognition/v3-generated.ts#L32 should point to the right URL.
