### ISSUE TITLE
[visual-recognition] All known visual recognition custom classifiers being used for classification

### ISSUE THREAD

**Issue by holly-cummins** [watson-developer-cloud/node-sdk#590]
When classifying an image, If I specify any custom classifiers using classifier_ids: [...], all of the custom classifiers I have defined are used to classify the image. Before the weekend, only the classifier I specified was used, which is the behaviour I'd expect. 

I have reproduced this with version <3 of the SDK, 3.0.1, and 3.0.3.

**Comment by holly-cummins** [comment]
A workaround has been shared with me; make sure the params contains an empty owners array. For example: 
     params.owners =  [  ]

**Comment by anweshan** [comment]
This was recently introduced by an API change by the Visual Recognition service, and they are actively working on fixing this issue. In the meantime, the workaround mentioned above should work.

**Comment by ammardodin** [comment]
@holly-cummins This issue has been fixed in the service. I am closing this, but please feel free to reopen if you notice anything off.
