### ISSUE TITLE
NLU model ID

### ISSUE THREAD

**Issue by noor92** [watson-developer-cloud/node-sdk#602]
When trying to include a model ID in the Natural Language Understanding Service, I get the following error:

> { Error: model not found
>     at Request._callback (/Users/js/ai/node_modules/watson-developer-cloud/lib/requestwrapper.js:85:15)
>     at Request.self.callback (/Users/js/ai/node_modules/request/request.js:186:22)
>     at emitTwo (events.js:125:13)
>     at Request.emit (events.js:213:7)
>     at Request.<anonymous> (/Users/js/ai/node_modules/request/request.js:1163:10)
>     at emitOne (events.js:115:13)
>     at Request.emit (events.js:210:7)
>     at Gunzip.<anonymous> (/Users/js/ai/node_modules/request/request.js:1085:12)
>     at Object.onceWrapper (events.js:314:30)
>     at emitNone (events.js:110:20) code: 404, language: 'en', error: 'model not found' }

However, when I pass the module ID to this URL mentioned in the docs: 
`https://gateway.watsonplatform.net/natural-language-understanding/api/v1/models/10:28d88779-d1e7-4119-9cfe-33451142daa2?version=2017-02-27`

it returns that my model is available. 

This is how I am calling the service: 

```js
module.exports.analyzeData= function(data) {
	var options;
	return new Promise (function (resolve, reject) {
		options = {
			text: 'Ally Wan Applied:13 Sep 2017 Last updated:7days Last active:7days',
			features: { 
				entities: { model: '**********' } 
			}
		}
		if (data.length <= 0) {
			log(`WARNING: content length of data` + '' + data.toString());
			return resolve();
		}
	 
		nlu.analyze(options, function (err, res) {
			log(err ? err: 'Watson response without error');
			return resolve(err || {res} );
		});
	})
}
```

**Comment by anweshan** [comment]
Hi, are you still getting this error? 

There is a error currently in the natural language understanding service related to custom models which will be fixed soon

**Comment by noor92** [comment]
Hi, not anymore. I wrote it like this. 

`features: { entities: { model: '10:28d88779-d1e7-4119-9cfe-3345********' ,mentions:true}, categories:{},concepts:{}} `

**Comment by noor92** [comment]
Hi, not anymore. I made following adjustments to my code: 


```
module.exports.analyzeData= function(data) {
	log('start sending data for watson to analyze');

	if (data.length <= 0) {
		log(`WARNING: content length of data` + '' + data.toString());
		return resolve();
	}

	var options = { 
		method: 'POST',
		url: 'https://gateway.watsonplatform.net/natural-language-understanding/api/v1/analyze',
		qs: { version: '2017-02-27' },
		headers: {
			authorization: "Basic " + new Buffer("39cf9a9c-6929************ :************").toString("base64"),
			'content-type': 'application/json' 
		},
		body: {
			text:" Sample text",
			features: { entities: { model: '10:28d88779-d1e7-4119-9cfe-********' ,mentions:true}, categories:{},concepts:{}} 
		},
		json: true }

		return new Promise(function (resolve, reject) {
			request(options, function (error, response, body) {
				if (error) {
					return reject(error)
				}
				resolve(body);
			});
		})
}

```
