### ISSUE TITLE
[visual-recognition] owners parameter ignored?

### ISSUE THREAD

**Issue by SirSpidey** [watson-developer-cloud/node-sdk#606]
Looks to me like the SDK is ignoring the `owners` parameter in the *parameters* object. 
- SDK version: `watson-developer-cloud@3.0.3`
- Node version: `v9.3.0`

**Expected behavior**
When you set **owners** to `[me]` and don't include any classifier_ids, the API classifies against your custom classifiers.

**Actual behavior**

Given this code

```js
...

let parameters = {
  owners: ["me"]
};

var params = {
  images_file: fs.createReadStream(.'/1024px-Beagle_1.jpg'),
  parameters: parameters
};

visual_recognition.classify(params, function(err, result) {
  if (err)
    console.log(err);
  else
    console.log(JSON.stringify(result, null, 2))
});
```

No custom classifiers are returned with the SDK (and there are 2 classifiers): 
```
...
      ],
      "image": "1024px-Beagle_1.jpg"
    }
  ],
  "images_processed": 1,
  "custom_classes": 0
}
```

But if you test the POST in the [API explorer](https://watson-api-explorer.mybluemix.net/apis/visual-recognition-v3#!/General/classify) with `{"owners":["me"]}` you get a result that includes the custom classifiers.
![image](https://user-images.githubusercontent.com/8194208/34827448-317749da-f6a8-11e7-8696-39c92e4da77e.png)

I can get the SDK to use the custom classifiers if I use `classifier_ids` in the **parameters** object and include both customer classifiers.

**Comment by anweshan** [comment]
This is now fixed! Going to release a patch release with fix soon.
