### ISSUE TITLE
First example on the tone analyzer not returning anything

### ISSUE THREAD

**Issue by Saamy88** [watson-developer-cloud/node-sdk#611]
I am trying to run this:
```js
'use strict';

var ToneAnalyzerV3 = require('watson-developer-cloud/tone-analyzer/v3');

var tone_analyzer = new ToneAnalyzerV3({
  username: 'INSERT YOUR USERNAME FOR THE SERVICE HERE',
  password: 'INSERT YOUR PASSWORD FOR THE SERVICE HERE',
  version_date: '2017-09-21'
});

tone_analyzer.tone(
  {
    tone_input: 'Greetings from Watson Developer Cloud!',
    content_type: 'text/plain'
  },
  function(err, tone) {
    if (err) {
      console.log(err);
    } else {
      console.log('tone endpoint:');
      console.log(JSON.stringify(tone, null, 2));
    }
  }
);
```

The second example works, which is the chat utterances, but the second one does not. Is there something wrong with it?

**Comment by anweshan** [comment]
The example is correct, however, tone analyzer does not return anything for that particular sentence as it is too short to generate any meaningful tone information. The example should probably be updated with a longer sentence or series of sentences to demonstrate that this works, but this is the correct way of writing code -- try it with more sentences or longer text.
