### ISSUE TITLE
Classification Error: Processing error

### ISSUE THREAD

**Issue by maulikdesai21** [watson-developer-cloud/node-sdk#622]
**Service Name : Watson Conversation 
Node version : 8.9.0
SDK-version : "watson-developer-cloud": "^3.0.5"
Version No : v1 , 
Version date : 2018-01-01**

I am getting **Classification Error: Processing error** as an error response in method 
```js
conversation.message(data,callback)
```

This is a random behavior  as same sentence would work perfectly at time and would error out randomly other time. 

However when I am passing action from the conversation this is more likely to happen,
```json
     "actions": [
    {
      "name": "transfer_check",
      "type": "client",
      "parameters": {
        ....
      },
      "result_variable": "context.transfer"
    }
  ]

```

**Comment by germanattanasio** [comment]
Is there a pattern on when the error occurs? I'm trying to see if this is a server issue of an SDK issue.

If you send the same message multiple times does it always fails?

**Comment by germanattanasio** [comment]
Not reproducible in the latest release. Please re-open this issue if it still occurs, with a set of reproducible steps. Check the CONTRIBUTING.md for an example.
