### ISSUE TITLE
Error "Cannot find name 'object'" when installing "watson-developer-cloud" nodejs module

### ISSUE THREAD

**Issue by vtheodos** [watson-developer-cloud/node-sdk#629]
[watson-developer-cloud nodejs module]

I used the IBM Watson ToneAnalyzer service to do some sentiment analysis. I decided to use the nodejs module in my Angular 2 project to take advantage of the class "ToneAnalyzerV3" (version: "2017-09-21"). However, after "npm start", I received the error "Cannot find name 'object'", which is not meaningful.

To solve the error, I did the following change in "dependencies" block of "package.json" file:

"watson-developer-cloud": "^3.0.5" (automatically installed after npm install watson-developer-cloud" ->"watson-developer-cloud": "^2.40.0".

PS: Credits also to Sonny Lans for his help

**Comment by anweshan** [comment]
Do you think you could share the code that gave this error? Which method in ToneAnalyzerV3?

**Comment by vtheodos** [comment]
The method is "tone_analyzer.tone". Unfortunately, it is part of commercial code.

**Comment by germanattanasio** [comment]
I just created a new folder with a new `package.json` and installed the library without issues.
```
[germana:~/Desktop/issue-629]$ ls -l
total 0
[germana:~/Desktop/issue-629]$ node -v
v7.5.0
[germana:~/Desktop/issue-629]$ npm -v
5.6.0
[germana:~/Desktop/issue-629]$ npm init
...
About to write to /Users/germana/Desktop/issue-629/package.json:
{
  "name": "issue-629",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
[germana:~/Desktop/issue-629]$ npm install watson-developer-cloud

> websocket@1.0.25 install /Users/germana/Desktop/issue-629/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN issue-629@1.0.0 No description
npm WARN issue-629@1.0.0 No repository field.

+ watson-developer-cloud@3.0.6
added 125 packages in 9.642s
[germana:~/Desktop/issue-629]$
```

In order for us to find and fix the issue, we need to be able to reproduce your issue.

**Comment by germanattanasio** [comment]
This issue has no reproducible steps. Please re-open this issue if it still occurs.
Check the CONTRIBUTING.md for an example.

**Comment by Allakazan** [comment]
Hi guys !
I solved the problem by change the version of package to ^2.40.0 and running: ``npm install --save @types/node`` in the root of my project.
