### ISSUE TITLE
[Conversation]Types are not exported

### ISSUE THREAD

**Issue by RoxanaDevIBM** [watson-developer-cloud/node-sdk#637]
Hey, 
I am using watson-developer-cloud with a TypeScript project where we use the conversation service.

When writing the code, I noticed that I was not able to use any of the types you guys defined under the namespace ConversationV1 in v1-generated.ts, and was advised to open a ticket.
This means that while using the code, I need to either generate the types myself or use any as a type.

For example:
The following code in TS would cause an error:
```js
const params: ConversationV1.GetWorkspaceParams = {
  workspace_id: workspaceId,
  export: false
};
```

This is caused by the fact that GetWorkspaceParams is something which is defined on the namespace, but not on the class which I import.

I was digging for a couple of solutions:
1. The most easy way would be to add/expose the types to the exported class in v1.d.ts by adding the following tot he class members:
```GetWorkspaceParams: GeneratedConversationV1.GetWorkspaceParams;```
The problem is, that there are a lot of types, and this seems a bit much to add them all, plus this solution does not seem right.
2. Another easy way is to expose v1-generated in index.d.ts, this will allow using it as a namespace.
3. Writing an internal type definition file for exposing the definitions I am using, tho this would cause not needed code duplication.
4. The hard option is to change the structure of v1, tho it lives up to the TypeScript requirements of the definition file generated. It looks like we lose the namespace when we extend the merged class/namespace GeneratedConversationV1, into ConversationV1 class and export that. This throws me back to nr.2.

The reason why I think it would be great to be able to use those types is that the intellisens given by this project is already great, and it would be a shame not to use it. Another reason is that of course when on TypeScript, any should be avoided as much as possible.

Any ideas? :)

**Comment by ammardodin** [comment]
Hey @RoxanaDevIBM thanks for reporting the issue and bring this up to our attention. The team recently switched to `TypeScript`. We will evaluate the options you provided and see what the right approach is here.

For the time being, can you try doing the following ?
```javascript
import{ GetWorkspaceParams } from 'watson-developer-cloud/conversation/v1-generated';
```
I think you can import the types you want to use via something like the above.

**Comment by anweshan** [comment]
So we have investigated the options you suggested - but ultimately we are investigating removing namespaces altogether as namespaces are not recommended in tslint as ES6-style external modules are the standard way to modularize code. For now all users can use the workaround provided and just import whatever types they want from the generated code

**Comment by germanattanasio** [comment]
We are displaying a deprecation message everytime users use a deprecated method, so I guess we need to wait for the next major release to deprecate the adapters.

**Comment by germanattanasio** [comment]
@dpopp07 I think that now that we are moving away from the `v1-generated` type of file this will be fixed. Maybe it's already fixed

**Comment by dpopp07** [comment]
I don't think the type exposure has changed it, so the solution would still be to import the type in the method Ammar described. I have been wanting to look into changing how types are exposed but haven't prioritized it yet. I listed in the v4 goals with `Seeking community feedback` but haven't heard anything. Maybe it's something I can look at for v4.

**Comment by dpopp07** [comment]
This hasn't changed and doesn't seem to be a problem for TS users. It should also be less of an issue now that Promises have correctly defined return types for inferred typing.

Types can be imported using this syntax:
```ts
import { Workspace } from 'ibm-watson/assistant/v1';`
```

Closing this issue - it can be re-opened if it is determined that this is a problem for anyone.
