### ISSUE TITLE
[Conversation] Add nodes_visited_details feature to message method options

### ISSUE THREAD

**Issue by asier-gutierrez** [watson-developer-cloud/node-sdk#639]
Simple HTTP request for message operation at Watson Conversation allows to add a field called nodes_visited_details as it is shown on the API reference for cURL https://www.ibm.com/watson/developercloud/conversation/api/v1/?curl#send_message.

The inclusion of this field to Node.js SDK would be very helpfull feature for the project I'm working on.

**Comment by anweshan** [comment]
Thanks for the comment! It will be added soon to the Node SDK.

**Comment by anweshan** [comment]
The newly generated version of the SDKs already has this, it will be merged in next week.

**Comment by asier-gutierrez** [comment]
Thanks!! I really appreciate your responses!
