### ISSUE TITLE
Watson [Natural Language Processing] requested html is not valid unicode

### ISSUE THREAD

**Issue by csurles** [watson-developer-cloud/node-sdk#646]
I am posting to Watson natural language processing api to read a webpage that has invalid Unicode characters. Can Watson send me the text and skip the invalid Unicode characters or encode them?

POST https://gateway.watsonplatform.net/natural-language-understanding/api/v1/analyze?version=2017-02-27&username=&password=&return_analyzed_text=true HTTP/1.1

{
                          "url": "http://www.mondaq.com/canada/x/678160/Patent/Federal+Court+Of+Appeal+Dismisses+Tevas+Levofloxacin+Damages+Appeal",
                          "features": {
                                        "entities":  {"limit": 80 },
                                        "metadata":{}
                                          }
}

{
  "error": "invalid request: requested html is not valid unicode",
  "code": 400
}

**Comment by anweshan** [comment]
https://www.ibm.com/watson/developercloud/natural-language-understanding/api/v1/?node#post-analyze

Are you passing in your HTML as a string? I'm not sure that unicode should cause a problem, but there is a 'clean' parameter that can perhaps help?

**Comment by csurles** [comment]
I am not passing any HTML. I am using Watson's URL functionality where it goes to the URL and pulls the html because it know how to avoid ads and such. So anytime I try to pull a web page with invalid Unicode it errors out. The clean option is set to true by default but that is not cleaning the Unicode.

**Comment by anweshan** [comment]
Sorry, there doesn't seem to be any function built in that cleans unicode, you will have to preprocess it

**Comment by anweshan** [comment]
Sorry, I gave an incorrect answer!

Here is the fix to your problem - the language detect does not allow non unicode characters, but if you specify the language, this will bypass that. If you specify `"language": "en" ` then your query will work.

**Comment by csurles** [comment]
Yes that worked thanks!
