### ISSUE TITLE
[Conversation] - Node Visited Details feature needs to be supported by SDK team

### ISSUE THREAD

**Issue by chethan-89** [watson-developer-cloud/node-sdk#650]
In the latest release, WCS added support to fetch node_visited_details which shows users what conditions were met in visiting that node. 

For this to work, we need to pass node_visited_details=true as part of query parameters. We need the Node JS SDK support to use this feature.

**Comment by anweshan** [comment]
Yup! We have added this feature to a new version, which will be released this week.
