### ISSUE TITLE
[speech-to-text] Cannot recognize stream from microphone

### ISSUE THREAD

**Issue by wandonye** [watson-developer-cloud/node-sdk#651]
First of all, issue [258](https://github.com/watson-developer-cloud/node-sdk/issues/258) has not been addressed. In the readme, there are still two examples mixed together. 

I expect the codes below should stream the audio from microphone directly to the speechToText service. 

```js
const micParams = { 
  rate: 44100, 
  channels: 2, 
  debug: false, 
  exitOnSilence: 6
}
export const micInstance = mic(micParams);
export const micInputStream = micInstance.getAudioStream();

let pauseDuration = 1;
micInputStream.on('pauseComplete', ()=> {
  console.log('Microphone paused for', pauseDuration, 'seconds.');
  setTimeout(function() {
      micInstance.resume();
      console.log('Microphone resumed.')
  }, Math.round(pauseDuration * 1000)); //Stop listening when speaker is talking
});

export const textStream = micInputStream.pipe(
  speechToText.createRecognizeStream({
    content_type: 'audio/l16; rate=44100; channels=1',
  })).setEncoding('utf8');

textStream.on('data', (user_speech_text) => {
  console.log(user_speech_text.toLowerCase());
});
```

But instead it gives the following error after `micInstance.start()` is triggered:

```
Uncaught Error: Unable to determine content-type from file header, please specify manually.
    at RecognizeStream._write
```

I believe it's much more common to stream mic into stt, instead of piping it into a .wav and then stream the .wav file to stt. Hope the readme can cover the more useful case.

**Comment by germanattanasio** [comment]
Try using `content-type: 'audio/l16; rate=44100; channels=1'` instead of `    content_type: 'audio/l16; rate=44100; channels=1'`

**Comment by wandonye** [comment]
Changing into `content-type` didn't work because it creates syntax err.

**Comment by ammardodin** [comment]
@wandonye the property needs to be a string if it contains a `-`, so you need to do something like `'content-type'`

**Comment by wandonye** [comment]
I went with another approach which worked. I used `fetch` to retrieve token and then the `speech-javascript-sdk` for the streaming connection.

Since my code structure has changed too much I didn't get a chance to try @ammardodin's method.

We can close this issue for now. If I got a chance to try `'content-type'`, I will post the outcome here.

**Comment by alschofield** [comment]
@wandonye @germanattanasio @ammardodin - I had the same error and tried ammardodin's suggestion and that ended up solving the error for me, thanks :)
