### ISSUE TITLE
[NLU] Argument error: version was not specified

### ISSUE THREAD

**Issue by don-tjandra** [watson-developer-cloud/node-sdk#666]
Could not understand why version field is not set in code below. As workaround, I can fix watson-developer-cloud version to 3.0.6. Then run npm update, pass version_date to service constructor, and NLU instance created without errors.

## Code
```
const NaturalLanguageUnderstandingV1 = require('watson-developer-cloud/natural-language-understanding/v1.js');
const nlu = new NaturalLanguageUnderstandingV1({
  url: settings.api.nlu.url,
  username: settings.api.nlu.username,
  password: settings.api.nlu.password,
  version_date: NaturalLanguageUnderstandingV1.VERSION_DATE_2017_02_27,
  version: NaturalLanguageUnderstandingV1.VERSION_DATE_2017_02_27
});
```

## Content of package.json
"watson-developer-cloud": "^3.0.6"

## After npm update
`-- watson-developer-cloud@3.2.1

## Partial stack trace
Error: Argument error: version was not specified
    at NaturalLanguageUnderstandingV1 [as constructor] (C:\Users\dtjandra\projects\explore\node_modules\watson-developer-cloud\natural-language-understanding\v1-generated.js:55:19)
    at new NaturalLanguageUnderstandingV1 (C:\Users\dtjandra\projects\explore\node_modules\watson-developer-cloud\natural-language-understanding\v1.js:36:24)

**Comment by anweshan** [comment]
Hi!

This was changed in v3.0.7 and subsequent versions to remove the hardcoded date constants

The correct usage pattern should be 

```
const NaturalLanguageUnderstandingV1 = require('watson-developer-cloud/natural-language-understanding/v1.js');
const nlu = new NaturalLanguageUnderstandingV1({
  url: settings.api.nlu.url,
  username: settings.api.nlu.username,
  password: settings.api.nlu.password,
  version: '2017-02-27'
});
```

Instead of date constants, we now require you to pass in the date as '2017-02-27' etc. for the version date

**Comment by don-tjandra** [comment]
Thanks, passing date string resolved the issue.
