### ISSUE TITLE
naturalLanguageClassifier.createClassifier - npm pacakge gives error - "TypeError: source.on is not a function"

### ISSUE THREAD

**Issue by nitin20212** [watson-developer-cloud/node-sdk#668]
Here is the code i am using-

//var nclib is defined in settings.js require('/usr/src/node-red/node_modules/watson-developer-cloud/natural-language-classifier/v1')
// var fs is defined in settings.js require('fs'),

var NaturalLanguageClassifierV1 = context.global.nlclib; 
var fs     = context.global.fsstream;

var naturalLanguageClassifier = new NaturalLanguageClassifierV1({
  username: '******************', 
  password: '****************'
});
 
var params = {
  metadata: {language: 'en',name: 'My Classifier'},
 training_data: fs.createReadStream('/usr/src/node-red/keyfiles/nlcdev.csv')
};

naturalLanguageClassifier.createClassifier(params,
  function(err, response) {
    if (err)
      console.log(err);
    else
      node.error(response);
      msg.payload = response;
      console.log(JSON.stringify(response, null, 2));
      node.send(msg);
});

return msg;

**Comment by ammardodin** [comment]
@nitin20212 Metadata is a form-data entry. You need to stringify metadata. Try writing your params like this:
```javascript
var params = {
    metadata: JSON.stringify({language: 'en',name: 'My Classifier'}),
    training_data:  fs.createReadStream('/usr/src/node-red/keyfiles/nlcdev.csv')
}
```

**Comment by nitin20212** [comment]
@ammardodin - That worked..Thank you..!!

If I use the class "create" instead of "createClassifier", it works passing as "{language: 'en',name: 'My Classifier'}". seems, this was the change in new version. 

Thanks for your help..!!

**Comment by ammardodin** [comment]
@nitin20212 The reason for this is that our NodeJS client is now auto-generated based on Swagger API. The type of `metadata` in the API spec is `file` as you will see [here](https://watson-api-explorer.mybluemix.net/apis/natural-language-classifier-v1#!/Manage32classifiers/createClassifier), therefore it's expected to be a file-like object, but a regular JavaScript object doesn't satisfy that requirement, so the latest method `createClassifier` will fail unless what's passed as metadata satisfies that requirement.

**Comment by nitin20212** [comment]
Thank you..that was useful.. can I ask you one question - is there a way to update the existing training set for additional data using API ?

**Comment by ammardodin** [comment]
@nitin20212 NLC doesn't currently have a way to update the training set. If you've found additional data you'd like to include in training the classifier, you'd need to create a new classifier.
