### ISSUE TITLE
Error in API reference nodejs example: source.on is not a function

### ISSUE THREAD

**Issue by octav-heronai** [watson-developer-cloud/node-sdk#673]
I'm trying to use Watson Classifier from node. I've started by implementing the example in the API reference, found at https://www.ibm.com/watson/developercloud/natural-language-classifier/api/v1/node.html?node#create-classifier

My code (sensitive information replaced with stars):
```
 58     create: function(args, cb) {
 59         var params = {
 60             metadata: {  
 61                 language: 'en',
 62                 name: '*********************'
 63             }, 
 64             training_data: fs.createReadStream(config.data.prepared.training)
 65         };
 66 
 67         params.training_data.on("readable", function () {
 68             nlc.createClassifier(params, function(err, response) {
 69                 if (err)
 70                     return cb(err);
 71                 console.log(JSON.stringify(response, null, 2));
 72                 cb();
 73             });
 74         });
 75     },
```

The file I am trying to make a stream from exists. The stream works (I've managed to read from it on "readable"). I've placed the on("readable") part because it made sense for me to do all of this once the stream becomes available, and also because I wanted to be able to check that I can read from it. It does not change the outcome, however.

nlc is the natural_langauge_classifier instance.

I'm getting this:
```
octav@****************:~/watsonnlu$ node nlc.js create
/home/octav/watsonnlu/node_modules/delayed-stream/lib/delayed_stream.js:33
  source.on('error', function() {});
         ^

TypeError: source.on is not a function
    at Function.DelayedStream.create (/home/octav/watsonnlu/node_modules/delayed-stream/lib/delayed_stream.js:33:10)
    at FormData.CombinedStream.append (/home/octav/watsonnlu/node_modules/combined-stream/lib/combined_stream.js:44:37)
    at FormData.append (/home/octav/watsonnlu/node_modules/form-data/lib/form_data.js:74:3)
    at appendFormValue (/home/octav/watsonnlu/node_modules/request/request.js:321:21)
    at Request.init (/home/octav/watsonnlu/node_modules/request/request.js:334:11)
    at new Request (/home/octav/watsonnlu/node_modules/request/request.js:128:8)
    at request (/home/octav/watsonnlu/node_modules/request/index.js:53:10)
    at Object.createRequest (/home/octav/watsonnlu/node_modules/watson-developer-cloud/lib/requestwrapper.js:208:12)
    at NaturalLanguageClassifierV1.createClassifier (/home/octav/watsonnlu/node_modules/watson-developer-cloud/natural-language-classifier/v1-generated.js:143:33)
    at ReadStream.<anonymous> (/home/octav/watsonnlu/nlc.js:68:8)
```

I tried debugging it myself for a while, but I'm not sure what this source is actually supposed to be. It's just an object composed of the metadata I put in and the "emit" function if I print it before the offending line in delayed-stream.js.
```
{ language: 'en',
  name: '**********************',
  emit: [Function] }
```

This is my package.json file:
```
  1 {
  2     "name": "watsonnlu",
  3     "version": "0.0.1",
  4     "dependencies": {
  5         "csv-parse": "2.0.0",
  6         "watson-developer-cloud": "3.2.1"
  7     }
  8 }
```

Any ideas how to make the example work? I know there is a similar issue from last year, but this is different, I think. Also, I think it's bad to have example code which does not work

(on a side note, in the example code the "metadata" object is missing altogether and the two fields are just placed directly in the root object - this seems to not be how it works, maybe that needs to be fixed as well in the documentation).

Cheers!
Octav

**Comment by ammardodin** [comment]
@octav-heronai You need to stringify metadata via `JSON.stringify`before you pass it.

**Comment by anweshan** [comment]
Thank you for notifying that the documentation needs to be updated!

**Comment by octav-heronai** [comment]
Stringify does the trick, thanks :)

**Comment by anweshan** [comment]
@ammardodin the type of metadata is currently ReadableStream/FileObject/Buffer. Should this be type String?

**Comment by germanattanasio** [comment]
No necessary, the user can send a string, a json file with the metadata or a `FileObject`

**Comment by ammardodin** [comment]
@anweshan Since the API definition has `metadata` as a `formData` parameter of type `file` it will be generated as a ` ReadableStream/FileObject/Buffer`. The user can simply stringify the JSON, or pass any of the other compliant parameters.

**Comment by anweshan** [comment]
@ammardodin I should clarify - I am asking as a service question, should it be type 'String' or JSON as it seems silly to make a file just to have metadata describing the language

Also - API reference is now updated to correctly show that metadata is required!

**Comment by ammardodin** [comment]
@anweshan Right now `metadata` supports two fields, namely `name` and `language`. I think it was chosen to be a `JSON` file as a design choice to allow `metadata` to easily grow and support additional fields that clients might deem to be useful in versioning their classifiers.
