### ISSUE TITLE
Always geraddrinfo error is reproducible, whenever there are bulk call

### ISSUE THREAD

**Issue by avinash2fly** [watson-developer-cloud/node-sdk#683]
error: { Error: getaddrinfo ENOTFOUND gateway.watsonplatform.net gateway.watsonplatform.net:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'gateway.watsonplatform.net',
  host: 'gateway.watsonplatform.net',
  port: 443 }

**Comment by germanattanasio** [comment]
Do you have a firewall or VPN blocking your internet connection?

I just tried 
```
curl -s https://gateway.watsonplatform.net
```
And got a valid response
```json
{
  "code": 403,
  "error": "Forbidden",
  "description" : "2018-04-30T08:43:04-05:00, Error ERCD-NOCONFIG occurred when accessing https://gateway.watsonplatform.net/, Tran-Id: gateway01-2348965993 -"
}
```

**Comment by avinash2fly** [comment]
problem is with multiple calls, I am using NLC node-sdk and with 50 multiple calls one after the other, I start to get this error. And it's pretty common with other API's as well e.g. discovery API, NLU.

**Comment by germanattanasio** [comment]
Interesting... So it's a concurrency issue. 

Are you using High Sierra in Mac? See https://github.com/nodejs/node/issues/15466

**Comment by avinash2fly** [comment]
yes, correct. Is it an existing one?

**Comment by germanattanasio** [comment]
@avinash2fly where you able to see if the problem was on your computer?

Can you check if you still see the error using an IAM instance of Natural Language Understanding? You can create it if you go to the IBM Cloud console and create a Natural Language Understanding instance in `us-east` or `au-syd`

**Comment by avinash2fly** [comment]
we kept the project on hold fro the moment. you it think it might be Mac problem. I will keep in mind th e listed solution. Thanks.

**Comment by germanattanasio** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by komalpcg** [comment]
It is happening for me. I called the ibm watson API for sentiment analysis from firebase cloud functions and it results in error randomly:
 getaddrinfo ENOTFOUND iam.cloud.ibm.com iam.cloud.ibm.com:443
