### ISSUE TITLE
[assistant] Issues while creating/updating Entities values with Pattern type

### ISSUE THREAD

**Issue by jungleBadger** [watson-developer-cloud/node-sdk#690]
### Step by step
* Create an Entity Value with Pattern type on its configuration
* Try to add, or update/delete (in case of addition using Service UI) a synonym on this Entity using node.js SDK methods

#### Request call through my server
![xsaxasasx](https://user-images.githubusercontent.com/12788435/39730746-c470599c-5239-11e8-89e6-9dbf848fe6f7.PNG)

#### Showing that entity actually exists (Through Conversation UI)
![csdcdds](https://user-images.githubusercontent.com/12788435/39730754-d31519ec-5239-11e8-8a32-330b2fdcda91.PNG)

### Details
* All CRUD calls works using Conversation UI.
* All CRUD calls work perfectly to synonyms on intents that is configured as synonym on its type.

### Node version
8.9.4

### SDK Version
3.3.0 and 3.4.1

### Expected Results
CRUD operations working fine on Values with Pattern as its type.

#### 3.3.0
Data Exception: The value: ${SOME_VALUE} is of a different type for the given entity

#### 3.4.1
Resource not found

### Possible solution
> It seems that when calling createSynonym, updateSynonym and deleteSynonym, the code is trying to access the `synonym` param directly, by attaching it to body request, so my guess is that when this request hits the server and gets the object, it will not found a synonym/s param there because it should have a pattern/s one.

![xxsasax](https://user-images.githubusercontent.com/12788435/39730726-b0ce3ddc-5239-11e8-8dfa-c2e7e4d26446.PNG)

**Comment by anweshan** [comment]
Thanks for submitting this issue! I am looking into this right now.

**Comment by ammardodin** [comment]
@jungleBadger Let me see if I understand what you're trying to accomplish here. So, you want to
- [ ] Create an entity
- [ ] Add a value to this entity of type pattern
- [ ] Add another value to this entity of type synonym

Is this correct?

**Comment by anweshan** [comment]
Hi @jungleBadger, apologies for the late response.

Unfortunately what you are trying to do is not allowed by the service itself - an entity value can have synonyms, or patterns (but not both). In order to add a synonym to an entity with the `patterns` type, you need to first call `updateValue` and change the `new_type` to be `synonyms`, as entity values with patterns cannot additionally have synonyms.

**Comment by ammardodin** [comment]
To update an entity value of type value, you can use the `updateValue` method. `updateSynonym` is reserved to update synonyms on an entity value of type synonym.

**Comment by jungleBadger** [comment]
And how about to update a pattern?

**Comment by ammardodin** [comment]
When you call `updateValue` to update a value of type pattern, you just need to specify the type of the value you're updating as `patterns`, and pass in an array of patterns. You can see the details in the [API](https://www.ibm.com/watson/developercloud/conversation/api/v1/curl.html?curl#update-value) reference

**Comment by jungleBadger** [comment]
I'm not home right now I will try to debug and make a video later in order to help the report.

**Comment by anweshan** [comment]
Hi, it's a bit confusing...no need to make a video, posting a code snippet will help.

It sounds like you are trying to create an entity value with type pattern, then edit this value to have a synonym as well? You cannot have a value of type pattern to have synonyms, you need to first edit the value to be of type synonym before calling createSynonym

**Comment by anweshan** [comment]
This is valid code to add new patterns to a entity value of type patterns
```
var params = {
  workspace_id: 'XXX',
  entity: 'beverage',
  value: 'bev_value',
  new_type: 'patterns',
  new_patterns: [
    'pop',
    'soft drink'
  ]
};

assistant.updateValue(params2, function(err, response) {
  if (err) {
    console.error(err);
  } else {
    console.log(JSON.stringify(response, null, 2));
  }
});
```

And this is valid code to add synonyms to a entity of type pattern

```
var params = {
  workspace_id: 'XXX',
  entity: 'beverage',
  value: 'bev_value',
  new_type: 'synonyms',
  new_synonyms: [
    'milk',
    'water'
  ]
};

assistant.updateValue(params, function(err, response) {
  if (err) {
    console.error(err);
  } else {
    console.log(JSON.stringify(response, null, 2));
  }
});
```

**Comment by jungleBadger** [comment]
I'm sorry for the confusion regarding Values/Synonyms, I will try to explain again:

I'm trying to add/update/delete synonyms to a Value of type Pattern using Node.js SDK.


I have this object as an Entity Value:
```
{
   "patterns": [], 
   "type": "patterns",
   "value": "assaasaeaewxxasxaexsasxsa"
}
```

> This is valid and is being listed as a value from my Entity


I want to add the following Synonym: 
```
{
 workspace_id: '46ae281f-8bf8-4900-a8e7-0dd8b8ac2771',
  entity: 'Test',
  value: 'assaasaeaewxxasxaexsasxsa',
  synonym: 'ae'
 }
```

> Notice that I do not want to use updateValue method to add the following synonym, I am using createSynonym method (updateSynonym and deleteSynonym has the same result).

Please, to replicate:
* Add an Entity
* Add an Entity Value of the Patterns type
* Add a Synonym to this value using createSynonym method


Please, also notice that:
> The following calls and interactions works fine using Watson Assistant Service UI.  I can manipulate synonyms (perhaps it is using updateValue method directly)


I do not want to use updateValue because the calls rate is lower than xxxSynonyms methods.


Thanks in advance

**Comment by anweshan** [comment]
@jungleBadger an entity value cannot have *both* patterns and synonyms, so I don't really understand the purpose of your use case. When you add synonyms to a value you will overwrite all existing patterns. You can use createSynonym methods to add synonyms to an entity value, given it is of the Synonyms type. If you want to add synonyms to a value of patterns type you need to first call updateValue to make it a synonyms type, but then from then on you can call createSynonym as many times as you would like without having to call updateValue.

This isn't something with the SDK specifically, it is just the way the service is, you can verify using the API explorer

**Comment by anweshan** [comment]
Closing this issue as it doesn't represent an error in the SDK
