### ISSUE TITLE
Support an IAM access token as query parameter when calling recognize

### ISSUE THREAD

**Issue by chughts** [watson-developer-cloud/node-sdk#697]
## Update Jun 18nd

As a Developer _I want_ to call the `recognize()` method using an IAM access token _so that_ I can create a WebSocket connection from a browser.

Calling the `/recognize` method works if we specify the `Authorization` header but it doesn't support the `watson-token` query parameter.

### Acceptance Criteria

 - [ ] Should accept an IAM access token in the `watson-token` query parameter
 - [ ] Should accept the `Authorization` bearer token.

---

## Old issue

Node version : 8.11.1
SDK version : 3.4.2

This issue relates to using STT streaming from the browser. 

With username / password credentials the BaseService superclass of AuthorizationV1 does not assign a tokenManager, and allows the Authorization getToken to function normally, retrieving a Bearer token to be use from the client.
 
With an iam_key, the BaseService assigns a IAM tokenManger  `v1_1.IamTokenManagerV1`,  which causes an exception int the BaseService `createRequest` function when

                parameters.defaultOptions.headers.Authorization =
                    "Bearer " + accessToken;

as `parameters.defaultOptions.headers` does not exist. 

It looks like `v1_1.IamTokenManagerV1` is causing a different behaviour to the constructor and getToken stack for AuthorizationV1 that does not allow Bearer Tokens to be retrieved with `AuthorizationV1 .getToken`

**Comment by pekevski** [comment]
looks like `parameters.defaultOptions` is a copy of the `options` object the developer inputs into the constructor of the service. eg. `var speechToText = new SpeechToText(options)`, therefore, `defaultOptions.headers` is undefined. Looks like the `initCredentials()` method doesn't append a headers object to the defaultOptions object either and thats why we get an authorisation issue.

**Comment by germanattanasio** [comment]
The `Authorization` service will be deprecated and it's not compatible with IAM.
The recommended approach is to get an Access Token and use it with the service rather than using the IAM API key.

**Comment by chughts** [comment]
@germanattanasio thanks for the direction. I can now fetch a token and have made progress but am now getting either a 401, or a 403 when opening the web socket connection. If this is a user level problem, then I can raise the issue on a forum (name your choice) and we can follow up there. 

Here are the pertinent code updates that I have made done. 

````
const AuthIAMV1 = require('watson-developer-cloud/iam-token-manager/v1');
...
let tokenService = new AuthIAMV1.IamTokenManagerV1({iamApikey : apikey});
...
tokenService.getToken((err, res) => {
  if (err) {
    reject(err);
  } else {
    tokenPending = false;
    tokenTime = now;
    token = res;
    resolve();
  }
});
...
let wsURI = 'wss://' + endpoint + '/v1/recognize'
                             + '?watson-token=' + token + '&model=' + model;

let ws = new WebSocket(wsURI);

ws.on('open', () => {
  ...
});
ws.on('message', (data) => {
  ...
});
ws.on('close', () => {
  ...
});
ws.on('error', (err) => {
  ...
});
````

I never get the on open only an on error. Which is 403 unauthorised when the endpoint is stream.watsonplatform.net/speech-to-text/api and 401 when the endpoint is gateway-syd.watsonplatform.net/speech-to-text/api

This logic works when using a userid / password based token from Authorization

**Comment by chughts** [comment]
I guess we are stuck on this - https://console.bluemix.net/docs/services/speech-to-text/release-notes.html#May2018-IAMwss

**Comment by jeffpk62** [comment]
The `watson-token` parameter cannot be used for IAM tokens.  You would need to pass the IAM access token with the `Authorization` header by specifying the usual `Bearer` value.  The release note applies to using WebSockets from a browser with JavaScript, which does not support passing headers with the connection request.  But if you can pass the header and IAM token with the Node request, that should succeed.

**Comment by chughts** [comment]
@jeffpk62 WebSockets from Node.js server side with IAM token also doesn't work. 

As per https://github.com/watson-developer-cloud/node-sdk/issues/696 
I am also struggling to get the regular recognize API to work with IAM tokens. Note: it is only with recognize that I have a problem, all other methods are working.  I have tried the SDK, and also crafting my own request. 

When crafting my own request, I get 401, I have tried with headers.authorization set to the IAM token with and without the Bearer. I have also tried with the standard auth.bearer: token, but all to no avail.

**Comment by jeffpk62** [comment]
@chughts Sorry, my response was based on what should work; I've not done much with IAM tokens yet.  Sorry for the misinformation, and good luck!

**Comment by anweshan** [comment]
@chughts This is a known error, the reason it hasn't been patched yet is we believe there are asynch issues related to the IAM call and access token call, a patch is estimated to be fixed by today.

**Comment by anweshan** [comment]
@chughts Your issue should be fixed in a beta release of watson-developer-cloud, to try it out, try installing watson-developer-cloud with version `beta`

However, you need to wrap your calls to methods with streams with a new method `pre-authenticate`. 

An example:

```
stt.preAuthenticate(function(ready) {
  if (!ready) {
    return;
  }
  stt.recognize(params, function(err, res) {
    if (err) {
      console.log(err);
    } else {
      console.log(JSON.stringify(res, null, 2));
    }
  });
});
```

**Comment by chughts** [comment]
I can confirm that this works with my code and the beta version of the SDK.

**Comment by germanattanasio** [comment]
`watson-token` should allow users to send an IAM token along with the old watson token. We need to enable this in the service

**Comment by germanattanasio** [comment]
We are working on a solution for users using the IAM apikey or an access token. It could be that we have to change the query parameter name. I will keep this issue updated.

**Comment by germanattanasio** [comment]
I've updated this issue with the remaining work

**Comment by germanattanasio** [comment]
The service now accepts the access token as a query parameter. Should we close this @dpopp07?

**Comment by dpopp07** [comment]
We might want to leave this open as `access_token` is only a parameter in the Watson Speech browser SDK. Is the problem here for the HTTP `recognize` or the WebSocket `recognize`? We can add `access_token` as a query parameter to one or both of these if need be.

For WebSockets, we already support `watson-token` and it is handwritten, so adding `access_token` would be easy.

For HTTP, it would be a hand-written change to add this query parameter unless we add it to the API spec so I would like to make sure there is a strong reason that we need it.

**Comment by germanattanasio** [comment]
I think the request was to support `watson-token` in the WebSocket method. The HTTP doesn't need to.

**Comment by dpopp07** [comment]
I added support for `access_token` in recognize/synthesize with websockets in `v3.18.2`
