### ISSUE TITLE
[text-to-speech] VCAP_SERVICES for Sydney instances displaying incorrect URL

### ISSUE THREAD

**Issue by Brianawalker** [watson-developer-cloud/node-sdk#706]
A customer is using the Node.Js SDK to create and utilize the Text to Speech service. They contacted Watson Support to report that they had issues creating custom models, due to the VCAP_SERVICES credentials displaying the incorrect url. 

According to the client, the url is currently displayed as _"https://stream-syd.watsonplatform.net/speech-to-text/api"._ 
The corrected url should be _"https://gateway-syd.watsonplatform.net/speech-to-text/api"_

@mamoonraja @jeffpk62

**Comment by mamoonraja** [comment]
@anweshan @germanattanasio Looks like RC instances have https://gateway-syd.watsonplatform.net/speech-to-text/api. Are we planning to deal with it soon?

**Comment by mamoonraja** [comment]
Does not look like an SDK issue, I think we need to update VCAP services.

**Comment by germanattanasio** [comment]
@Brianawalker If the user specifies the URL in the constructor then he can use `gateway-syd.watsonplatform.net/speech-to-text/api`.

Sadly we can't find the URL automatically. We default to `gateway.watsonplatform.net` and allow the user to override it.
