### ISSUE TITLE
failing unit tests

### ISSUE THREAD

**Issue by DanielRuf** [watson-developer-cloud/node-sdk#710]
It seems the unit tests are currently failing

https://travis-ci.org/watson-developer-cloud/node-sdk/builds/386875229

**Comment by anweshan** [comment]
Unit tests now pass

**Comment by DanielRuf** [comment]
> Unit tests now pass

Where? https://github.com/watson-developer-cloud/node-sdk/commits/master

**Comment by anweshan** [comment]
The build passes, unit tests were passing in that build, a few integration tests were not due to intermittent service errors which are not affecting the build longer.

**Comment by DanielRuf** [comment]
Ah ok =)
