### ISSUE TITLE
[visual-recognition] Error: socket hang up

### ISSUE THREAD

**Issue by holly-cummins** [watson-developer-cloud/node-sdk#715]
```
   2018-06-07T10:56:18.19+0100 [APP/PROC/WEB/0] OUT Error returned from Watson. Retrying:  { Error: socket hang up
   2018-06-07T10:56:18.19+0100 [APP/PROC/WEB/0] OUT     at createHangUpError (_http_client.js:254:15)
   2018-06-07T10:56:18.19+0100 [APP/PROC/WEB/0] OUT     at TLSSocket.socketOnEnd (_http_client.js:346:23)
   2018-06-07T10:56:18.19+0100 [APP/PROC/WEB/0] OUT     at emitNone (events.js:91:20)
```
If I send multiple requests to the visual recognition service, I see a high occurrence of 'code 400' errors for individual images (#714). I also see a high occurrence of http-request level errors, and these seem to persist even when retrying.

**Comment by ammardodin** [comment]
@holly-cummins Thanks for opening the issue. When you observe a socket hang up, do you retry immediately, or are you doing some sort of back off / time interval queue strategy? Are you using a proxy by any chance ?

**Comment by holly-cummins** [comment]
We're not using a proxy (the app is running on IBM cloud). We do use a backoff on our retry, with the `promise-retry` library. I've tried increasing the time in the backoff, but no luck. This is the code for the connection: 

  ```
classify(params) {
    return promiseRetry(
      { retries: 5, factor: 1.4, minTimeout: 200 },
      (retry, number) => {
        return this.classifyWithoutRetry(params).catch(err => {
          console.log('Error returned from Watson. Retrying: ', err);
          retry(err);
        });
      }
    ).catch(err => {
      console.error(
        'Giving up with persistent error: ',
        err
      );
      return { images: [] };
    });
  }

  classifyWithoutRetry(params) {
    return new Promise((resolve, reject) => {
      const startTime = Date.now();
      this.watson.classify(params, (err, result) => {
        if (err) {
          reject(err);
        } else {
          resolve(result);
        }
      });
    });
  }

```

**Comment by holly-cummins** [comment]
As a further data point, the error is often persistent once it starts - so once we see the error, it continues, even over 5 retries.

**Comment by holly-cummins** [comment]
... and two more little bits of information. In the good case, I get a response within 10 seconds or so. In the socket hangup case, I don't get a response for 60 seconds (at which point I guess it makes sense that one side disconnects, since the communication obviously isn't going well).  I've found a similar report from a few years ago: https://developer.ibm.com/answers/questions/380096/getting-socket-hangup-error-when-trying-to-make-2/

**Comment by germanattanasio** [comment]
@holly-cummins have you seen this issue lately? Do you have the code that was causing this? We would like to know if it was fixed with the recent move to IAM

**Comment by holly-cummins** [comment]
Sadly, at the moment the app which showed the problem isn't running. I'm happy to be optimistic that this is fixed and close it, and I can re-open if I see the issue when I next stage the app.
