### ISSUE TITLE
load conversation credentials from `VCAP_SERVICES`

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/node-sdk#725]
Loading VCAP_SERVICES for assistant service instances seems to be broken in at least some cases, possibly because we're not accounting for the different service name ("conversation" instead of "assistant").

We may need to change this code to add a line for `if (this.name === 'conversation`)` to first check for conversation and then assistant if conversation is empty.

``` js
if (this.name === 'visual_recognition') {
      temp = vcapServices.getCredentials('watson_vision_combined');
    } else {
      temp = vcapServices.getCredentials(vcapServicesName);
    }
```

**Comment by germanattanasio** [comment]
Fixed in 3.5.1
