### ISSUE TITLE
IAM URLs for Watson APIs are different than defaults in the the WDC Node SDK 

### ISSUE THREAD

**Issue by bdragunas** [watson-developer-cloud/node-sdk#727]
By default when you instantiate a Watson Service using the Node SDK (for example Watson Assistant) the URL path that is used in the WDC package is: https://gateway.watsonplatform.net/assistant/api

Given the new IAM authentication for all Watson services, they require a different URL to authenticate your iam_apikey against (for example Watson Assistant) uses: https://gateway-wdc.watsonplatform.net/assistant/api

The existing Watson API documentation will lead you to an authentication error as a result. A temporary fix is to pass in the IAM URL when you instantiate the Watson API object to override the default URL that the Node SDK uses. 

Like this:
var watsonAssistant = new AssistantV1({
    url: '{iam_url}'
    version: '{version}',
    iam_apikey: '{iam_api_key}'
  });

Fix: There should be a parameter you pass into the SDK declaring if you are using IAM or basic authentication. The SDK will then toggle to the right URL path for proper authentication.

**Comment by germanattanasio** [comment]
@bdragunas We already support the `iam_url` and `url` parameters. I think you are confusing them but the url for the Watson services didn't change. We added support for new regions where Watson was not available like Washington(The URL you are using in your example).

The `iam_url` should only be specified if is not the default.
