### ISSUE TITLE
[speech-to-text] `objectMode: true` doesn't work when `recognizeStream.setEncoding('utf8')` set

### ISSUE THREAD

**Issue by iaincollins** [watson-developer-cloud/node-sdk#733]
Now that `objectMode: true` needs to be set to get interim speech recognition results in object form on `data` events (with word timing info, etc) if `recognizeStream.setEncoding('utf8')` is set on the stream then empty event data is passed in `data` events.

This is confusing when upgrading to the latest release of the node-sdk as in previous releases when `setEncoding('utf8')` was not set, results were not returned correctly (at least not for all languages) - meaning that it previously if you were using interim results it  _had_ to be set (and now _must not_ be set).

I appreciate you may not feel like addressing this use case but I hope that logging it here (even if the issue is closed) may at least help folks who run into this issue in future, as getting blank object data after upgrading the sdk was unexpected.

**Comment by dpopp07** [comment]
@iaincollins Thanks for opening this issue. We recently discovered this issue and that the example for `createRecognizeStream` was out of date. I updated the example to match the current behavior, along with some minor explanations. I am not sure if we will be changing this behavior anytime soon but hopefully this issue and the new example will help alleviate any problems for users moving forward.

Updated example: https://github.com/watson-developer-cloud/node-sdk/blob/master/examples/speech_to_text.v1.js
