### ISSUE TITLE
Write unit tests for Discovery

### ISSUE THREAD

**Issue by stevengassert94** [watson-developer-cloud/node-sdk#745]
Hi, I'm part of the SRE team for Discovery and I'm trying to learn more about Javascript so after talking to @germanattanasio I decided to write some unit tests.

I will write a PR and use it to close this issue

**Comment by germanattanasio** [comment]
@stevengassert94 do you still want to do this?

**Comment by dpopp07** [comment]
I am adding automatically generated unit tests to the SDK this week, so this is no longer needed.

If you are still interested in learning about using Discovery with NodeJS, writing integration tests would be a good way to do it.

Closing this issue, please open another one for integration tests if you still want to do it.
