### ISSUE TITLE
[Watson Discovery Service] AddDocument function not accepting base64 encoded file as input 

### ISSUE THREAD

**Issue by apasrini** [watson-developer-cloud/node-sdk#747]
[Watson Discovery Service]AddDocument function not accepting base64 encoded file as input.

I am trying to invoke the addDocument function with params as provided in the document. 

Not Able to add document with file input parameter as  base64 encoded string which is a file instead of using local file path.

**1st try :** 
```
var DiscoveryV1 = require('watson-developer-cloud/discovery/v1');
var fs = require('fs');
var Base64=<base 64 content pdf file as string>;
var b = new Buffer(base64, 'base64')
var file = fs.createReadStream(b);
discovery.addDocument({ environment_id: 'xxx', collection_id: 'xxx', file: file, file_content_type: 'application/pdf', metadata: { "name": "Aparna", "Subject": "File" }},
function(error, data) {
console.log(data);
console.log(error); });
```

In this case, I am trying to provide input as a buffer for createReadStream. 

<img width="753" alt="screen shot 2018-07-16 at 1 25 15 pm" src="https://user-images.githubusercontent.com/14104686/42872994-d0a615be-8a6d-11e8-82da-8e6cc1418c6c.png">

In the above case, I get an issue from createReadStream itself
Error [ERR_INVALID_ARG_TYPE]: form-data: The "path" argument must be of type string without null bytes. Received type object
at nullCheck (fs.js:173:16)
at Object.fs.open (fs.js:648:8)
at ReadStream.open (fs.js:2047:6)
at new ReadStream (fs.js:2034:10)
at Object.fs.createReadStream (fs.js:1978:10)

**2nd Try**
I have also tried providing base64 encoded string directly but it didn't work. With this, I get file upload status is processing. But File ingestion failed. 

If I give Request input as {file: <localpath> }-- document gets uploaded.- local file path

If the input is base64 - {file : base64} - the document ingestion fails.
Decoding the encoded content, still, the document ingestion fails with node module.

**3rd Try**
var DiscoveryV1 = require('watson-developer-cloud/discovery/v1');
var fs = require('fs');

```
var discovery = new DiscoveryV1({
username: 'xxxx',
password: 'xxxx',
version_date: '2017-11-07',
file_content_type: 'application/pdf'
});
var base64 = "base64 encoded content added here"
var file = fs.readFileSync('sample1.pdf');

discovery.addDocument({ environment_id: 'xxx', collection_id: 'xxxx', file: file, file_content_type: 'application/pdf', metadata: { "name": "AparnaFile", "Subject": "sample" }},
function(error, data) {
console.log(data);
console.log(error);
}
);
```
 - the document ingestion fails in this case but status response is file is processing. 

**4th Try** using stream module
```

var DiscoveryV1 = require('watson-developer-cloud/discovery/v1');
var discovery = new DiscoveryV1({
username: 'xxxx',
password: 'xxxx',
version_date: '2017-11-07',
file_content_type: 'application/pdf'
});
var Readable = require('stream').Readable
var s = new Readable
s._read = () => {};
s.push(new Buffer(base64data,"base64").toString("binary") )   // the string you want send
s.push(null)

discovery.addDocument({ environment_id: 'xxx', collection_id: 'xxxx', file: s, file_content_type: 'application/pdf', metadata: { "name": "AparnaFile", "Subject": "sample" }},
function(error, data) {
console.log(data);
console.log(error);
}
);
```

**In all the above cases ingestion with no proper error message in Watson Discovery service UI. 
with no error in response when executing the above code.**

<img width="1193" alt="screen shot 2018-07-18 at 3 52 09 pm" src="https://user-images.githubusercontent.com/14104686/42875904-8e1953bc-8a74-11e8-8669-f8fd12395636.png">

**Is there a way to get to the full stack trace of the error message ?**

### When reporting a bug, please be sure to include the following:  
- [ ] Start the title with the service name in brackets:  `[speech-to-text] websockets...`
- [ ] Steps to reproduce provided
- [ ] Expected behavior provided
- [ ] Actual behavior -Able to upload base64 encoded string which is a file instead of using local file path
- [ ] Node version version 9
- [ ] SDK version latest

**Comment by dpopp07** [comment]
Hello @apasrini 

Is there a reason that you are wanting to pass a stream to the service? The service should accept a `Buffer` type as is. If you have the file available as a base 64 string, you can convert to a buffer with the following code:
```js
var fileAsBuffer = Buffer.from(fileAsString, 'base64');
```

I should not that the service will not accept a `String` as a value for `file`.

The code would look something like this:
```js
var DiscoveryV1 = require('./discovery/v1');
var fs = require('fs');

var discovery = new DiscoveryV1({
  username: '<username>',
  password: '<password>',
  version: '2016-11-07',
});

var Base64 = <base 64 content pdf file as string>;
var fileAsBuffer = Buffer.from(Base64, 'base64');

discovery.addDocument(
  {
    environment_id: '<environment_id>',
    collection_id: '<collection_id>',
    file: fileAsBuffer,
    file_content_type: 'application/pdf',
    metadata: { name: 'Aparna', Subject: 'File' },
  },
  function(error, data) {
    console.log(data);
    console.log(error);
  }
);
```

Please let me know if this solves your issue or not

**Comment by SowmyaGrama** [comment]
We are using REST API and passing data like below worked, hence closing issue.
```
formData:
            { file:
                { value: new Buffer(base64json,"base64"),//base64data - is base64 encoded file content
                    options:
                        { filename: 'working1.pdf'
                        }
                }
            }
```
