### ISSUE TITLE
[speech-to-text] transcribe mic to file example not working

### ISSUE THREAD

**Issue by dpopp07** [watson-developer-cloud/node-sdk#765]
Moving discussion from PR comment thread:

Thanks for looking into it @dpopp07 I am a still bit confused. If I understand this example correctly, it does a few things (please see the screenshot below):
* Listen to a mic and get audio stream from it;
* Pipe this audio stream to a file writer and get an audio file written to disk;
* Pipe the audio stream once again to Watson speech to text service and once the transcription is back, it gets written to a file (note: I am not looking at text to speech).

In my test, the transcription was all wrong, so that's where I started looking at that audio file recorded on disk and noticed that was wrong as well which in turn gave wrong transcription.

Sorry if I totally misunderstood the example. Please let me know what you think.

Thanks!

![image](https://user-images.githubusercontent.com/5871654/43692665-7056bd9c-98f7-11e8-8130-1dc1f65261e9.png)

(Note: I still use createRecognizeStream since the code uses recognizeUsingWebSocket is not published yet and it'd give me error message)

**Comment by qunliu** [comment]
Just as a FYI, not sure if you have gotten to this issue yet, I noticed the version watson-developer-cloud 3.8.0 is published and I gave it a try (using recognizeUsingWebSocket now), the issue is still there on my machine, basically the transcription is incorrect and recorded wav file is slow-mo.

Thanks for looking into it!

**Comment by dpopp07** [comment]
Hi @qunliu, I looked into this issue again today and the example worked fine for me as expected. The `mic` package can behave differently depending on your operating system, I wonder if that's the issue?

What OS are you using?

**Comment by qunliu** [comment]
Thanks for looking into it @dpopp07  We currently switched to use the browser based client lib (https://github.com/watson-developer-cloud/speech-javascript-sdk) which seems to be working fine for us now.

**Comment by dpopp07** [comment]
@qunliu Sounds good, I'll close this issue. Let me know if you run into problems again and I can re-open it
