### ISSUE TITLE
[Assistant] [Feature Request] Return rate limit information

### ISSUE THREAD

**Issue by catcher-in-the-try** [watson-developer-cloud/node-sdk#773]
There appears to be no way to get the rate limits information from the `response` from a call to any Assistant API.

According to the docs, the following headers are returned in the server response:

```
    X-RateLimit-Reset: the time the current timer expires (in UNIX epoch time)
    X-RateLimit-Remaining: the number of requests remaining in the current time window
    X-RateLimit-Limit: the total number of requests allowed within the time window
```

Please consider adding a way to retrieve those headers via the Node.js SDK.

I am using SDK v 3.9.0 on Node.js 10.6.0.

**Comment by germanattanasio** [comment]
You can do

```js
var assistant = new watson.AssistantV1({
/* username, password, version, url, etc... */
});

assistant.message(params,  function(err, result, response) {
  if (err)
    console.log('error:', err);
  else
    console.log(response.headers);
});
```

`response.headers` will have the rate limitation information you are looking for

**Comment by dpopp07** [comment]
Closing this issue. @catcher-in-the-try If you are still unable to access the headers, comment here and we will re-open the issue.

**Comment by matheusbsilva** [comment]
I couldn't get the information about Rate Limit using @germanattanasio example, the returned headers don't contain any info about Rate Limit, is there something I'm missing? My code:

```js
const AssistantV1 = require('ibm-watson/assistant/v1');

const service = new AssistantV1({
/* username, password, version, ... */
});

service.message({
  workspace_id: 'xxx',
  input: {'text': 'Hello'},
  return_response: 'true'
  })
  .then(res => {
    console.log(res.headers);
  })
  .catch(err => {
    console.log(err)
  });
```

**Comment by dpopp07** [comment]
@matheusbsilva Your code is correct, you're not missing anything. The only reason you are not seeing any rate limit headers is because you are using the `message` method.

According to the docs:
> There is no rate limit for this operation.

If you need to see the rate limit info for other operations, the way you've set up your code should work.

**Comment by matheusbsilva** [comment]
Thanks @dpopp07 ! Do you know any way that I can control the request rate limit to the Watson Assistant API? Because I was looking forward to use this headers to do this type of control.

**Comment by dpopp07** [comment]
You mean you want to limit your own requests you make to Watson Assistant? I'm not sure I fully understand the use case but you could try something like [this package](https://www.npmjs.com/package/bottleneck) to do that within your code.
