### ISSUE TITLE
[speech-to-text] Error: Session closed. Reason: Payload exceeds the 104857600 bytes limit.

### ISSUE THREAD

**Issue by daveyjones** [watson-developer-cloud/node-sdk#775]
My Node app has been working great for months, supporting continuous recognition for hours at a time. However, over the past few weeks, I've been getting the following error after about 20 minutes of usage:

> Error: Session closed. Reason: Payload exceeds the 104857600 bytes limit.

Here are the fundamental components of the Node app:

```
var mic = require("mic");
var watson = require("watson-developer-cloud/speech-to-text/v1");
var wav = require("wav");

var speechToText = new watson({
	url: "https://stream.watsonplatform.net/speech-to-text/api",
	username: "##########",
	password: "##########"
});

var micInstance = mic({rate: "44100", channels: "1", device: "sysdefault:CARD=PCH", debug: false});
var micInputStream = micInstance.getAudioStream();
var wavStream = new wav.Writer({sampleRate: 44100, channels: 1});

var recognizeStream = speechToText.recognizeUsingWebSocket({
	content_type: "audio/wav",
	customization_id: "##########",
	interim_results: true,
	objectMode: true,
	inactivity_timeout: 3600
});

micInputStream.pipe(wavStream);
wavStream.pipe(recognizeStream);
micInstance.start();
```
I understand that this error can occur when uploading a file that is too large, but in this case I'm working with a stream, so file size shouldn't be an issue.

**Steps to reproduce:** use the methods above to start a recognition stream. After approximately 20 minutes, recognition will stall due to the error noted above.

**Expected behavior:** continuous recognition for an indefinite amount of time (unless no speech is detected for 1 hour).

**Actual behavior:** continuous recognition for approximately 20 minutes until the error is thrown.

**Node version:** 10.9.0

**SDK version:** 3.9.1

**Comment by dpopp07** [comment]
Hi @daveyjones 
I'm looking into this issue. While I'm working on it, I wanted to ask - was there any concrete event that occurred in between the app working and no working?

As in, was it working fine until you updated your version of the Node SDK, installed a new Node version, used different parameters, etc? Or has everything been consistent and one day it just stopped working like it used to?

**Comment by dpopp07** [comment]
I ended up being busy this morning but was able to reproduce your issue this afternoon. The fact that it wasn't happening before, and started happening without anything on the client side changing, makes me lean towards thinking that it could be the service.

That said, another possibility that comes to mind is that backpressure is building up in the streams and chunks are getting larger and larger until they break the ~100mb limit (which I verified is an intentional limit for the service). I am going to investigate this some and will get back to you.

**Comment by dpopp07** [comment]
@daveyjones Just wanted to follow up - I spent most of yesterday messing around with the SDK streaming module to try and figure out if something is going on internally. I wasn't able to change the behavior at all, so I think the error is with the service and I would recommend submitting a bug report there.

I may revisit this in the future and will let you know if I find anything else. Please keep me updated if you hear anything from the service side.

**Comment by daveyjones** [comment]
@dpopp07 Thank you for continuing to investigate! I've reported this on the service side as well—I'll see what comes of that and continue to test on my end.

**Comment by daveyjones** [comment]
@dpopp07 Here's some more information. It seems that I get this error when testing on my MacBook but not on an Ubuntu box. The `mic` Node module is a wrapper around `arecord` on Linux and `sox` on Mac, which would explain the difference. So this may not actually be an issue with the SDK but rather with `mic` or possibly an underlying issue with `sox`. However, since the IBM examples use the `mic` module in examples, others will likely run into this issue.

**Comment by dpopp07** [comment]
@daveyjones Thanks for the follow up and for that information. I will investigate using a mic package with more consistent behavior for the example. I'll close this issue now
