### ISSUE TITLE
v4 Goals

### ISSUE THREAD

**Issue by dpopp07** [watson-developer-cloud/node-sdk#780]
## Breaking Changes
- [x] Start returning Promises **Seeking community feedback**
- [x] ~[speech-to-text] For `recognizeUsingWebSocket`, consider changing the default value of `objectMode` to `true`~ **Seeking community feedback**
- [x] Get rid of the compatibility layer
- [x] Remove support for Node 4.0
- [x] Update all dependencies
- [x] Remove LT v2
- [x] Remove Dialog
- [x] Remove Conversation
- [ ] Make the SDK more browser friendly
  - [x] `request` -> `axios` (or `fetch`)
  - [ ] Confirm browser package works in frameworks like React and Angular
  - [ ] Confirm package works in React Native
- [x] Filename is a required parameter for a number of methods (when the API wants filenames)
- [x] Remove code dealing with cookies
- [x] Remove support for JSON training data in NLC
- [x] Remove all code dealing with the old `api_key` for VR
- [x] [discovery] Remove compatibility support for array parameters in `query` and `federatedQuery`
- [x] Remove Personality Insights v2

## Non-breaking major changes
- [x] Update tests to use `jest` and be more readable
- [x] Rewire unit tests to be more modular and write more
- [x] Make integration tests more robust and less error-prone
- [x] Update error formatting to match APIs
- [ ] Create classes for each model in the services **Seeking community feedback**
- [ ] Services can be loaded independently using webpack

---
Would welcome some community feedback on some of these goals - do people want these things? Are there other implementations/packages we should be looking at? Any comments are appreciated!

**Comment by csantanapr** [comment]
I think is great to have support for promises, that way async/await can be used out of the box when calling this APIs.

**Comment by csantanapr** [comment]
Are we making progress towards to an mvp 4.x release?

**Comment by germanattanasio** [comment]
We are! The plan is to have an MVP ready next month

**Comment by csantanapr** [comment]
Thanks for the update

**Comment by mrutkows** [comment]
@germanattanasio  any update?

**Comment by dpopp07** [comment]
We are waiting until after THINK to release a new major version. There is also still some ongoing development work to meet the above goals. New estimate on the release is early March

**Comment by csantanapr** [comment]
@dpopp07 Hmm, can we get a basic 4.0 out, and then work on features for 4.1 ?

**Comment by dpopp07** [comment]
We can but we're working to get any breaking changes into 4.0. We're also coordinating with the other SDKs to make a synchronized major release. So there are a few moving parts. This is close to being ready

**Comment by dpopp07** [comment]
@csantanapr @mrutkows Once I finish a couple major issues I am working on, I will publish the v4.0 branch to npm as a beta release if you want to start looking at it. It should be mostly stable after these issues.

**Comment by dpopp07** [comment]
The release branch for v4.0.0 has been published as a release candidate on NPM. You can install this version with the tag `next` or `4.0.0-rc1`. This RC is stable and functional but more breaking changes _will_ be released. This RC includes support for Promises. A list of the changes made is documented here -> https://github.com/watson-developer-cloud/node-sdk/blob/v4.0.0-branch/UPGRADE-4.0.md.

I am continuing to update this document. Please post in this thread with any questions, comments, or bugs!

**Comment by csantanapr** [comment]
@dpopp07 @germanattanasio I started integrating the v4 library and found a problem
Some sub components instead need to use `v1-generated` as the import instead of `v1` like in 3.x
Why is that, it looks like some components use `v1` and some not.
For example discovery
```
const DiscoveryV1 = require('watson-developer-cloud/discovery/discovery/v1-generated');
```
instead of before 
```
var disco = require("watson-developer-cloud/discovery/v1")
```

**Comment by germanattanasio** [comment]
It should always be 
```
const DiscoveryV1 =  require("watson-developer-cloud/discovery/v1")
```

This looks like an error.

**Comment by csantanapr** [comment]
@germanattanasio I see it in a couple of places

https://github.com/watson-developer-cloud/node-sdk/search?q=v1-generated&unscoped_q=v1-generated

**Comment by dpopp07** [comment]
@csantanapr Yes, that is a mistake. I will correct that and let you know when the fix is released.

**Comment by csantanapr** [comment]
Thank you 🙏🏻

**Comment by dpopp07** [comment]
@csantanapr Fix has been released. Use `watson-developer-cloud@4.0.0-rc2` or `watson-developer-cloud@next` to install.

**Comment by csantanapr** [comment]
what's the ETA for 4.x?

**Comment by dpopp07** [comment]
The scheduled date is **next Friday, 3/29**.

Still some work to be done, but that date should not be pushed back anymore.

**Comment by csantanapr** [comment]
I don’t believe it, proof me wrong 😺

**Comment by dpopp07** [comment]
🚀🚀🚀 Okay it's official! Watson Node SDK `v4.0.1` has been released! 🚀🚀🚀

This is the official version for the major release. `v4.0.0` was used for beta testing so do not use that version - use `4.0.1` or `latest` to install it. Full list of breaking changes in [the migration guide](https://github.com/watson-developer-cloud/node-sdk/blob/master/UPGRADE-4.0.md).

@csantanapr It actually went out last night, so one day ahead of schedule 😉 

Thanks to everyone who posted here with feedback on this release. Please open issues with any bugs or feature requests you come up with.

**Comment by csantanapr** [comment]
Thanks that’s great achievement folks :-)
