### ISSUE TITLE
[assistant] How to know the workspace rate limit before hitting exception?

### ISSUE THREAD

**Issue by psyntium** [watson-developer-cloud/node-sdk#791]
when creating workspace using createWorkspace, you'll get "Maximum workspaces limit exceeded. Limit = 5" if you're trying to create more than 5 workspaces.

How do we know the limit using the sdk?

using the API, I can see that this can be seen from the following:
https://assistant-us-south.watsonplatform.net/rest/v1/limits

**Comment by germanattanasio** [comment]
You can look at the response header. Check the README: https://github.com/watson-developer-cloud/node-sdk#parsing-http-response.
