### ISSUE TITLE
[visual-recognition] Connection timeout

### ISSUE THREAD

**Issue by KerimG** [watson-developer-cloud/node-sdk#793]
Steps to reproduce:

Trying to classify image with following code:

```JS
var visual_recognition = new VisualRecognitionV3({
  apikey: "...",
  version: "v3",
  version_date: "2016-05-20"
});

var params = {
  classifier_ids: ["..."],
  images_file: fs.createReadStream(imageFileName)
};

visual_recognition.classify(params, (result) => {
  
});
```

Expected behavior: 

result Object contains success field along with classification of image.

Actual behavior:

```
{ Error: connect ETIMEDOUT 54.209.159.70:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '54.209.159.70',
  port: 443 }
```

Node v8.11.1

SDK Version v3.12.0

**Comment by dpopp07** [comment]
Hi @KerimG 
This is almost certainly due to the fact that there are no more instances of Visual Recognition using `apikey` for authentication, so you are trying to hit a service instance that either doesn't exist or has been migrated to use IAM.

See [this section of the README](https://github.com/watson-developer-cloud/node-sdk#authentication) for more info on authenticating with IAM.

**Comment by KerimG** [comment]
@dpopp07 

Thanks for the information. I recreated my service with IAM authentication and now it works. What's a bummer is something like this can break out of nowhere. This service worked fine just a few weeks ago.

**Comment by dpopp07** [comment]
Yes, agreed. Usually when breaking changes happen, we can insulate the SDK with code to ensure compatibility but with a change that big, there isn't much we can do other than notify users. That kind of change is very rare and will hopefully continue to be!

Going to close this issue, feel free to open another if you have other problems with the SDK.
