### ISSUE TITLE
Can I really send a buffer to Watson Speech to Text?

### ISSUE THREAD

**Issue by lizcmoreira** [watson-developer-cloud/node-sdk#811]
I'm trying to send an audio to Watson Speech to Text as follows:

1) I record an audio in the microphone.
2) I store the data in a Buffer.
3) I send the Buffer to Watson to convert to text.

So far so good, because the data arrives there the way it came out, but it seems to me that Watson does not accept the Buffer to do the conversion. Which does not make much sense, because in the Request part of the documentation it says that Watson can receive a buffer.

![error2](https://user-images.githubusercontent.com/29645173/49662767-de05d380-fa33-11e8-9d3a-e9bab89c5352.PNG)

What is going on?

It gives the following error:

![error](https://user-images.githubusercontent.com/29645173/49662781-e6f6a500-fa33-11e8-9657-93dd64158159.PNG)

Note: The Buffer in this image is the audio that was send to Watson and should be converted to text.

**Comment by dpopp07** [comment]
@lizcmoreira Thanks for the issue. This is a bug in the SDK. It will be resolved in #824
