### ISSUE TITLE
Missing grammer at speech to text

### ISSUE THREAD

**Issue by vincentbouillart** [watson-developer-cloud/node-sdk#827]
Hi, I discovered in the watson docs the beta functionality to pass in a custom grammer name or add one or delete one like this grammar_name=name-of-my-grammar but when i go to the docs It seems to me that it's only available via http calls ? (i went trough the code and found it)

https://cloud.ibm.com/apidocs/speech-to-text?language=node#list-grammars

When i go to the api docs and select the node code option to see how to use it, it disappears so i think there is a bug in the api docs.

**Comment by dpopp07** [comment]
@vincentbouillart Thanks for the issue - I was seeing what you described a couple days ago but it seems to be working now. Can you confirm that you can see that section now?

**Comment by vincentbouillart** [comment]
It works now ! great tnx !
