### ISSUE TITLE
[visual-recognition] SDK Still contains old Beta Methods

### ISSUE THREAD

**Issue by huhlig** [watson-developer-cloud/node-sdk#838]
The Visual Recognition sdk contains unimplemented methods that throw a Beta Error. These Should be removed or implemented.

https://github.com/watson-developer-cloud/node-sdk/blob/master/visual-recognition/v3.ts#L43

**Comment by dpopp07** [comment]
@huhlig Thanks for the issue. These methods will be removed in the next major version of the SDK, which we plan to release early next month.

For an early look at the new major version, see the [v4 branch](https://github.com/watson-developer-cloud/node-sdk/tree/v4.0.0-branch) or install the version `4.0.0-rc1` from NPM.

To see or discuss other planned changes for this next major release, see the [v4 goals tracking issue](https://github.com/watson-developer-cloud/node-sdk/tree/v4.0.0-branch).
