### ISSUE TITLE
[text-to-speech] Cannot read property .on fo undefined in synthesize.js

### ISSUE THREAD

**Issue by spyderman4g63** [watson-developer-cloud/node-sdk#843]
I'm seeing an error when trying to run the following command from the STT/TTS lab manual:
`node synthesize.js --text_file data/JSON_text.json --out_file JSON_text.wav`

the error is:
```
MacBook-Pro-3:TTS jward$ node synthesize.js --text_file data/JSON_text.json --out_file JSON_text.wav >
 error.txt
/Users/jward/Desktop/speech_lab_assets/TTS/synthesize.js:72
text_to_speech.synthesize(params).on('error', function(error) {
                                 ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/Users/jward/Desktop/speech_lab_assets/TTS/synthesize.js:72:34)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```
the code in question is this section:
```
text_to_speech.synthesize(params).on('error', function(error) {
  console.log('Error! Code:'+ error.code +' Type: '+error.code_description+ ' Message: '+error.error);
}).pipe(fs.createWriteStream(args.out_file));
```
If I output text_to_speech.synthesize(params) it is always undefined.

I have noticed that a lot of the functions in the SDK have changed. Did synthesize get renamed?

Node version: v10.8.0
SDK version: watson-developer-cloud@4.0.0

**Comment by dpopp07** [comment]
Hey @spyderman4g63 

I see you are using v4.0.0. The current version of the SDK is `3.18.1` and the examples are written based on version 3.x.

v4 is currently in development and has been released as a beta for developers that want to try it out or use experimental features. It includes breaking changes - one of which is that non-WebSocket methods no longer return streams, they return Promises. This is why you're seeing the error.

For the current examples to be relevant, switch your version to `3.18.1` or `@latest`.

If you want to start working with v4 (currently planned to release this month), install version `4.0.0-rc2` or `@next` and see the [migration document](https://github.com/watson-developer-cloud/node-sdk/blob/v4.0.0-branch/UPGRADE-4.0.md) for details on the breaking changes.

**Comment by spyderman4g63** [comment]
Thanks for the reply. I've install watson-developer-cloud@3.18.1 but I'm seeing the same behavior. 

I've confirmed that the params var actually contains some values:
```
{ text: 'JSON objects are common when using Watson products.',
  voice: 'en-US_AllisonVoice',
  accept: 'audio/wav',
  customization_id: '1a184c42-8d8c-4902-8576-3fb5ccc2114e' }
```

However `text_to_speech.synthesize(params)` is still undefined.

**Comment by dpopp07** [comment]
Oh okay, I think I know what's going on. Are you using IAM for authentication? Returning streams doesn't work well with IAM, which is a small part of the reason we're abandoning returning streams in the next major release. That example should probably be updated.

Your best option moving forward is to use a callback and stream the result:
```js
text_to_speech.synthesize(params, (err, res) => {
  if (err) {
    console.log(err);
  } else {
    res.pipe(fs.createWriteStream('audio.wav'); // or whatever you want to do with the stream
  }
});
```

Let me know if that solves your issue or not.

**Comment by dpopp07** [comment]
@spyderman4g63 what is the status on this?

**Comment by riderjensen** [comment]
@dpopp07 I had the same issue as @spyderman4g63. Your solution didnt work for me since the res that I was getting was not a stream. I got an error that res.pipe() is not a function. Instead, I found that simply writing to a file instead of using a stream worked:

`const TextToSpeechV1 = require('watson-developer-cloud/text-to-speech/v1');
const fs = require('fs');

const textToSpeech = new TextToSpeechV1({
  iam_apikey: '{your api}',
  url: '{your URL}'
});

const synthesizeParams = {
    text: 'Hello world',
    accept: 'audio/wav',
    voice: 'en-US_AllisonVoice'
  };
  
  textToSpeech.synthesize(synthesizeParams, function (err, buffer) {
    if (err) {
      console.log(err);
    } else {
        const d = new Date();
        fs.writeFile(`./audio-${d.getSeconds()}-${d.getMinutes()}-${d.getHours()}.wav`, buffer, () => {
            console.log('File is written')

        })
    }
  });`

**Comment by dpopp07** [comment]
@riderjensen Ah yes, that is correct. My mistake. `synthesize` will return a result of type `Buffer`.

However, in the next major release, v4, `synthesize` will return a Stream.

Thanks for the correction, it seems that this specific problem is resolved for now so I will close the issue.
