### ISSUE TITLE
Error Modules not found building on Angular CLI project.

### ISSUE THREAD

**Issue by npacucci** [watson-developer-cloud/node-sdk#864]
Hi, 
I'm trying to build the SDK v.4.0.1 inside my Angular CLI project but I get the following errors:

> Module not found: Error: Can't resolve 'fs'
> Module not found: Error: Can't resolve 'https'
> Module not found: Error: Can't resolve 'os'
> Module not found: Error: Can't resolve 'path'
> Module not found: Error: Can't resolve 'stream'

I know that the problem is like #770, so there are some dependencies that are not supposed to work in the browser. 

**But I'm asking you if will be possible to have an SDK more browser-friendly in the future?**

**SDK Version**
ibm-watson: 4.0.1
@angular/core: 7.2.6
@angular/cli: 7.3.2,
@angular/compiler-cli: 7.2.6.

**Comment by dpopp07** [comment]
It is definitely our desire to have the SDK be more browser friendly but I don't know what the timeline on making that happen is. If you have any ideas about the best ways to do that, feel free to open a feature request or better yet, a PR!

**Comment by dpopp07** [comment]
@npacucci Please see if this is fixed in version 5.0.0 and let me know!

**Comment by npacucci** [comment]
Hi @dpopp07 , I tried using the 5.1.0 version, but the building doesn't work yet without the [Webpack Configuration](https://github.com/watson-developer-cloud/node-sdk/tree/master/examples/webpack).

I get the following errors:

```
ERROR in ./node_modules/jwa/index.js
Module not found: Error: Can't resolve 'crypto' in '**\node_modules\jwa'

ERROR in ./node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js
Module not found: Error: Can't resolve 'https' in '**\node_modules\ibm-cloud-sdk-core\lib'

ERROR in ./node_modules/ibm-watson/lib/common.js
Module not found: Error: Can't resolve 'os' in '**\node_modules\ibm-watson\lib'

ERROR in ./node_modules/ibm-cloud-sdk-core/lib/content-type.js
Module not found: Error: Can't resolve 'path' in **\node_modules\ibm-cloud-sdk-core\lib'

ERROR in ./node_modules/ibm-cloud-sdk-core/lib/helper.js
Module not found: Error: Can't resolve 'path' in '**\node_modules\ibm-cloud-sdk-core\lib'

ERROR in ./node_modules/mime-types/index.js
Module not found: Error: Can't resolve 'path' in '**\node_modules\mime-types'

ERROR in ./node_modules/isstream/isstream.js
Module not found: Error: Can't resolve 'stream' in '**\node_modules\isstream'

ERROR in ./node_modules/jws/lib/verify-stream.js
Module not found: Error: Can't resolve 'stream' in '**\node_modules\jws\lib'

ERROR in ./node_modules/jws/lib/sign-stream.js
Module not found: Error: Can't resolve 'stream' in '**\node_modules\jws\lib'

ERROR in ./node_modules/jws/lib/data-stream.js
Module not found: Error: Can't resolve 'stream' in '**\node_modules\jws\lib'
```
Compared to the previous version the 'fs' library is not yet necessary, but it seems that there are still these dependencies that need a browser polyfill: 
- crypto
- https
- os
- path
- stream

So the [Webpack Configuration](https://github.com/watson-developer-cloud/node-sdk/tree/master/examples/webpack) is still needed.

**Comment by dpopp07** [comment]
@npacucci Thanks for getting back to me and alerting us about the issue - we are looking into it now

**Comment by christiancompton** [comment]
@npacucci Can you share your tsconfig.json?  I am working on addressing this, but want to make sure my changes will work with your configuration.

**Comment by npacucci** [comment]
Hi @christiancompton , here is my **tsconfig.json**:

> {
>    "compileOnSave": false,
>    "compilerOptions": {
>     "baseUrl": "./",
>     "outDir": "./typescript-output/compiled",
>     "sourceMap": true,
>     "declaration": false,
>     "downlevelIteration": true,
>     "emitDecoratorMetadata": true,
>     "experimentalDecorators": true,
>     "module": "esnext",
>     "moduleResolution": "node",
>     "importHelpers": true,   
>     "target": "es5",
>     "typeRoots": [
>       "node_modules/@types"
>     ],
>     "lib": [
>       "es2017",
>       "dom"
>     ]
>   },
>   "angularCompilerOptions": {  
>     "fullTemplateTypeCheck": false,
>     "strictInjectionParameters": false,
>     "preserveWhitespaces": false,
>     "skipAotRemoveDecorators": true,
>     "enableAotReplaceResolver": true,
>     "trace": false
>   }
> }
> 

I also have a tsconfig extension **tsconfig.app.json**:

> {
>   "extends": "../tsconfig.json",
>   "compilerOptions": {   
>     "baseUrl": "./",
>     "outDir": "../typescript-output/compiled/src",
>     "sourceMap": false,     
>     "types": []
>   },
>   "exclude": [
>     "test.ts",
>     "**/*.spec.ts"
>   ],
>   "angularCompilerOptions": {
>     "enableIvy": false
>   }
> }


**Angular version 8.2.3**

**Comment by dpopp07** [comment]
We still want to fix this
