### ISSUE TITLE
TypeError: fs.existsSync is not a function, instantiating an Assistant2 with Webpack config. 

### ISSUE THREAD

**Issue by npacucci** [watson-developer-cloud/node-sdk#865]
Hi,
I'm trying to instantiate a new Assistant2 object as described in the official doc: https://cloud.ibm.com/apidocs/assistant-v2?locale=it&code=node#send-user-input-to-assistant. 
So I did this:

```js
const AssistantV2 = require('ibm-watson/assistant/v2');

const assistant = new AssistantV2({
  version: '{version}',
  iam_apikey: '{apikey}',
  url: '{url}'
});
```

But at runtime I get the following error:

> Error: Uncaught (in promise): TypeError: fs.existsSync is not a function
> TypeError: fs.existsSync is not a function
>     at fileExistsAtPath (read-credentials-file.js:40)
>     at Object.readCredentialsFile (read-credentials-file.js:25)
>     at AssistantV2.push../node_modules/ibm-cloud-sdk-core/lib/base_service.js.BaseService.initCredentials (base_service.js:236)
>     at AssistantV2.BaseService (base_service.js:98)
>     at new AssistantV2 (v2.js:57)

Before this, I implemented the Webpack configuration as described here (to workaround the Angular CLI build): https://github.com/watson-developer-cloud/node-sdk/tree/master/examples/webpack. 
So I did this inside my webpack config:

```
  node: {
    // see http://webpack.github.io/docs/configuration.html#node
    // and https://webpack.js.org/configuration/node/
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  },
```

Therefore, setting the 'fs' module as an empty object is not good in this case.

### 
**But does the Assistant2 really need the 'fs' library since I have passed the credentials manually in my code instead of through the ibm-credentials.env file?**

**Expected behavior**
Works correctly at runtime without using the 'fs' library since I have passed the credentials manually in my code instead of through the ibm-credentials.env file.

**Actual behavior**
 TypeError: fs.existsSync is not a function. Because it uses the 'fs' library regardless.

**SDK Version**
ibm-watson: 4.0.1

**Additional information:**
- Implemented the Webpack solution as described here: https://github.com/watson-developer-cloud/node-sdk/tree/master/examples/webpack.

**Comment by dpopp07** [comment]
@npacucci I do see the issue, it makes an attempt to read from the credentials file whether you have provided credentials or not. This is unnecessary and I can look into posting a fix for this soon.

In the meantime though, have you tried using your own polyfill - [something like this](https://www.npmjs.com/package/browserfs)?

**Comment by npacucci** [comment]
In the meantime I tried to use the polyfill and it works, but after I get a runtime error such as:

> Error: Uncaught (in promise): TypeError: Invalid Version: v5.0
> TypeError: Invalid Version: v5.0
>     at new SemVer (semver.js:323)
>     at Range.push../node_modules/semver/semver.js.Range.test (semver.js:1203)
>     at Function.satisfies (semver.js:1257)
>     at AssistantV2.BaseService (base_service.js:93)
>     at new AssistantV2 (v2.js:57)

Probably there is a problem with the SemVer RegEx inside the `semver.satisfies(process.version, '4.x')` method. My process.version is 'v5.0' but if I try to change it at runtime to '5.0.0' it works.

This is the code that throws the TypeError:
```
var m = version.trim().match(options.loose ? re[LOOSE] : re[FULL])

  if (!m) {
    throw new TypeError('Invalid Version: ' + version)
  }
```

In any case, even changing the process.version at runtime, I subsequently get errors related to the CORS policy:

> Access to XMLHttpRequest at 'https://iam.bluemix.net/identity/token' from origin 'http://localhost:5001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**So the Assistant2 doesn't support the CORS?**

**Comment by npacucci** [comment]
In summary, this is my situation: 

I've a web application (Angular CLI project) and I would simply like to call client side (Typescript / Javascript) the Assistant2 APIs (createSession, message, deleteSession), it's possible to do it now? I don't understand what I should do.

I think that the most correct solution is to have a pure Assistant2 browser library, as the [`watson-speech`](https://www.npmjs.com/package/watson-speech) npm package for the speech to text.

I strongly believe in your assistant and I think that giving the possibility to make it work in any web app with minimal code would be very awesome and powerful! 

So I'll wait for word  :)

**Comment by germanattanasio** [comment]
@npacucci We are working on a fix for this. I will make sure it gets addressed

**Comment by germanattanasio** [comment]
@npacucci assistant supports CORS but the IAM server that we use to get an access token seems to not. I would suggest you move the access token to an api in your app
```
GET /api/token
```

and then use the token as access token in your application so that you don't need to call the IAM url from the browser
