### ISSUE TITLE
Include commitlint.config.js in repo

### ISSUE THREAD

**Issue by MasterOdin** [watson-developer-cloud/node-sdk#867]
When attempting to make a commit to this repo, the commit message is checked by husky to ensure it follows proper paradigm. However, it's confusing that on the first attempt to make a commit, they get the following error message:
```
⧗   input: Test test test
✖   Please add rules to your `commitlint.config.js`
    - Getting started guide: https://git.io/fhHij
    - Example config: https://git.io/fhHip [empty-rules]
✖   found 1 problems, 0 warnings
    (Need help? -> https://github.com/conventional-changelog/commitlint#what-is-commitlint )
```
and now the user has to look at getting started for using commitlint and just hope that you folks aren't deviating from the default in any way.

**Comment by dpopp07** [comment]
@MasterOdin Thanks for the issue - we were actually just looking at that this morning. A fix should be posted soon
