### ISSUE TITLE
TextToSpeechV1 is missing the plain synthesize method

### ISSUE THREAD

**Issue by lorimbrius** [watson-developer-cloud/node-sdk#879]
The [examples](https://github.com/watson-developer-cloud/node-sdk/blob/master/examples/text_to_speech.v1.js) and [API docs](https://cloud.ibm.com/apidocs/text-to-speech?code=node#synthesize-audio) show TextToSpeechV1 having a plain synthesize method in addition to the synthesizeUsingWebSocket method but that seems to be missing:

```typeScript
import SynthesizeStream = require('../lib/synthesize-stream');
import GeneratedTextToSpeechV1 = require('./v1-generated');
declare class TextToSpeechV1 extends GeneratedTextToSpeechV1 {
    constructor(options: any);
    /**
     * Repair the WAV header of an audio/wav file.
     *
     * @param {Buffer} wavFileData - Wave audio - will be edited in place and returned
     * @return {Buffer} wavFileData - the original Buffer, with a correct header
     */
    repairWavHeader: (wavFileData: any) => any;
    /**
     * Use the synthesize function with a readable stream over websockets
     *
     * @param {Object} params The parameters
     * @return {SynthesizeStream}
     */
    synthesizeUsingWebSocket(params: any): SynthesizeStream;
}
export = TextToSpeechV1;
```

**Comment by dpopp07** [comment]
The code you posted is from the helper file, not the file with the primary methods. The HTTP synthesize function is [here](https://github.com/watson-developer-cloud/node-sdk/blob/master/text-to-speech/v1-generated.ts#L260) and should be accessible.

Going to close this issue - please re-open if you are having trouble calling the method and we will help you out
