### ISSUE TITLE
[discovery] multiple collection query for node sdk fails to work.

### ISSUE THREAD

**Issue by donovat** [watson-developer-cloud/node-sdk#882]
**Multiple Collection Query - federatedQuery fails to work**
Calling SDK API;
   discovery.federatedQuery(queryParams, (error, results) =>{
fails with either error Missing collection_id or collection_id's cannot be empty

The SDK documentation states; 
collection_ids
string
A comma-separated list of collection IDs to be queried against. Required when querying multiple collections, invalid when performing a single collection query.
https://cloud.ibm.com/apidocs/discovery?code=node

I have tried a number of examples;
collection_id: "f0744d9d-b460-4601-99d5-8f24afXXXXX, 23713373-9be6-42c5-82e6-954a667aXXXX" // taken as one string in json
collection_id: "f0744d9d-b460-4601-99d5-8f24afXXXXX", "23713373-9be6-42c5-82e6-954a667aXXXX" // breaks json format
collection_id: ["f0744d9d-b460-4601-99d5-8f24afXXXXX", "23713373-9be6-42c5-82e6-954a667aXXXX"] // json array object

**Multiple Version dates**
Running in IBM Cloud Function - so not sure which they load by default. 
const DiscoveryV1 = require('watson-developer-cloud/discovery/v1');

Note: The documentation noted below, is missing a good example and is poor.

**Comment by mediumTaj** [comment]
Closing as the issue was using `collection_ids` rather than `collection_id`

**Comment by donovat** [comment]
update: was using collection_id rather than collection_ids. ( wrong way round above). 
And then the correct use is:
collection_ids: "f0744d9d-b460-4601-99d5-8f24afXXXXX, 23713373-9be6-42c5-82e6-954a667aXXXX"

**Comment by mediumTaj** [comment]
sorry i meant that to read that the solution was to use `collection_ids` rather than `collection_id`
