### ISSUE TITLE
natural-language-understanding set language to english

### ISSUE THREAD

**Issue by cyruslk** [watson-developer-cloud/node-sdk#887]
Hello, i'm using the [natural-language-understanding](https://github.com/watson-developer-cloud/node-sdk#natural-language-understanding) feature and when I parse the text, this error is being outputed: `natural-language-understanding`. How can I set the language to english?

Thanks!

```
 name: 'Bad Request',
  code: 400,
  message: 'unsupported text language',
  body: '{"error":"unsupported text language","code":400}',
  headers:
   { 'x-backside-transport': 'FAIL FAIL',
     'content-type': 'application/json; charset=utf-8',
     'cache-control': 'no-cache, no-store',
     'x-dp-watson-tran-id': 'gateway02-248674833',
     'content-security-policy': "default-src 'none'",
     pragma: 'no-cache',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'DENY',
     'x-xss-protection': '1; mode=block',
     'x-global-transaction-id': 'ffea405d5cddc1b70ed27a11',
     'x-dp-transit-id': 'gateway02-248674833',
     'strict-transport-security': 'max-age=31536000;',
     'content-length': '80',
     'x-edgeconnect-midmile-rtt': '45',
     'x-edgeconnect-origin-mex-latency': '108',
     date: 'Thu, 16 May 2019 20:01:59 GMT',
     connection: 'close',
     vary: 'Accept-Encoding' }
```

**Comment by dpopp07** [comment]
Hey @cyruslk 

Will you post your request snippet so I can see what you are doing?

**Comment by cyruslk** [comment]
Hey @dpopp07 ,

Thanks so much for the quick reply. I'm using the default example you shared in your README but I don't see where/how to specify the language. 

```
     const returnNluData = (selectedString) => {
       nlu.analyze({
        html: selectedString,
        features: {
          concepts: {},
          keywords: {}
      }})
        .then(result => {
          return JSON.stringify(result, null, 2);
        })
        .catch(err => {
          console.log('error:', err);
        });
     }
```

**Comment by dpopp07** [comment]
The language can be specified using the `language` parameter and is automatically detected by the service if the language is not explicitly set. The [NLU docs](https://cloud.ibm.com/apidocs/natural-language-understanding?code=node#analyze-text) can give you more information. Let me know if this helps!

**Comment by cyruslk** [comment]
Hey there --

So this is the way it has to be implemented, right?

```
    nlu.analyze(
          {
            text: string,
            language: "en",
            features: {
              concepts: {},
              keywords: {}
            }
          })
          .then(result => {
            console.log(JSON.stringify(result, null, 2));
          })
          .catch(err => {
            console.log('error:', err);
      });
```

**Comment by cyruslk** [comment]
What I don't get is that when I'm using this block of code for the following text:

` But whoa the required facts are reached through a potent sympathy and far-rsacbing activity, the collecting agent :s tho nu'trcpolitan newspaper`

I get no keywords.

But when I use your online demo: https://natural-language-understanding-demo.ng.bluemix.net/

I get keywords:

```
{
 "keywords": [
  {
   "text": "potent sympathy",
   "relevance": 0.758625,
   "count": 1
  },
  {
   "text": "rsacbing activity",
   "relevance": 0.66507,
   "count": 1
  },
  {
   "text": "facts",
   "relevance": 0.634791,
   "count": 1
  },
  {
   "text": "collecting agent",
   "relevance": 0.548826,
   "count": 1
  },
  {
   "text": "nu'trcpolitan newspaper",
   "relevance": 0.365943,
   "count": 1
  }
 ]
}
```
Is there something I'm doing wrong here?

**Comment by dpopp07** [comment]
@cyruslk I just made an attempt to reproduce your issue using the SDK and received the same response that you posted from the online demo.

I don't think you are doing anything wrong. I wonder if you are using an older version of the service. What date are you passing in for the `version` parameter in the service constructor?

**Comment by cyruslk** [comment]
Hello @dpopp07 -This is what I'm passing in the service constructor:

```
var nlu = new NaturalLanguageUnderstandingV1({
    url: "https://gateway.watsonplatform.net/natural-language-understanding/api",
    version: '2018-04-05',
    iam_apikey: config.iam_apikey,
    iam_url: "https://iam.bluemix.net/identity/token",
    language: "en"
});
```

Is there an error here?

**Comment by dpopp07** [comment]
@cyruslk No, I don't see an error. In fact, I am using your exact configuration and I get the correct response. I am not really sure why you would not be getting keywords back, but the only difference between your set up and mine is the instance of the service we are using.

@mediumTaj do you know of any reason NLU would not return keywords for a specific instance?

**Comment by dpopp07** [comment]
@cyruslk I am asking around internally about this issue. Will you post the response that you _do_ get when using the SDK?

**Comment by dpopp07** [comment]
@cyruslk Any updates here?
