### ISSUE TITLE
Tone-Analyzer input parameters 

### ISSUE THREAD

**Issue by maxagabb** [watson-developer-cloud/node-sdk#889]
Hello,
I'm trying to run the browserify example with the Watson Tone-Analyzer. 

**Overview**

There seems to be an issue with the way input is given to the tone method of the toneAnalyzer. 

**Expected behavior**
By default I expected the result of the method to be tone-analysis of the text-area in JSON format. 

**Actual behavior**
Running the code as is results in the following error: 
```Error: Missing required parameters: tone_input ```

**Fix for issue**
Calling the tone method with the following returned JSON results. 
```     
  toneAnalyzer.tone(
    {
          tone_input: { 'text': input.value },
    },
```
**How to reproduce**
I was originally having trouble running the sample code because of a CORS issue. I ended up calling the tone method server side with a POST request. The following code returned JSON results for me. 

This is the route handling in server.js:
```     
app.post('/analyze', function(req, res, next) {
  toneAnalyzer.tone(
    {
          tone_input: { 'text': req.body.text },
    },
    function(err, result) {
      if (err) {
        return console.log(err);
      }
      console.log("before return",JSON.stringify(result, null, 2));
      res.send(JSON.stringify(result, null, 2));
      res.end("finished request");
    }
  );
```
Here is the post request made in client.js:
```     
btn.onclick = function() {
  console.log(input.value);
  var xhr = new XMLHttpRequest();
  xhr.open("POST", 'http://localhost:3000/analyze', true);
  xhr.setRequestHeader('Content-Type', 'application/json');
  xhr.send(JSON.stringify({"text": input.value}));
};
```

**Comment by dpopp07** [comment]
So your error is that you are unable to run from the browser because of a CORS issue?

Are you using the parameter `iam_apikey` to authenticate with the service. That parameter tells the SDK to make a request to the IAM service to get an access token. Requests to the IAM service cannot be made from the browser for security reasons, so you may need to move the authorization component to the server and then authenticate with `iam_access_token` in the browser. Let me know if that will work for you.

**Comment by maxagabb** [comment]
Thanks for the reply!

I resolved my CORS by instantiating a ToneAnalyzerV3 object with an
iam_apikey in the server. I can now get the JSON results by making a server
request.

If I'm remembering correctly, after resolving the CORS issue that's when
the tone analyzer input became a problem which was fixed with the solution
in my post.

**Comment by dpopp07** [comment]
No problem! So is this resolved now or are you still having any problems?

**Comment by maxagabb** [comment]
I have no more problems, so I'll go ahead and close the issue.
