### ISSUE TITLE
v1.0.0 goals

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/node-sdk#89]
Hey @germanattanasio and @jsstylos, I think we should target a 1.0 release sometime soon and then start sticking to semver for releases. 

Things we want to have before releasing 1.0 (you can edit this to add more):
- [x] Resolve beta/experimenta/ga differentiation issues (#35 & #43)
- [x] Replace Speech to Text REST API with one that uses WebSockets (discussion on #91) (?)
- [x] Deprecate most of document conversion API (?)

**Comment by germanattanasio** [comment]
:+1:

**Comment by jsstylos** [comment]
Other than beta/experimental versioning, are there any other breaking changes we should make when we're going to 1.0? Removing support for legacy parameter names or any other deprecated features?

**Comment by nfriedly** [comment]
One idea that crossed my mind was to start using named parameters instead of a hash. I think it makes a lot of sense in some places (like commands that only accept 0 or 1 parameters). But it's a fairly significant change and doesn't doesn't get us that much of an improvement. So I'm kind of leaning towards no. But if we want to do it, 1.0 is a good place to do so.

**Comment by jsstylos** [comment]
I like the simplicity and consistency of having a JSON object for all of the parameters, though I see how in the case of simple services there might be a small gain having named parameters. I'd probably leave it out of 1.0. (We can also add it later if we want, as long as we support the JSON object method also.)

**Comment by jsstylos** [comment]
One issue that's come up a couple of times is whether to prefer explicitly specified credentials or VCAP_SERVICES credentials when both exist. A user had a bug with this today, where having to pass use_vcap_services=false in order to use the explicitly set credentials was not expected. By switching the order of the arguments to extend to `options = extend({}, service.credentials, options);` we would give preference to explicitly set credentials, which would likely avoid these types of user bugs. (This is a breaking change, so I'm adding it as a comment to the v1.0 issue.)

**Comment by nfriedly** [comment]
Yea, I think that makes sense to default to the explicitly set ones.

**Comment by nfriedly** [comment]
Relatedly, I think we should ship a `bluemix-lite` module that *just* parses `VCAP_SERVICES` and returns credentials. The other one has a boatload of dependencies.

**Comment by nfriedly** [comment]
or we could name the new one `vcap-services`

**Comment by nfriedly** [comment]
vcap services module released: https://www.npmjs.com/package/vcap_services

**Comment by nfriedly** [comment]
#110 is done in the [v1.0](https://github.com/watson-developer-cloud/node-sdk/tree/v1.0) branch, so I checked off the box for STT websockets. Right now, the older methods are still present but give a warning message that they are deprecated and will be removed in a future release. 

(That part is only [a few lines of code](https://github.com/watson-developer-cloud/node-sdk/blob/v1.0/services/speech_to_text/v1.js#L529), so you could copy it into master, do a patch release, and then actually delete them from v1.0 if you want.)

Ditto for document conversion.

**Comment by nfriedly** [comment]
Can we remove `search` and/or `tone_analyzer v1`? Any other services that we can/should remove?

**Comment by nfriedly** [comment]
Oh, also, `message_resonance`? (not sure about that one)

**Comment by germanattanasio** [comment]
![f258f40627b8f0f4b0734de2f709e154](https://cloud.githubusercontent.com/assets/313157/10748846/7f64a862-7c3a-11e5-8f23-0ff50f479c13.jpg)

**Comment by nfriedly** [comment]
cool, mr, ta v1, and search are all gone now.

**Comment by nfriedly** [comment]
And, I've now updated the readme with a list of breaking changes. I think we're ready to go.

Do we want to test this out by updating several of our demo apps first? 

We can change the dependency in package.json from `^v0.10.6` or whatever to `https://github.com/watson-developer-cloud/node-sdk#v1` and npm will download the current v1 branch. (Note: I think bluemix caches it and doesn't check for updates unless you set the `NODE_MODULES_CACHE=false` environment property.)

**Comment by nfriedly** [comment]
We could also publish it to npm as something like `v1.0.0-rc.1` but I think that will be considered to be the current release that `npm install` and `npm update` use then :(

**Comment by germanattanasio** [comment]
what if we publish it as v1.0.0-beta

**Comment by nfriedly** [comment]
There might be a way to do it, with something like `npm publish --tag rc`, but I can't find much documentation on npm, and semver considers `v1.0.0-whatever to be newer than `v0.10.x` (see #11 on http://semver.org)

I'm hesitant because I've seen it screwed up quite a few times.

**Comment by germanattanasio** [comment]
I'm looking at the README and seems like we are saying that STT methods to create/delete sessions are going to be deprecated. I think we can still keep them since you can use the websocket with or without a session and to use it with a session you need to create it

**Comment by nfriedly** [comment]
Oh, alright then. I'll remove the deprecation bit about sessions.

Also, from talking to @othiym23 on IRC, it sounds like my guess about `npm publish --tag=rc` (or `beta` or whatever) is correct - adding the `--tag` will prevent npm from giving our prerelease versions to folks who are just trying to get the latest stable version.

**Comment by germanattanasio** [comment]
v1.0.0-beta was released!
