### ISSUE TITLE
Watson STT node.js SDK: Websocket abnormally closing with Error 1006

### ISSUE THREAD

**Issue by RMichaelPickering** [watson-developer-cloud/node-sdk#902]
**Overview**
Watson STT: Websocket abnormally closing with Error 1006
Our node.js app running in IBM Cloud connects to Watson STT using the Websocket protocol, latest ibm-watson sdk for node.js, and recognizeUsingWebsocket method. After a period of time during which per client connections from node.js to Watson STT service via Websocket work normally, all subsequent connections from node.js app to Watson STT fail with error code 1006.

**Expected behavior**
Connections to Watson STT using websockets and recognizeUsingWebsocket method work as documented.

**Actual behavior**
After some time, perhaps about one hour, all attempts to open a new Websocket connection from node.js server to Watson STT service using recognizeUsingWebsocket method fail with error code 1006.

**How to reproduce**
Create a node.js app that includes a websocket connection to Watson STT using recognizeUsingWebsocket method. Start node.js, open a connection, and stream some audio to Watson STT via recognizeUsingWebsocket. Observe normal behaviour -- receive transcription results from Watson STT. Close the connection. Wait a period of time, perhaps an hour or more, keeping the same node.js app live but inactive. Then attempt to connect to Watson STT again using recognizeUsingWebsocket method and receive error 1006. At this point, any further attempts to connect to Watson STT via websocket will continue to fail until node.js app is shut down and restarted.

**Screenshots**
Log from node.js showing initial connection to Watson STT:
![image](https://user-images.githubusercontent.com/16781901/60747889-880bf680-9f56-11e9-90de-bc9b31aa33fd.png)

Log after time has passed showing connection failure:
![image](https://user-images.githubusercontent.com/16781901/60747912-bb4e8580-9f56-11e9-8184-e5f9d37e347c.png)

**SDK Version**
ibm-watson current v4.x GA release for node.js

**Additional information:**
- OS: IBM Cloud Foundry - SDK for node.js
- node.js v10

**Additional context**
_Add any other details about the problem._

**Comment by dpopp07** [comment]
@RMichaelPickering Thanks for the detailed issue, I will look into it this week.

**Comment by dpopp07** [comment]
@RMichaelPickering I've been looking at this and wanted to give an update. Initially, I had a feeling that the token just wasn't being refreshed and that it would be a simple solution. Turns out, I was right about one thing - the token wasn't refreshing the way it should. I fixed that and now the token will expire after a while, the next request will get a new token, and the code continues working for a bit.

The bad news is that even after this process, once the app has been running for about an hour, (as you stated) a new connection will just not open. Even with a newly refreshed token. Unfortunately, I have no idea why this would be happening. This is going to require some deeper investigation. I'll keep you updated with my progress.

**Comment by RMichaelPickering** [comment]
@dpopp07 Thanks for the update -- yes, we KNEW there was an issue!
We may have found a workaround but it's a fairly obscure and involved approach for node.js, which is quite different from your sample code, and we're still having issues with connections not being very robust! Happy to get on a call to compare notes if it would help.

**Comment by dpopp07** [comment]
@RMichaelPickering I have a couple more things I would like to try today. I will let you know if I find anything new, after that a call to compare findings would be a good idea. I would be interested to hear about your workaround as well

**Comment by RMichaelPickering** [comment]
@dpopp07 Thanks for the further update! We're going to apply the latest update which fixes the token refresh issue, and make some further testing. Unfortunately, so far our workaround seems to not be entirely effective and we still have issues crop up after a period of time, but we want to apply your token fix and see if anything changes. So having a call later next week would make sense from our perspective, too!

**Comment by RMichaelPickering** [comment]
Please also see #849 which was originally opened 4 months ago -- this hasn't yet been fixed!!

**Comment by dpopp07** [comment]
@RMichaelPickering I was finally able to find the issue. It's unfortunate that something so simple eluded me for this long but the good news is, it's a very easy fix. I've tested your use case and once #920 is merged, this should work as expected. Thanks for your patience!

**Comment by RMichaelPickering** [comment]
@dpopp07 That is really excellent news! I feel your pain about how a relatively simple bug could cause such a subtle but big and difficult-to-solve problem. It happens to all of us sometimes! Truly glad that you've got it sorted out, and looking forward to test the fix!!
