### ISSUE TITLE
Payload length 33988 exceeds the payload limit 5120 bytes.

### ISSUE THREAD

**Issue by TheGP** [watson-developer-cloud/node-sdk#903]
Would be nice to fix it and allow to make longer audios.

**Comment by dpopp07** [comment]
@TheGP Will you provide more information about the problem you ran into?

In the SDK, we set the max content length to be "Infinity" and let the individual services handle the payload limits. It could be that the service (I am guessing you are working with Speech to Text?) has set a payload limit on the operation you are using.

Will you provide a code snippet and error message so I can try to reproduce your problem?

**Comment by TheGP** [comment]
@dpopp07 
`{
   "code_description": "Bad Request", 
   "code": 400, 
   "error": "Payload length 47818 exceeds the payload limit 5120 bytes."
}`

**Comment by dpopp07** [comment]
Are you using the `synthesize()` method? It has a documented upload limit of 5 KB of text. See the documentation [here](https://cloud.ibm.com/apidocs/text-to-speech#synthesize-audio).

The relevant text from the documentation:
> The method accepts a maximum of 5 KB of input text in the body of the request, and 8 KB for the URL and headers. The 5 KB limit includes any SSML tags that you specify. The service returns the synthesized audio stream as an array of bytes.

It looks like this is a limitation of the service and there is nothing in the SDK we can do about it

**Comment by oshihirii** [comment]
I am getting error:

    Error: Response not received. Body of error is HTTP ClientRequest object

How can i see the contents of that error to further troubleshoot?  

And can i add `maxContentLength: Infinity` to `new TextToSpeechV1()` parameters to resolve the issue?

I am already implementing logic that I believe would keep text content of requests under 5kb, so not sure why i am getting error.  Works fine locally, just testing online with larger requests (still under 5kb) and getting the error.
