### ISSUE TITLE
Cannot call Watson Assistant V1 with iam_client_id and iam_client_secret

### ISSUE THREAD

**Issue by henrikmatzen** [watson-developer-cloud/node-sdk#905]
**Overview**
When calling Watson Assistant v1 with **iam_client_id** and **iam_client_secret** following error is returned: 

`{ Unauthorized: Access is denied due to invalid credentials.
    at RequestWrapper.formatError (/home/janneme/ibm/eva-xxx/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:218:21)
    at /home/janneme/ibm/eva-xxx/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:206:29
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'Unauthorized',
  code: 401,
  message: 'Access is denied due to invalid credentials.',
  body: '{"code":401,"error":"Unauthorized"}',
  headers:
   { 'x-backside-transport': 'FAIL FAIL',
     connection: 'close',
     'transfer-encoding': 'chunked',
     date: 'Mon, 08 Jul 2019 09:44:04 GMT',
     'content-type': 'application/json',
     'x-dp-transit-id': 'gateway-fra-dp01-2262955649',
     'x-global-transaction-id': '683fc2df5d23106486e1f681',
     'strict-transport-security': 'max-age=31536000;',
     'x-dp-watson-tran-id': 'gateway-fra-dp01-2262955649' } }`

**Expected behavior**
Watson Assistant should use my client_id and secret to authenticate against IAM. I have revalidated the credentials with the IBM support and they are valid.

**SDK Version**
4.2.1

**Additional information:**
- OS: macOS Mojave, 10.14.5
- v9.11.1

**Comment by dpopp07** [comment]
@henrikmatzen This is odd behavior, thanks for the issue. To help with this, I would like a bit more info:

What parameters are you passing to the service constructor?

What is result of the debug logs? See [this section of the README](https://github.com/watson-developer-cloud/node-sdk#debug) for instructions on how to run in debug mode.

**Comment by dpopp07** [comment]
Closing as OP has solved their initial problem and is no longer using client ID/secrets.
