### ISSUE TITLE
Unable to connect to Cloud Pak (ICP4d) Watson instances using SDK

### ISSUE THREAD

**Issue by lagarwalla** [watson-developer-cloud/node-sdk#906]
**Overview**
Unable to connect to Watson Assistant running on ICP4d using SDK. The curl command works perfectly.

**Expected behavior**
The SDK should connect to Watson Service on ICP4d using Node v8

**Actual behavior**
It throws up SSL handshake error. Seems like this is caused by invalid untrusted SSL certificate of WA in ICP4d. The log throws up below error while using debug:
```
Error: write EPROTO 140735991276416:error:14077410:SSL 
routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake 
failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:
```
The generic error it produces without debug is:
```
Response not received. Body of error is HTTP ClientRequest object body
```

**How to reproduce**
Here is the code to connect to WA on ICP4d and it produces the error when using debug mode.
```
const AssistantV1 = require('ibm-watson/assistant/v1');
const service = new AssistantV1({
    version: '2019-02-28',
    icp4d_access_token: 'xxxxxxxx 500 char long toekn',
    url: 'https://icp-hostname:31843/assistant/wa-cloudpak/instances/1561981096/api',
    disable_ssl_verification: true
});

service.listWorkspaces()
  .then(res => {
    console.log(JSON.stringify(res, null, 2));
  })
  .catch(err => {
    console.log(err)
  });
```
**SDK Version**
SDK v4.1.2 and node version 8.x

**Comment by germanattanasio** [comment]
Hi @lagarwalla Thanks for writing the issue. Node 6 and 8 are not supported by this SDK but we haven't updated the README yet.

**Comment by lagarwalla** [comment]
With node10, I am able to connect to WA in ICP4d.

However with node10, I faced issue while connecting to IBM cloud's WA. The issue happens only from IBM office network (seems like some proxy thing). Node8 used to work well from IBM office network.

The error is:
```
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27
```
This error does not come when connecting from Home or Mobile or VPN network.

Details:
- Node 10
- Mac OS 10.13.6
- Error when used from IBM office network
