### ISSUE TITLE
speech-to-text streaming example

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/node-sdk#91]
https://gist.github.com/germanattanasio/359580d99ea22f47c6ba should go into the examples folder

**Comment by nfriedly** [comment]
(In general, I think we should include more examples. And maybe start giving each service a sub-folder under `examples/` rather than a single huge js file.)

**Comment by germanattanasio** [comment]
I would rather work on #110 than providing the live transcription using the REST api. We should also consider deprecating `recognizeLive`. Maybe something for #89

**Comment by nfriedly** [comment]
Aah, that's a good point.

**Comment by germanattanasio** [comment]
I'm going to close this and work on #110 Support for WebSockets.
