### ISSUE TITLE
DiscoveryV1.query() failed with error "BXNIM0408E: Provided refresh token is expired"

### ISSUE THREAD

**Issue by yosuke312** [watson-developer-cloud/node-sdk#934]
**Overview**
DiscoveryV1.query() failed with error "BXNIM0408E: Provided refresh token is expired"

**Expected behavior**
The request should get processed successfully even if refresh token is expired. SDK should handle OAuth flow to get a new access token using API keys behind the scenes without emitting the error back to the app.

**Actual behavior**
The promise returned got rejected with the following error.
```json
{
	"context": {
		"requestId": "bcaef5b6a33e477f90ffd275ee5d2453",
		"requestType": "incoming.Identity_Token",
		"userAgent": "watson-developer-cloud-nodejs-3.9.1;",
		"clientIp":"xx.xx.xx.xx",
		"url":"https://iam.bluemix.net",
		"instanceId":"iamid-4.3-6234-7b03afd-cb7bb68f6-xxxxx",
		"threadId":"15654f",
		"host":"iamid-4.3-6234-7b03afd-cb7bb68f6-xxxxx",
		"startTime":"12.08.2019 12:37:11:756 UTC",
		"endTime":"12.08.2019 12:37:11:757 UTC",
		"elapsedTime":"1",
		"locale":"en_US",
		"clusterName":"iam-id-prtok04-m9sc"
	},
	"errorCode": "BXNIM0408E",
	"errorMessage": "Provided refresh token is expired"
} 
```

**How to reproduce**
We have multiple servers running the same application that runs queries on the same Discovery instance, but the issue happened only on one specific server. The issue could be reproduced solidly on the failing server regardless of the query, but it went away after restarting the process on the failing server. The procedure that brought the server to the failing state is unknown. We have been running the same application for months, but this was the first time we experienced the issue.

**Screenshots**
N/A

**SDK Version**
3.9.1

**Additional information:**
- OS: Linux version 3.10.0-862.6.3.el7.x86_64
- Node: v8.12.0

**Additional context**
(See "How to reproduce" section)

**Comment by dpopp07** [comment]
Hmm that's pretty strange. In that version of the code, we assume the refresh tokens will expire after 30 days and we request a new token if the refresh token lives for about 7 days. Is it possible that no requests were made on that server for 7 days? If so, then it's possible the refresh token expired is less than 7 days and the refresh request failed.

In the newest versions of the SDK, we don't use the refresh tokens anymore. We just request new tokens using the API key once they expire. You could potentially avoid this issue by upgrading to the latest version.

If you think the 7 day lag period is the issue, I can release a fix that shortens the refresh time to 1 day or shorter.

**Comment by yosuke312** [comment]
Thank you for looking into this.

I checked our app's log, but is seems no request for 7 days is not the case here. The last successful DiscoveryV1.query() request from the server before the reported failure (2019/08/12-21.37.11.761) was 2019/08/12-00.01.11.693.

It is a good news that upgrading to the latest version will probably resolve the issue. We will do some testing and upgrade to the latest version as soon as possible.

**Comment by dpopp07** [comment]
@yosuke312 any updates on this issue?

**Comment by yosuke312** [comment]
@dpopp07 Sorry for my delayed response. We have experienced the same issue one more time with the old version of Watson SDK (3.9.1). We upgraded the SDK to the latest version yesterday as suggested, and we have not experienced the issue since then. We still cannot tell for sure if the issue has gone away because the issue seems to happen only once in a few months, but we are OK to close this ticket for now. We will reopen it should we experience the issue again. Thank you for your support.

**Comment by pgoldweic** [comment]
I am seeing the analogous issue but with the Watson Assistant service instead of discovery. The sdk version of watson-developer-cloud I'm running with is 3.18.4. We got an identical error code and error message in our production bot. This version is being used by the botkit-middleware-watson module, version 1.8.2. Any suggestions?

**Comment by dpopp07** [comment]
I still don't know how that could happen unless the refresh token was removed on the server side or in the case where no requests were made in 7+ days. Can you provide more details on your situation?

**Comment by pgoldweic** [comment]
Thanks for replying promptly. This message was received by our bot application that has been in continuous operation, so it is certainly NOT the case that there were no API calls made to Watson Assistant for 7+ days. Fortunately the next API call apparently worked out fine, but it is worrysome that this is occurring, of course, as it completely messed up that particular bot interaction :-(

**Comment by dpopp07** [comment]
Interesting. In that case, I'm really not sure why that would happen with a refresh token. I know this may not be ideal, but are you able to upgrade to either v4 or v5? We stopped using refresh tokens in these versions and so the potential for running into that issue again _should_ be eliminated.

**Comment by pgoldweic** [comment]
Well, I also wonder which version I could safely upgrade to. I'm waiting for a response to such question in the botkit-middleware-watson project. BTW, not sure if this helps at all with your understanding/diagnosis of the situation, but here is a bit more detail for the error:
Error: {"context":{"requestId":"047b58f8522341ed9dac1d5a64f0ffb9","requestType":"incoming.Identity_Token","userAgent":"NotSet","url":"https://iam.bluemix.net","instanceId":"...blah...","threadId":"35fccf","host":"...blah...","startTime":"05.12.2019 20:16:47:270 GMT","endTime":"05.12.2019 20:16:47:274 GMT","elapsedTime":"4","locale":"en_US","clusterName":"...blah..."},"errorCode":"BXNIM0408E","errorMessage":"Provided refresh token is expired"} {"cause":{"code":400},"isOperational":true,"code":400}

I can provide (via email perhaps) more detail if needed (e.g. instanceid, host). BTW, I noticed that the dates displayed are kind of old; not sure what that means though, as this happened yesterday.

**Comment by pgoldweic** [comment]
@dpopp07 , it would be helpful if you could comment on how safe (or relatively safe) it should be to upgrade to a later version of this module, given that I'm using the middleware I mentioned? (apparently, it uses only the 'message' method of Assistant, as far as I can see) .

**Comment by dpopp07** [comment]
@pgoldweic Looks like the middleware you mentioned is [using v4.2.5 of the Node SDK](https://github.com/watson-developer-cloud/botkit-middleware/blob/master/package.json#L59). Thus, you should be safe to update to v4, which should provide the benefit of not using refresh tokens

**Comment by pgoldweic** [comment]
I think you may have missed the fact that I'm using version 1.8.2 (and *not* the current version)  of botkit-middleware-watson, which in turn uses version 3.18.4 of watson-middleware-cloud (previous name for the current 'ibm-watson').

**Comment by dpopp07** [comment]
Oh I did miss that. I'm not familiar with that package so it's hard to say how safe it would be to upgrade. @germanattanasio might know better than me

**Comment by pgoldweic** [comment]
Well, I asked in the middleware github first; and the task -of figuring this up- was left for me to figure out, which I understand (since I'm using a legacy version).  As I mentioned earlier, in looking briefly at the source code for the botkit middleware, I see that the only method this middleware uses from Assistant V1 is essentially  'message'. Given this knowledge, what can you say about how the 'ibm-watson'  module (previously 'watson-middleware-cloud') has changed from version 3.18.4 to 4 as it respects to the 'message' method? Have parameters changed? Is there a change log that clearly states what has changed that I could take a look at? This would be really helpful.

**Comment by germanattanasio** [comment]
See https://github.com/watson-developer-cloud/node-sdk/blob/master/MIGRATION-V5.md

**Comment by pgoldweic** [comment]
Thanks @germanattanasio . That should certainly help!
