### ISSUE TITLE
Speech to Text stream stops working after multiple wav files.

### ISSUE THREAD

**Issue by mwoodsy** [watson-developer-cloud/node-sdk#940]
**Overview**
I have node service that listens for the creation a new wav file on a server. When the wav file is being recorded, a node module called GrowingFile streams the file to the watson speech to text service. Growing File allows for a timeout interval so the stream doesn't end until the wav file hasn't changed in X seconds, otherwise I would use fs.createReadStream for real time streaming of the file. This has worked for about a year or so when using the username and password authentication. Since updating my library to use the iamkey authentication this has stopped working. Or better said: it works a couple of times but eventually stops working and requires my node service to restart before it starts working again. At first I thought growing file or my code was the issue but after some debugging in the recognizeStream.js file I think the issue is the callback in _write(chunk, encoding, callback) but I'm not entirely sure what. Looking at an old library that works I see the only changes that may be related to this are how `this`  and  `self` are declared and used.  

**Expected behavior**
The filestream pipes to recognizeStream.prototype._write(chunk, encoding, callback) which opens a websocket to watson and sends the data over for transcription. After send  ( `afterSend(callback)` ) the callback is executed using process.nextTick(callback) at which time the file stream unpauses and pipes another chunk of data over to recognize stream.

The filestream pauses after each chunk is sent and unpauses when the callback is executed in the _write function. 

**Actual behavior**
When the callback executes the filestream does not unpause. 

At first I thought this was due to the websocket getting confused with repeat authentication attempts for each recording. In order to rule this out I modified the RecognizeStream.prototype._write as follows:

```js
RecognizeStream.prototype._write = function (chunk, encoding, callback) {
      console.log("received data, fire callback. chuck size:", chunk.length)
      callback() // unpause stream. Also tried process.nextTick(callback) with no luck
      return; //don't authenticate, don't send data out for transcription.

```

Watching the console I saw the first few recording printed out the line of text for as long as the recording was actively being recorded. After a few recordings the callback was only being called once but calling it did not unpause the stream. The wav file continued to grow but never would pipe new data to recognize-stream. 

**SDK Version**
4.3.3

**Additional information:**
Server: Centos 7
node version: 10

**Additional context**

service.js (wavFile is a var that has the path to the new wav file)
```js
var Watson = require('./watson');
// Some code to listen for new wav files.
...
trascribeFile(pathToWavFile)
...



function transcribeFile(wavFile){ 
  var sttEngine = new Watson(wavFile);
  sttEngine.start(function (data) {
     console.log("data.transcript: " + data.transcript);
  });
}
```

watson.js
```js
var SpeechToTextV1 = require('ibm-watson/speech-to-text/v1');
var GrowingFile = require('growing-file');

function Watson(file) {
    this.file = file;
    this.iam_apikey = 'my iamkey';
    this.url = 'url for iam key';
};

Watson.prototype.start = function (callback) {

    var speechParams = {
        iam_apikey: this.iam_apikey,
        url: this.url
    }

    var speech_to_text = new SpeechToTextV1(speechParams);
    var recognizeStream = speech_to_text.recognizeUsingWebSocket({
        content_type: 'audio/wav; rate=16000',
        smart_formatting: true,
        interim_results: true,
        objectMode: true
    }).on('data', function (data) {
        var results = {
            'transcript': data.results[0].alternatives[0].transcript
            };
        callback(results);
    });

//Fails after repeat recordings.
 GrowingFile(this.file,{timeout:15000,interval:100}).pipe(recognizeStream);

// Work around
/*
    let gf = GrowingFile.open(this.file, {
        timeout: 15000,
        interval: 100
    })

    gf.on('data', function(data) {
        recognizeStream._write(data, null, function () {
            return true;
        });
    }).on('end', function() {
        console.log('FILE HAS ENDED');
        recognizeStream.finish();
    })
*/
};

module.exports = Watson;
```

**Comment by mwoodsy** [comment]
I tried to recreate this using a static wav file of an old recording instead of a wav file that is actively being written too but can not reproduce the same behavior. This only seems to happen with a live recording.

**Comment by dpopp07** [comment]
@mwoodsy I apologize, I missed this issue when it was opened. That's pretty strange behavior. I appreciate you digging in the code and providing that information. I'll try to reproduce this today and start debugging from there

**Comment by dpopp07** [comment]
This is probably still an issue even though I have not been able to reproduce yet

**Comment by mediumTaj** [comment]
Still active

**Comment by apaparazzi0329** [comment]
@mwoodsy Do you know if this is still an issue in the latest version of the node-sdk, 6.2.2?
