### ISSUE TITLE
Support React Native

### ISSUE THREAD

**Issue by orome** [watson-developer-cloud/node-sdk#942]
If I attempt to import and use code that invokes the [Watson Assistant API][1] for Node, I get a fatal error

> The package at "node_modules/ibm-watson/lib/common.js" attempted to
> import the Node standard library module "os". It failed because React
> Native does not include the Node standard library.

I [gather][2] this means that it is not possible to use the Watson Node API with React Native.

What alternatives are available for using the Watson Assistant API with React Native? Should I just use `fetch` and follow the [Watson Assistant cURL API][3], and if so, how do construct the arguments to `fetch`, specifically `-u "apikey:{apikey}"`?

Perhaps the documentation could be improved to address this.

----

There is [partial example][4] of how to do this with version 1 of the Assistant API, but that uses a different authentication method and is not applicable here.

  [1]: https://cloud.ibm.com/apidocs/assistant-v2?code=node
  [2]: https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo
  [3]: https://cloud.ibm.com/apidocs/assistant-v2
  [4]: https://dev.to/tonydiaz/building-a-chatbot-using-react-native-and-watson-assistant-3adj

**Comment by dpopp07** [comment]
@orome Thanks for bringing this to our attention. The intention is to support the SDK on browser and browser-like environments, including React Native. There are some known issues, like the one you pointed out, that we are trying to solve. I will see if there is a short-term fix that could help you along, otherwise it's something we are trying to address for the v5 release at the end of September

**Comment by dpopp07** [comment]
@orome I have a good workaround for this now (I think!) and just published a release which should fix this issue. Try using `v4.5.3` of this library and let me know if it works for you or not. Thanks!

**Comment by orome** [comment]
@dpopp07 Nope. I get 'module "url"' now, but otherwise the same fatal problem. (With `v5.0.0` also.)

**Comment by dpopp07** [comment]
v5 doesn't include this fix yet - I want to make sure it works before I make that patch.

What error specifically are you getting?

**Comment by orome** [comment]
I get:

```
Unable to resolve module `url` from `/Users/Roy/Documents/Projects/Coding/React/enigma/node_modules/ibm-watson/authorization/v1.js`: Module `url` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.

ABI34_0_0RCTFatal
__37-[ABI34_0_0RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
0x0
```

**Comment by orome** [comment]
@dpopp07 Simply adding `new AssistantV2` is all I need to do to trigger that.

**Comment by dpopp07** [comment]
@orome Thanks for the information. This should be fixable, I will look at it more over the next couple of weeks

**Comment by dpopp07** [comment]
This is still something we need to look at

**Comment by Shing-Ho** [comment]
```
error: Error: Unable to resolve module `module` from `node_modules/ibm-watson/node_modules/stack-utils/index.js`: module could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (/Users/jy/Documents/Projects/React-Native/gabivoice/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (/Users/jy/Documents/Projects/React-Native/gabivoice/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/jy/Documents/Projects/React-Native/gabivoice/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/Users/jy/Documents/Projects/React-Native/gabivoice/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/jy/Documents/Projects/React-Native/gabivoice/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/jy/Documents/Projects/React-Native/gabivoice/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /Users/jy/Documents/Projects/React-Native/gabivoice/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/jy/Documents/Projects/React-Native/gabivoice/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```
I am getting this problem, Any thing that I can do?
