### ISSUE TITLE
Support webhooks when updating workspace

### ISSUE THREAD

**Issue by ChrisSchneider** [watson-developer-cloud/node-sdk#945]
When updating the Watson Assistant workspace with the node-sdk, the `webhooks` property is ignored.

Updating the workspace with a workspace JSON that contains a webhook works in the REST API.

**Comment by dpopp07** [comment]
@ChrisSchneider Will you provide a little more detail? What method are you trying to call - `updateWorkspace`? Can you provide an example of the object you are talking about? I don't see mention of a `webhooks` property anywhere in the Assistant documentation.

Also, what version date are you using? It's possible that this is an additional property that used to be supported but isn't anymore. You may be able to fix this by changing your version date
