### ISSUE TITLE
The npm package is very big and contains  nearly 1MB of test output

### ISSUE THREAD

**Issue by Tissandier** [watson-developer-cloud/node-sdk#952]
**Overview**
The npm package is very big and contains some nearly 1MB of test output

**Expected behavior**
We expect the package to be smaller

**Actual behavior**
See the file test-output.log in the package this file is nearly 1MB, there is maybe other files like that in the distribution.

**How to reproduce**
Just install the package 

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**SDK Version**
_Please provide the SDK version here._
4.3.0

**Additional information:**
- OS: Any
- Which version of `Node` are you using? The problem does not depend on Node version.

**Additional context**
_Add any other details about the problem._

**Comment by germanattanasio** [comment]
@Tissandier I think this is a matter of adding a few keys to `.npmignore`. @Tissandier since you found the issue, do you mind doing a PR?

**Comment by cjolif** [comment]
thanks a lot, when do you think you'll have a NPM release with the fix included?

**Comment by dpopp07** [comment]
@cjolif I'm having some issues with the build but should be out by the end of the day today
