### ISSUE TITLE
NLP classifier url is not corrected v1.js in V4.4.0

### ISSUE THREAD

**Issue by Yingmin-Li** [watson-developer-cloud/node-sdk#961]
The static URL is not correct in  [natural-language-classifier/v1.ts](https://github.com/watson-developer-cloud/node-sdk/blob/master/natural-language-classifier/v1.ts) 

---

**Overview**
_Call NLP classifier API return 401 Unauthorized: Access is denied due to invalid credentials._

**Expected behavior**
_Return 200_

**Actual behavior**
_return 401 Unauthorized: Access is denied due to invalid credentials_

**How to reproduce**
_Follow the example on [IBM API doc](https://cloud.ibm.com/apidocs/natural-language-classifier?code=node#classify-multiple-phrases) _

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**SDK Version**
_4.4.0_

**Additional information:**
- OS: _Windows 10_
- Node: _v12.10.0_

**Additional context**
_Change the static url in line 369 from [gateway](https://gateway.watsonplatform.net/natural-language-classifier/api) to [gateway-fra](https://gateway-fra.watsonplatform.net/natural-language-classifier/api) can resolve the issue_

**Comment by dpopp07** [comment]
@Yingmin-Li The static URL is just a default URL and is for the US-South region. It is not intended to work for every user.

If your service is deployed in a different region, like France, you need to set your own URL. You can do this in the service constructor, like so:

```js
const naturalLanguageClassifier = new NaturalLanguageClassifierV1({
  iam_apikey: '{apikey}',
  url: 'https://gateway-fra.watsonplatform.net/natural-language-classifier/api',
});
```
