### ISSUE TITLE
SDK identify response doesn't match the service response

### ISSUE THREAD

**Issue by sgilra** [watson-developer-cloud/node-sdk#963]
#### Expected behavior
Language Identified `English`
#### Actual behavior
Language Identified `Icelandic`
#### Steps to reproduce the problem
Text used:
```
Hello,
 
One of my team members continuously receives the notification below, bur isn’t able to complete the set-up because of the error.
 
Can you please assist her?
 
Joyce van Vliet
B91944
```
**Screenshots**

<img width="538" alt="Screen Shot 2019-09-18 at 4 15 55 PM" src="https://user-images.githubusercontent.com/19226641/65182600-a77fcf00-da2f-11e9-8416-6a436ad7cad4.png">

**SDK Version**
Not sure which version the LT public demo (https://language-translator-demo.ng.bluemix.net/) is using but its on Node js

**Additional information:**
This is also reproducible for Python SDK as stated by @hvanderveer 

**Additional context**
The same text when passed directly to the service returns `English`

```
curl -u apikey:XXX "https://gateway.watsonplatform.net:443/language-translator/api/v3/identify?version=2018-05-01" -H "content-type:text/plain" -d @identify.txt
{
  "languages" : [ {
    "language" : "en",
    "confidence" : 0.5343359232949358
  }, {
    "language" : "is",
    "confidence" : 0.43247035220341196
  }, {
```

**Comment by dpopp07** [comment]
@sgilra Thanks for the issue, I will look into this

**Comment by sgilra** [comment]
Not reproducible. Closing as fixed upstream with a deployment of new LID model.
