### ISSUE TITLE
unable to get APIKEY from ibm-credentials.env

### ISSUE THREAD

**Issue by kyokonishito** [watson-developer-cloud/node-sdk#965]
**Overview**
If I put ibm-credentials.env in the working dir, an error is occured with following message:

```
Error: Insufficient credentials provided in constructor argument. Refer to the documentation for the required parameters. Common examples are username/password and iam_apikey.
```
The format of ibm-credentials.env was changed. For example, if I use LanguageTranslator,
current APIKEY's key is:
`LANGUAGE_TRANSLATOR_APIKEY`

The  **OLD** APIKEY's key is:
`LANGUAGE_TRANSLATOR_IAM_APIKEY`

ibm-cloud-sdk-core/lib/base_service.js should be updated to read current format. Current code can read only old one `*_IAM_APIKEY`.

**Expected behavior**
If I put ibm-credentials.env in the working dir, we can not set apikey and url in the source codes.

**Actual behavior**
If I put ibm-credentials.env in the working dir, we have an error.

**How to reproduce**
1. Create following file named with translate.js:
```Javascript
const LanguageTranslatorV3 = require('ibm-watson/language-translator/v3');

const languageTranslator = new LanguageTranslatorV3({
  version: '2018-05-01',
});

const translateParams = {
  text: 'Hello',
  model_id: 'en-es',
};

languageTranslator.translate(translateParams)
  .then(translationResult => {
    console.log(JSON.stringify(translationResult, null, 2));
  })
  .catch(err => {
    console.log('error:', err);
  });

```
2. install ibm-watson library in same folder of  translate.js:

`npm install ibm-watson`

3. Download `ibm-credentials.env` from Language Translation service page in  IBM Cloud Web.
(need to create the service before that)

4. Run the following command:
`node translate.js`

**Screenshots**
![image](https://user-images.githubusercontent.com/40123488/65222072-49b7b980-daf9-11e9-9b50-723cff622932.png)

**SDK Version**
ibm-watson@4.5.0

**Additional information:**
os: macOS Mojave 10.14.6
node: v10.16.3

**Comment by dpopp07** [comment]
@kyokonishito Thanks for the issue. That format of the credentials file is what we are moving towards and will be compatible with our next major release but I didn't know we had changed it already.

@lpatino10 Did we already make these changes to the credentials file? I don't think that is compatible with any of our current SDKs

**Comment by lpatino10** [comment]
Hey @kyokonishito, sorry about that. I was responsible for updating that a little prematurely 😞 

I'm working now to revert that and make the file compatible with the SDK. I'll report back when that's done. In the meantime, you can manually change that key back to `LANGUAGE_TRANSLATOR_IAM_APIKEY` as a workaround.

**Comment by kyokonishito** [comment]
@lpatino10 Thanks! I'm waiting for the completion.

**Comment by lpatino10** [comment]
Hey @kyokonishito, the change should be live now.

**Comment by kyokonishito** [comment]
@lpatino10 Thank you for your quick action! I confirmed the fix. I closed this issue.
