### ISSUE TITLE
Node.js code not working from the API docs

### ISSUE THREAD

**Issue by lidderupk** [watson-developer-cloud/node-sdk#980]
**Overview**
The code for Node.js from the API docs does not work.
```
const visualRecognition = new VisualRecognitionV3({
  version: '2018-03-19',
  iam_apikey:  vrKey
});
```

 I get the following error:

```
Error: Missing required parameters: apikey
    at Object.getMissingParams (/Users/ulidder/Documents/icloud-documents/code-upkar/att5g/vr/node_modules/ibm-cloud-sdk-core/lib/helper.js:101:11)
    at Object.validateInput (/Users/ulidder/Documents/icloud-documents/code-upkar/att5g/vr/node_modules/ibm-cloud-sdk-core/auth/utils/helpers.js:61:39)
    at new IamAuthenticator (/Users/ulidder/Documents/icloud-documents/code-upkar/att5g/vr/node_modules/ibm-cloud-sdk-core/auth/authenticators/iam-authenticator.js:47:17)
```

**Expected behavior**
Expected the code in API docs to work without throwing the error. I got it working with the following code

```
const visualRecognition = new VisualRecognitionV3({
  version: '2018-03-19',
  authenticator: new IamAuthenticator({ apikey: vrKey }),
});
```

**Actual behavior**
Get error
```
Error: Missing required parameters: apikey
    at Object.getMissingParams (/Users/ulidder/Documents/icloud-documents/code-upkar/att5g/vr/node_modules/ibm-cloud-sdk-core/lib/helper.js:101:11)
    at Object.validateInput (/Users/ulidder/Documents/icloud-documents/code-upkar/att5g/vr/node_modules/ibm-cloud-sdk-core/auth/utils/helpers.js:61:39)
    at new IamAuthenticator (/Users/ulidder/Documents/icloud-documents/code-upkar/att5g/vr/node_modules/ibm-cloud-sdk-core/auth/authenticators/iam-authenticator.js:47:17)
```

**How to reproduce**
Copy paste the code from the Node.js API docs.

**Screenshots**
N/A

**SDK Version**
`const VisualRecognitionV3 = require('ibm-watson/visual-recognition/v3');`

**Additional information:**
`Node version v11.14.0`

**Additional context**
Ran into this error at a hackathon. The Python code works as it is. Node.js does not.

**Comment by SirSpidey** [comment]
You've caught us in between releasing the SDK major version and updating the docs. For now, take a look at the example at https://github.com/watson-developer-cloud/node-sdk/blob/master/README.md#visual-recognition that shoes the authentication

**Comment by hgw2101** [comment]
For reference, the affected Node version here is 8.10.

**Comment by lidderupk** [comment]
@SirSpidey, that is what I ended up doing. But I don't think other people make that connection and unfortunately just give up on the service. I am an IBMer at a hackathon. I expected the code example in the official API docs to work without having to dig into the SDK source :(. It is also concerning that the examples between API docs and the SDK Github docs are different. Thank you for your attention to this.

**Comment by mkistler** [comment]
@SirSpidey This is a bug in the front matter for the Node SDK in that it does not specify the version of the Node SDK -- unlike all the other languages.  We need to update the Node front-matter to change:
```
npm install ibm-watson
```
to something like:
```
npm install ibm-watson@^4.0.0
```

While we're at it, we should throw in '--save', so that it adds the dependency to the application's package.json.  So I recommend that the front-matter update for the new major release should be
```
npm install --save ibm-watson@^5.0.0
```

**Comment by MasterOdin** [comment]
> While we're at it, we should throw in '--save', so that it adds the dependency to the application's package.json

Since NPM 5, that's the default behavior unless specified otherwise.

**Comment by SirSpidey** [comment]
@mkistler Got it. Will update the front matter for the install command. Yes, we just removed the `--save` option.

**Comment by germanattanasio** [comment]
@SirSpidey was this fixed?

**Comment by SirSpidey** [comment]
Yes. install is now in this format `npm install ibm-watson@^5.2.0`.
