### ISSUE TITLE
I guess a typo in readme's sample code text_to_speech

### ISSUE THREAD

**Issue by ericqqqqq** [watson-developer-cloud/node-sdk#986]
**Check service status**

**Overview**
https://github.com/watson-developer-cloud/node-sdk/blame/master/README.md#L721
the argument `audio` should be `repairedFile`

**Expected behavior**
Sample code store a wav file called audio.wav

**Actual behavior**
There is an error because the variable audio is not in the callback function closure. `ReferenceError: audio is not defined`

**How to reproduce**
running sample code `Text to Speech` will reproduce the issue

**Comment by dpopp07** [comment]
@ericqqqqq Good catch! Thanks for posting, this has been corrected
