### ISSUE TITLE
createSession from Assistant V2 in ibm-watson Version 5.1.0 is not working behind http proxy

### ISSUE THREAD

**Issue by ChristianStornowski** [watson-developer-cloud/node-sdk#991]
**Overview**
My enterprise is using a http proxy and because of that `createSession` from `ibm-watson/assistant/v2` is not working. Internally a token from https://iam.cloud.ibm.com/identity/token is created with an axios https post call.
I think axios is not working with https post calls and http proxy.

**Expected behavior**
```
{
  "result": {
     "session_id": "XXX-XXXX-XXXX-XXX-XXXX"
  }
}
```

**Actual behavior**
```
Error: write EPROTO 13072:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:

    at RequestWrapper.formatError (xxx\node_modules\ibm-cloud-sdk-core\lib\request-wrapper.js:207:21)
    at xxx\node_modules\ibm-cloud-sdk-core\lib\request-wrapper.js:195:25
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  message: 'write EPROTO 13072:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\\ws\\deps\\openssl\\openssl\\ssl\\record\\ssl3_record.c:332:\n',
  statusText: 'EPROTO',
  body: 'Response not received - no connection was made to the service.'
}

```

**How to reproduce**
Use a http proxy, via Environment Variable `http_proxy` and `https_proxy` and execute this code:

```
const AssistantV2 = require('ibm-watson/assistant/v2'); // watson sdk
const {IamAuthenticator} = require('ibm-watson/auth'); // watson sdk
const HttpsProxyAgent = require('https-proxy-agent'); // https Agent

const assistantV2 = new AssistantV2({
    authenticator: new IamAuthenticator({apikey: "XXX"}),
    version: '2019-02-28',
    url: "YYY",
    headers: {
        'X-Watson-Learning-Opt-Out': 'true'
    },
    httpsAgent: new HttpsProxyAgent("http://proxy.example.com:PORT")
});

assistant.createSession({
    assistantId: 'XXX-XXX-XXX-XXX'
})
    .then(res => {
        console.log(JSON.stringify(res, null, 2));
    })
    .catch(err => {
        console.log(err);
    });
```

**SDK Version**
4.2.1

**Additional information:**
- OS: Windows 10
- nodejs: 12.6.0

**Additional context**
This problem was fixed in version 4.3.2 with this ticket: https://github.com/watson-developer-cloud/node-sdk/issues/900. But after updating to Version 5.1.0 i have this problem again.

**Comment by dpopp07** [comment]
Hi @ChristianStornowski - I believe I know the issue here.

The `IamAuthenticator` is sending a request to the token server to retrieve the token. The authenticator has _its own_ HTTPS agent so you need to configure it there also:

```js
const AssistantV2 = require('ibm-watson/assistant/v2'); // watson sdk
const {IamAuthenticator} = require('ibm-watson/auth'); // watson sdk
const HttpsProxyAgent = require('https-proxy-agent'); // https Agent

const httpsAgent = new HttpsProxyAgent("http://proxy.example.com:PORT");

const assistantV2 = new AssistantV2({
    authenticator: new IamAuthenticator({apikey: "XXX", httpsAgent}), // Agent added here
    version: '2019-02-28',
    url: "YYY",
    headers: {
        'X-Watson-Learning-Opt-Out': 'true'
    },
    httpsAgent,
});

assistant.createSession({
    assistantId: 'XXX-XXX-XXX-XXX'
})
    .then(res => {
        console.log(JSON.stringify(res, null, 2));
    })
    .catch(err => {
        console.log(err);
    });
```

Sorry you're running into this again! Let me know how this goes

**Comment by ChristianStornowski** [comment]
Thanks for the short response. :-)

I and/or my coworker will test this asap and report(s), hopefully, a success with our solution.

**Comment by ChristianStornowski** [comment]
It's working with
`authenticator: new IamAuthenticator({apikey: "XXX", httpsAgent}),`
:-)

thx.

**Comment by dpopp07** [comment]
Excellent! Before, the SDK would share the agent between the service and token requests. Now, they are configured independently so users are not forced to use the same configuration for both.
