### ISSUE TITLE
watson middleware is not working behind http proxy - Response not received. Body of error is HTTP ClientRequest object

### ISSUE THREAD

**Issue by juanpablo64** [watson-developer-cloud/node-sdk#999]
Hello! I am trying to run a botkit application that uses IBM watson assistant as middleware. The problem is, while the whole system works on my local PC, on the server we are deplyoing it into I get the error message when I try sending a message:

```
Error: Response not received. Body of error is HTTP ClientRequest object
    at RequestWrapper.formatError (/home/desa/webchatbot/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:218:21)
    at /home/desa/webchatbot/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:206:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  message: 'Response not received. Body of error is HTTP ClientRequest object',
```

the expected behaviour is: Message is sent to watson IBM assistant, the message is processed and the appropiate response is sent back. Here's how I call the service.

![image](https://user-images.githubusercontent.com/7575105/69353643-96d11c80-0c5d-11ea-8caa-03b84d995b83.png)

**Comment by dpopp07** [comment]
@juanpablo64 I see you are specifying the proxy directly, which `axios` cannot handle very well. Please try [this method](https://github.com/watson-developer-cloud/node-sdk#use-behind-a-corporate-proxy) and let me know if it solves your issue.

**Comment by juanpablo64** [comment]
thank you so much! it worked as you said!
